"""Seed data for the California School Dashboard accountability layer.

Three things are transcribed here:

``_INDICATORS``
    The seven state indicators, and which direction each is judged in.
``_CUTPOINTS``
    The status and change bands from the state's five-by-five colored tables
    at https://www.cde.ca.gov/ta/ac/cm/fivebyfivecolortables.asp.  Bounds are
    inclusive; an open end is ``None``, which is how the tables read ("+45.0
    points or more", "-70.1 points or fewer").
``_COLOR_CELLS``
    Every status x change cell of every grid.  The full-denominator cells are
    on that same page; the small-denominator ones are not published as tables
    anywhere and were derived from the indicator files themselves, then
    checked against the page wherever the two overlap.

Two rules are carried in code rather than data, in
:mod:`app.service.dashboard_projection`:

* Entities with fewer than 150 students are judged on a reduced grid.  For
  chronic absenteeism, suspension and college/career the five change bands
  collapse to three -- "increased significantly" folds into "increased" and
  "declined significantly" into "declined" -- and the cut points are otherwise
  unchanged.  Graduation keeps five bands but uses its own colors.
* A row flagged ``dataerrorflag`` carries a state override rather than a grid
  result, and is never reproduced.

Together these reproduce every ``statuslevel``, ``changelevel`` and ``color``
in the 2024-25 files exactly; see ``tests/service/test_dashboard_projection``.

Variants keep a cut point tied to the table it came from: suspension is
published as six tables keyed by the file's ``type`` column (``ED``, ``HD``,
``UD`` for districts; ``ES``, ``MS``, ``HS`` for schools) and the academic
indicators as two, split by the ``hscutpoints`` flag.
"""

from __future__ import annotations

from decimal import Decimal

from sqlmodel import Session

from app.model.dashboard import (
    DashboardColorCell,
    DashboardCutpoint,
    DashboardIndicator,
    DashboardStudentGroup,
)

# (code, name, short name, lower_is_better, unit, sort order, informational)
type _Indicator = tuple[str, str, str, bool, str, int, bool]
# (indicator, variant, kind, level, lower bound, upper bound, label)
type _Cutpoint = tuple[str, str, str, int, Decimal | None, Decimal | None, str]
# (indicator, variant, small denominator, status level, change level, color)
type _ColorCell = tuple[str, str, bool, int, int, int | None]

# (code, name, category, sort order)
type _StudentGroup = tuple[str, str, str, int]

_STUDENT_GROUPS: tuple[_StudentGroup, ...] = (
    ("ALL", "All Students", "All", 1),
    ("AA", "Black/African American", "Race or ethnicity", 10),
    ("AI", "American Indian or Alaska Native", "Race or ethnicity", 11),
    ("AS", "Asian", "Race or ethnicity", 12),
    ("FI", "Filipino", "Race or ethnicity", 13),
    ("HI", "Hispanic", "Race or ethnicity", 14),
    ("PI", "Native Hawaiian or Pacific Islander", "Race or ethnicity", 15),
    ("WH", "White", "Race or ethnicity", 16),
    ("MR", "Two or More Races", "Race or ethnicity", 17),
    ("EL", "English Learners", "English learner", 20),
    ("ELO", "English Learners Only", "English learner", 21),
    ("LTEL", "Long-Term English Learners", "English learner", 22),
    ("RFP", "Reclassified Fluent English Proficient", "English learner", 23),
    ("EO", "English Only", "English learner", 24),
    ("SED", "Socioeconomically Disadvantaged", "Student group", 30),
    ("SWD", "Students with Disabilities", "Student group", 31),
    ("FOS", "Foster Youth", "Student group", 32),
    ("HOM", "Homeless Youth", "Student group", 33),
    # The academic indicator files split by which test a student sat.
    ("SBA", "Smarter Balanced Assessment", "Assessment type", 40),
    ("CAA", "California Alternate Assessment", "Assessment type", 41),
    ("CAST", "California Science Test", "Assessment type", 42),
)

_INDICATORS: tuple[_Indicator, ...] = (
    ("ELA", "English Language Arts/Literacy", "ELA", False, "dfs", 1, False),
    ("MATH", "Mathematics", "Math", False, "dfs", 2, False),
    ("CHRO", "Chronic Absenteeism", "Chronic Absenteeism", True, "percent", 3, False),
    ("SUSP", "Suspension Rate", "Suspension", True, "percent", 4, False),
    ("GRAD", "Graduation Rate", "Graduation", False, "percent", 5, False),
    ("CCI", "College/Career", "College/Career", False, "percent", 6, False),
    ("ELPI", "English Learner Progress", "EL Progress", False, "percent", 7, False),
    ("SCIENCE", "Science", "Science", False, "points", 8, False),
    # Published in the same file family but outside the accountability system.
    (
        "ELPACPART",
        "ELPAC Participation Rate",
        "ELPAC Participation",
        False,
        "percent",
        9,
        True,
    ),
)

_CUTPOINTS: tuple[_Cutpoint, ...] = (
    (
        "CCI",
        "ALL",
        "change",
        5,
        Decimal("9.0"),
        None,
        "Increased Significantly from Prior Year",
    ),
    (
        "CCI",
        "ALL",
        "change",
        4,
        Decimal("2.0"),
        Decimal("8.9"),
        "Increased from Prior Year",
    ),
    (
        "CCI",
        "ALL",
        "change",
        3,
        Decimal("-1.9"),
        Decimal("1.9"),
        "Maintained from Prior Year",
    ),
    (
        "CCI",
        "ALL",
        "change",
        2,
        Decimal("-9.0"),
        Decimal("-2.0"),
        "Declined from Prior Year",
    ),
    (
        "CCI",
        "ALL",
        "change",
        1,
        None,
        Decimal("-9.1"),
        "Declined Significantly from Prior Year",
    ),
    ("CCI", "ALL", "status", 5, Decimal("70.0"), None, "Very High"),
    ("CCI", "ALL", "status", 4, Decimal("55.0"), Decimal("69.9"), "High"),
    ("CCI", "ALL", "status", 3, Decimal("35.0"), Decimal("54.9"), "Medium"),
    ("CCI", "ALL", "status", 2, Decimal("10.0"), Decimal("34.9"), "Low"),
    ("CCI", "ALL", "status", 1, None, Decimal("9.9"), "Very Low"),
    (
        "CHRO",
        "ALL",
        "change",
        5,
        None,
        Decimal("-3.0"),
        "Declined Significantly from Prior Year",
    ),
    (
        "CHRO",
        "ALL",
        "change",
        4,
        Decimal("-2.9"),
        Decimal("-0.5"),
        "Declined from Prior Year",
    ),
    (
        "CHRO",
        "ALL",
        "change",
        3,
        Decimal("-0.4"),
        Decimal("0.4"),
        "Maintained from Prior Year",
    ),
    (
        "CHRO",
        "ALL",
        "change",
        2,
        Decimal("0.5"),
        Decimal("3.0"),
        "Increased from Prior Year",
    ),
    (
        "CHRO",
        "ALL",
        "change",
        1,
        Decimal("3.1"),
        None,
        "Increased Significantly from Prior Year",
    ),
    ("CHRO", "ALL", "status", 5, None, Decimal("2.5"), "Very Low"),
    ("CHRO", "ALL", "status", 4, Decimal("2.6"), Decimal("5.0"), "Low"),
    ("CHRO", "ALL", "status", 3, Decimal("5.1"), Decimal("10.0"), "Medium"),
    ("CHRO", "ALL", "status", 2, Decimal("10.1"), Decimal("20.0"), "High"),
    ("CHRO", "ALL", "status", 1, Decimal("20.1"), None, "Very High"),
    (
        "ELA",
        "ALL",
        "change",
        5,
        Decimal("15.0"),
        None,
        "Increased Significantly from Prior Year",
    ),
    (
        "ELA",
        "ALL",
        "change",
        4,
        Decimal("3.0"),
        Decimal("14.9"),
        "Increased from Prior Year",
    ),
    (
        "ELA",
        "ALL",
        "change",
        3,
        Decimal("-2.9"),
        Decimal("2.9"),
        "Maintained from Prior Year",
    ),
    (
        "ELA",
        "ALL",
        "change",
        2,
        Decimal("-15.0"),
        Decimal("-3.0"),
        "Declined from Prior Year",
    ),
    (
        "ELA",
        "ALL",
        "change",
        1,
        None,
        Decimal("-15.1"),
        "Declined Significantly from Prior Year",
    ),
    ("ELA", "ALL", "status", 5, Decimal("45.0"), None, "Very High"),
    ("ELA", "ALL", "status", 4, Decimal("10.0"), Decimal("44.9"), "High"),
    ("ELA", "ALL", "status", 3, Decimal("-5.0"), Decimal("9.9"), "Medium"),
    ("ELA", "ALL", "status", 2, Decimal("-70.0"), Decimal("-5.1"), "Low"),
    ("ELA", "ALL", "status", 1, None, Decimal("-70.1"), "Very Low"),
    (
        "ELA",
        "HS",
        "change",
        5,
        Decimal("15.0"),
        None,
        "Increased Significantly from Prior Year",
    ),
    (
        "ELA",
        "HS",
        "change",
        4,
        Decimal("3.0"),
        Decimal("14.9"),
        "Increased from Prior Year",
    ),
    (
        "ELA",
        "HS",
        "change",
        3,
        Decimal("-2.9"),
        Decimal("2.9"),
        "Maintained from Prior Year",
    ),
    (
        "ELA",
        "HS",
        "change",
        2,
        Decimal("-15.0"),
        Decimal("-3.0"),
        "Declined from Prior Year",
    ),
    (
        "ELA",
        "HS",
        "change",
        1,
        None,
        Decimal("-15.1"),
        "Declined Significantly from Prior Year",
    ),
    ("ELA", "HS", "status", 5, Decimal("75.0"), None, "Very High"),
    ("ELA", "HS", "status", 4, Decimal("30.0"), Decimal("74.9"), "High"),
    ("ELA", "HS", "status", 3, Decimal("0.0"), Decimal("29.9"), "Medium"),
    ("ELA", "HS", "status", 2, Decimal("-45.0"), Decimal("-0.1"), "Low"),
    ("ELA", "HS", "status", 1, None, Decimal("-45.1"), "Very Low"),
    (
        "ELPI",
        "ALL",
        "change",
        5,
        Decimal("10.0"),
        None,
        "Increased Significantly From Prior Year",
    ),
    (
        "ELPI",
        "ALL",
        "change",
        4,
        Decimal("2.0"),
        Decimal("9.9"),
        "Increased From Prior Year",
    ),
    (
        "ELPI",
        "ALL",
        "change",
        3,
        Decimal("-1.9"),
        Decimal("1.9"),
        "Maintained From Prior Year",
    ),
    (
        "ELPI",
        "ALL",
        "change",
        2,
        Decimal("-10"),
        Decimal("-2.0"),
        "Declined From Prior Year",
    ),
    (
        "ELPI",
        "ALL",
        "change",
        1,
        None,
        Decimal("-10.1"),
        "Declined Significantly From Prior Year",
    ),
    ("ELPI", "ALL", "status", 5, Decimal("65.0"), None, "Very High"),
    ("ELPI", "ALL", "status", 4, Decimal("55.0"), Decimal("64.9"), "High"),
    ("ELPI", "ALL", "status", 3, Decimal("45.0"), Decimal("54.9"), "Medium"),
    ("ELPI", "ALL", "status", 2, Decimal("35.0"), Decimal("44.9"), "Low"),
    ("ELPI", "ALL", "status", 1, None, Decimal("34.9"), "Very Low"),
    (
        "GRAD",
        "ALL",
        "change",
        5,
        Decimal("5.0"),
        None,
        "Increased Significantly from Prior Year",
    ),
    (
        "GRAD",
        "ALL",
        "change",
        4,
        Decimal("1.0"),
        Decimal("4.9"),
        "Increased from Prior Year",
    ),
    (
        "GRAD",
        "ALL",
        "change",
        3,
        Decimal("-0.9"),
        Decimal("0.9"),
        "Maintained from Prior Year",
    ),
    (
        "GRAD",
        "ALL",
        "change",
        2,
        Decimal("-5.0"),
        Decimal("-1.0"),
        "Declined from Prior Year",
    ),
    (
        "GRAD",
        "ALL",
        "change",
        1,
        None,
        Decimal("-5.1"),
        "Declined Significantly from Prior Year",
    ),
    ("GRAD", "ALL", "status", 5, Decimal("95.0"), None, "Very High"),
    ("GRAD", "ALL", "status", 4, Decimal("90.5"), Decimal("94.9"), "High"),
    ("GRAD", "ALL", "status", 3, Decimal("80.0"), Decimal("90.4"), "Medium"),
    ("GRAD", "ALL", "status", 2, Decimal("68.0"), Decimal("79.9"), "Low"),
    ("GRAD", "ALL", "status", 1, None, Decimal("67.9"), "Very Low"),
    (
        "MATH",
        "ALL",
        "change",
        5,
        Decimal("15.0"),
        None,
        "Increased Significantly from Prior Year",
    ),
    (
        "MATH",
        "ALL",
        "change",
        4,
        Decimal("3.0"),
        Decimal("14.9"),
        "Increased from Prior Year",
    ),
    (
        "MATH",
        "ALL",
        "change",
        3,
        Decimal("-2.9"),
        Decimal("2.9"),
        "Maintained from Prior Year",
    ),
    (
        "MATH",
        "ALL",
        "change",
        2,
        Decimal("-15.0"),
        Decimal("-3.0"),
        "Declined from Prior Year",
    ),
    (
        "MATH",
        "ALL",
        "change",
        1,
        None,
        Decimal("-15.1"),
        "Declined Significantly from Prior Year",
    ),
    ("MATH", "ALL", "status", 5, Decimal("35.0"), None, "Very High"),
    ("MATH", "ALL", "status", 4, Decimal("0.0"), Decimal("34.9"), "High"),
    ("MATH", "ALL", "status", 3, Decimal("-25.0"), Decimal("-0.1"), "Medium"),
    ("MATH", "ALL", "status", 2, Decimal("-95.0"), Decimal("-25.1"), "Low"),
    ("MATH", "ALL", "status", 1, None, Decimal("-95.1"), "Very Low"),
    (
        "MATH",
        "HS",
        "change",
        5,
        Decimal("15.0"),
        None,
        "Increased Significantly from Prior Year",
    ),
    (
        "MATH",
        "HS",
        "change",
        4,
        Decimal("3.0"),
        Decimal("14.9"),
        "Increased from Prior Year",
    ),
    (
        "MATH",
        "HS",
        "change",
        3,
        Decimal("-2.9"),
        Decimal("2.9"),
        "Maintained from Prior Year",
    ),
    (
        "MATH",
        "HS",
        "change",
        2,
        Decimal("-15.0"),
        Decimal("-3.0"),
        "Declined from Prior Year",
    ),
    (
        "MATH",
        "HS",
        "change",
        1,
        None,
        Decimal("-15.1"),
        "Declined Significantly from Prior Year",
    ),
    ("MATH", "HS", "status", 5, Decimal("25.0"), None, "Very High"),
    ("MATH", "HS", "status", 4, Decimal("0.0"), Decimal("24.9"), "High"),
    ("MATH", "HS", "status", 3, Decimal("-60.0"), Decimal("-0.1"), "Medium"),
    ("MATH", "HS", "status", 2, Decimal("-115.0"), Decimal("-60.1"), "Low"),
    ("MATH", "HS", "status", 1, None, Decimal("-115.1"), "Very Low"),
    (
        "SCIENCE",
        "ALL",
        "change",
        5,
        Decimal("5.0"),
        None,
        "Increased Significantly from Prior Year",
    ),
    (
        "SCIENCE",
        "ALL",
        "change",
        4,
        Decimal("2.0"),
        Decimal("4.9"),
        "Increased from Prior Year",
    ),
    (
        "SCIENCE",
        "ALL",
        "change",
        3,
        Decimal("-1.9"),
        Decimal("1.9"),
        "Maintained from Prior Year",
    ),
    (
        "SCIENCE",
        "ALL",
        "change",
        2,
        Decimal("-5.0"),
        Decimal("-2.0"),
        "Declined from Prior Year",
    ),
    (
        "SCIENCE",
        "ALL",
        "change",
        1,
        None,
        Decimal("-5.1"),
        "Declined Significantly from Prior Year",
    ),
    ("SCIENCE", "ALL", "status", 5, Decimal("65.0"), None, "Very High"),
    ("SCIENCE", "ALL", "status", 4, Decimal("55.0"), Decimal("64.9"), "High"),
    ("SCIENCE", "ALL", "status", 3, Decimal("45.0"), Decimal("54.9"), "Medium"),
    ("SCIENCE", "ALL", "status", 2, Decimal("35.0"), Decimal("44.9"), "Low"),
    ("SCIENCE", "ALL", "status", 1, None, Decimal("34.9"), "Very Low"),
    (
        "SUSP",
        "ED",
        "change",
        5,
        None,
        Decimal("-2.0"),
        "Declined Significantly from Prior Year",
    ),
    (
        "SUSP",
        "ED",
        "change",
        4,
        Decimal("-1.9"),
        Decimal("-0.3"),
        "Declined from Prior Year",
    ),
    (
        "SUSP",
        "ED",
        "change",
        3,
        Decimal("-0.2"),
        Decimal("0.2"),
        "Maintained from Prior Year",
    ),
    (
        "SUSP",
        "ED",
        "change",
        2,
        Decimal("0.3"),
        Decimal("2.0"),
        "Increased from Prior Year",
    ),
    (
        "SUSP",
        "ED",
        "change",
        1,
        Decimal("2.1"),
        None,
        "Increased Significantly from Prior Year",
    ),
    ("SUSP", "ED", "status", 5, None, Decimal("0.5"), "Very Low"),
    ("SUSP", "ED", "status", 4, Decimal("0.6"), Decimal("1.5"), "Low"),
    ("SUSP", "ED", "status", 3, Decimal("1.6"), Decimal("3.0"), "Medium"),
    ("SUSP", "ED", "status", 2, Decimal("3.1"), Decimal("6.0"), "High"),
    ("SUSP", "ED", "status", 1, Decimal("6.1"), None, "Very High"),
    (
        "SUSP",
        "ES",
        "change",
        5,
        None,
        Decimal("-1.0"),
        "Declined Significantly from Prior Year",
    ),
    (
        "SUSP",
        "ES",
        "change",
        4,
        Decimal("-0.9"),
        Decimal("-0.3"),
        "Declined from Prior Year",
    ),
    (
        "SUSP",
        "ES",
        "change",
        3,
        Decimal("-0.2"),
        Decimal("0.2"),
        "Maintained from Prior Year",
    ),
    (
        "SUSP",
        "ES",
        "change",
        2,
        Decimal("0.3"),
        Decimal("2.0"),
        "Increased from Prior Year",
    ),
    (
        "SUSP",
        "ES",
        "change",
        1,
        Decimal("2.1"),
        None,
        "Increased Significantly from Prior Year",
    ),
    ("SUSP", "ES", "status", 5, None, Decimal("0.5"), "Very Low"),
    ("SUSP", "ES", "status", 4, Decimal("0.6"), Decimal("1.0"), "Low"),
    ("SUSP", "ES", "status", 3, Decimal("1.1"), Decimal("3.0"), "Medium"),
    ("SUSP", "ES", "status", 2, Decimal("3.1"), Decimal("6.0"), "High"),
    ("SUSP", "ES", "status", 1, Decimal("6.1"), None, "Very High"),
    (
        "SUSP",
        "HD",
        "change",
        5,
        None,
        Decimal("-3.0"),
        "Declined Significantly from Prior Year",
    ),
    (
        "SUSP",
        "HD",
        "change",
        4,
        Decimal("-2.9"),
        Decimal("-0.5"),
        "Declined from Prior Year",
    ),
    (
        "SUSP",
        "HD",
        "change",
        3,
        Decimal("-0.4"),
        Decimal("0.4"),
        "Maintained from Prior Year",
    ),
    (
        "SUSP",
        "HD",
        "change",
        2,
        Decimal("0.5"),
        Decimal("3.0"),
        "Increased from Prior Year",
    ),
    (
        "SUSP",
        "HD",
        "change",
        1,
        Decimal("3.1"),
        None,
        "Increased Significantly from Prior Year",
    ),
    ("SUSP", "HD", "status", 5, None, Decimal("1.5"), "Very Low"),
    ("SUSP", "HD", "status", 4, Decimal("1.6"), Decimal("3.5"), "Low"),
    ("SUSP", "HD", "status", 3, Decimal("3.6"), Decimal("6.0"), "Medium"),
    ("SUSP", "HD", "status", 2, Decimal("6.1"), Decimal("9.0"), "High"),
    ("SUSP", "HD", "status", 1, Decimal("9.1"), None, "Very High"),
    (
        "SUSP",
        "HS",
        "change",
        5,
        None,
        Decimal("-2.0"),
        "Declined Significantly from Prior Year",
    ),
    (
        "SUSP",
        "HS",
        "change",
        4,
        Decimal("-1.9"),
        Decimal("-0.3"),
        "Declined from Prior Year",
    ),
    (
        "SUSP",
        "HS",
        "change",
        3,
        Decimal("-0.2"),
        Decimal("0.2"),
        "Maintained from Prior Year",
    ),
    (
        "SUSP",
        "HS",
        "change",
        2,
        Decimal("0.3"),
        Decimal("3.0"),
        "Increased from Prior Year",
    ),
    (
        "SUSP",
        "HS",
        "change",
        1,
        Decimal("3.1"),
        None,
        "Increased Significantly from Prior Year",
    ),
    ("SUSP", "HS", "status", 5, None, Decimal("0.5"), "Very Low"),
    ("SUSP", "HS", "status", 4, Decimal("0.6"), Decimal("1.5"), "Low"),
    ("SUSP", "HS", "status", 3, Decimal("1.6"), Decimal("6.0"), "Medium"),
    ("SUSP", "HS", "status", 2, Decimal("6.1"), Decimal("10.0"), "High"),
    ("SUSP", "HS", "status", 1, Decimal("10.1"), None, "Very High"),
    (
        "SUSP",
        "MS",
        "change",
        5,
        None,
        Decimal("-3.0"),
        "Declined Significantly from Prior Year",
    ),
    (
        "SUSP",
        "MS",
        "change",
        4,
        Decimal("-2.9"),
        Decimal("-0.3"),
        "Declined from Prior Year",
    ),
    (
        "SUSP",
        "MS",
        "change",
        3,
        Decimal("-0.2"),
        Decimal("0.2"),
        "Maintained from Prior Year",
    ),
    (
        "SUSP",
        "MS",
        "change",
        2,
        Decimal("0.3"),
        Decimal("4.0"),
        "Increased from Prior Year",
    ),
    (
        "SUSP",
        "MS",
        "change",
        1,
        Decimal("4.1"),
        None,
        "Increased Significantly from Prior Year",
    ),
    ("SUSP", "MS", "status", 5, None, Decimal("0.5"), "Very Low"),
    ("SUSP", "MS", "status", 4, Decimal("0.6"), Decimal("2.0"), "Low"),
    ("SUSP", "MS", "status", 3, Decimal("2.1"), Decimal("8.0"), "Medium"),
    ("SUSP", "MS", "status", 2, Decimal("8.1"), Decimal("12.0"), "High"),
    ("SUSP", "MS", "status", 1, Decimal("12.1"), None, "Very High"),
    (
        "SUSP",
        "UD",
        "change",
        5,
        None,
        Decimal("-2.0"),
        "Declined Significantly from Prior Year",
    ),
    (
        "SUSP",
        "UD",
        "change",
        4,
        Decimal("-1.9"),
        Decimal("-0.3"),
        "Declined from Prior Year",
    ),
    (
        "SUSP",
        "UD",
        "change",
        3,
        Decimal("-0.2"),
        Decimal("0.2"),
        "Maintained from Prior Year",
    ),
    (
        "SUSP",
        "UD",
        "change",
        2,
        Decimal("0.3"),
        Decimal("2.0"),
        "Increased from Prior Year",
    ),
    (
        "SUSP",
        "UD",
        "change",
        1,
        Decimal("2.1"),
        None,
        "Increased Significantly from Prior Year",
    ),
    ("SUSP", "UD", "status", 5, None, Decimal("1.0"), "Very Low"),
    ("SUSP", "UD", "status", 4, Decimal("1.1"), Decimal("2.5"), "Low"),
    ("SUSP", "UD", "status", 3, Decimal("2.6"), Decimal("4.5"), "Medium"),
    ("SUSP", "UD", "status", 2, Decimal("4.6"), Decimal("8.0"), "High"),
    ("SUSP", "UD", "status", 1, Decimal("8.1"), None, "Very High"),
)

_COLOR_CELLS: tuple[_ColorCell, ...] = (
    ("CCI", "ALL", False, 5, 5, 5),
    ("CCI", "ALL", False, 5, 4, 5),
    ("CCI", "ALL", False, 5, 3, 5),
    ("CCI", "ALL", False, 5, 2, 4),
    ("CCI", "ALL", False, 5, 1, 3),
    ("CCI", "ALL", False, 4, 5, 5),
    ("CCI", "ALL", False, 4, 4, 4),
    ("CCI", "ALL", False, 4, 3, 4),
    ("CCI", "ALL", False, 4, 2, 3),
    ("CCI", "ALL", False, 4, 1, 2),
    ("CCI", "ALL", False, 3, 5, 4),
    ("CCI", "ALL", False, 3, 4, 4),
    ("CCI", "ALL", False, 3, 3, 3),
    ("CCI", "ALL", False, 3, 2, 2),
    ("CCI", "ALL", False, 3, 1, 2),
    ("CCI", "ALL", False, 2, 5, 3),
    ("CCI", "ALL", False, 2, 4, 3),
    ("CCI", "ALL", False, 2, 3, 2),
    ("CCI", "ALL", False, 2, 2, 2),
    ("CCI", "ALL", False, 2, 1, 1),
    ("CCI", "ALL", False, 1, 5, 3),
    ("CCI", "ALL", False, 1, 4, 2),
    ("CCI", "ALL", False, 1, 3, 1),
    ("CCI", "ALL", False, 1, 2, 1),
    ("CCI", "ALL", False, 1, 1, 1),
    ("CCI", "ALL", True, 5, 4, 5),
    ("CCI", "ALL", True, 5, 3, 5),
    ("CCI", "ALL", True, 5, 2, 4),
    ("CCI", "ALL", True, 4, 4, 4),
    ("CCI", "ALL", True, 4, 3, 4),
    ("CCI", "ALL", True, 4, 2, 3),
    ("CCI", "ALL", True, 3, 4, 4),
    ("CCI", "ALL", True, 3, 3, 3),
    ("CCI", "ALL", True, 3, 2, 2),
    ("CCI", "ALL", True, 2, 4, 3),
    ("CCI", "ALL", True, 2, 3, 2),
    ("CCI", "ALL", True, 2, 2, 2),
    ("CCI", "ALL", True, 1, 4, 2),
    ("CCI", "ALL", True, 1, 3, 1),
    ("CCI", "ALL", True, 1, 2, 1),
    ("CHRO", "ALL", False, 5, 5, 5),
    ("CHRO", "ALL", False, 5, 4, 5),
    ("CHRO", "ALL", False, 5, 3, 5),
    ("CHRO", "ALL", False, 5, 2, 4),
    ("CHRO", "ALL", False, 5, 1, 3),
    ("CHRO", "ALL", False, 4, 5, 5),
    ("CHRO", "ALL", False, 4, 4, 4),
    ("CHRO", "ALL", False, 4, 3, 4),
    ("CHRO", "ALL", False, 4, 2, 3),
    ("CHRO", "ALL", False, 4, 1, 2),
    ("CHRO", "ALL", False, 3, 5, 4),
    ("CHRO", "ALL", False, 3, 4, 4),
    ("CHRO", "ALL", False, 3, 3, 3),
    ("CHRO", "ALL", False, 3, 2, 2),
    ("CHRO", "ALL", False, 3, 1, 2),
    ("CHRO", "ALL", False, 2, 5, 3),
    ("CHRO", "ALL", False, 2, 4, 3),
    ("CHRO", "ALL", False, 2, 3, 2),
    ("CHRO", "ALL", False, 2, 2, 2),
    ("CHRO", "ALL", False, 2, 1, 1),
    ("CHRO", "ALL", False, 1, 5, 3),
    ("CHRO", "ALL", False, 1, 4, 2),
    ("CHRO", "ALL", False, 1, 3, 1),
    ("CHRO", "ALL", False, 1, 2, 1),
    ("CHRO", "ALL", False, 1, 1, 1),
    ("CHRO", "ALL", True, 5, 4, 5),
    ("CHRO", "ALL", True, 5, 3, 5),
    ("CHRO", "ALL", True, 5, 2, 4),
    ("CHRO", "ALL", True, 4, 4, 4),
    ("CHRO", "ALL", True, 4, 3, 4),
    ("CHRO", "ALL", True, 4, 2, 3),
    ("CHRO", "ALL", True, 3, 4, 4),
    ("CHRO", "ALL", True, 3, 3, 3),
    ("CHRO", "ALL", True, 3, 2, 2),
    ("CHRO", "ALL", True, 2, 4, 3),
    ("CHRO", "ALL", True, 2, 3, 2),
    ("CHRO", "ALL", True, 2, 2, 2),
    ("CHRO", "ALL", True, 1, 4, 2),
    ("CHRO", "ALL", True, 1, 3, 1),
    ("CHRO", "ALL", True, 1, 2, 1),
    ("ELA", "ALL", False, 5, 5, 5),
    ("ELA", "ALL", False, 5, 4, 5),
    ("ELA", "ALL", False, 5, 3, 5),
    ("ELA", "ALL", False, 5, 2, 4),
    ("ELA", "ALL", False, 5, 1, 4),
    ("ELA", "ALL", False, 4, 5, 5),
    ("ELA", "ALL", False, 4, 4, 4),
    ("ELA", "ALL", False, 4, 3, 4),
    ("ELA", "ALL", False, 4, 2, 4),
    ("ELA", "ALL", False, 4, 1, 4),
    ("ELA", "ALL", False, 3, 5, 4),
    ("ELA", "ALL", False, 3, 4, 4),
    ("ELA", "ALL", False, 3, 3, 3),
    ("ELA", "ALL", False, 3, 2, 3),
    ("ELA", "ALL", False, 3, 1, 3),
    ("ELA", "ALL", False, 2, 5, 3),
    ("ELA", "ALL", False, 2, 4, 3),
    ("ELA", "ALL", False, 2, 3, 2),
    ("ELA", "ALL", False, 2, 2, 2),
    ("ELA", "ALL", False, 2, 1, 2),
    ("ELA", "ALL", False, 1, 5, 2),
    ("ELA", "ALL", False, 1, 4, 2),
    ("ELA", "ALL", False, 1, 3, 1),
    ("ELA", "ALL", False, 1, 2, 1),
    ("ELA", "ALL", False, 1, 1, 1),
    ("ELA", "HS", False, 5, 5, 5),
    ("ELA", "HS", False, 5, 4, 5),
    ("ELA", "HS", False, 5, 3, 5),
    ("ELA", "HS", False, 5, 2, 4),
    ("ELA", "HS", False, 5, 1, 4),
    ("ELA", "HS", False, 4, 5, 5),
    ("ELA", "HS", False, 4, 4, 4),
    ("ELA", "HS", False, 4, 3, 4),
    ("ELA", "HS", False, 4, 2, 4),
    ("ELA", "HS", False, 4, 1, 4),
    ("ELA", "HS", False, 3, 5, 4),
    ("ELA", "HS", False, 3, 4, 4),
    ("ELA", "HS", False, 3, 3, 3),
    ("ELA", "HS", False, 3, 2, 3),
    ("ELA", "HS", False, 3, 1, 3),
    ("ELA", "HS", False, 2, 5, 3),
    ("ELA", "HS", False, 2, 4, 3),
    ("ELA", "HS", False, 2, 3, 2),
    ("ELA", "HS", False, 2, 2, 2),
    ("ELA", "HS", False, 2, 1, 2),
    ("ELA", "HS", False, 1, 5, 2),
    ("ELA", "HS", False, 1, 4, 2),
    ("ELA", "HS", False, 1, 3, 1),
    ("ELA", "HS", False, 1, 2, 1),
    ("ELA", "HS", False, 1, 1, 1),
    ("ELPI", "ALL", False, 5, 5, 5),
    ("ELPI", "ALL", False, 5, 4, 5),
    ("ELPI", "ALL", False, 5, 3, 5),
    ("ELPI", "ALL", False, 5, 2, 4),
    ("ELPI", "ALL", False, 5, 1, 3),
    ("ELPI", "ALL", False, 4, 5, 5),
    ("ELPI", "ALL", False, 4, 4, 4),
    ("ELPI", "ALL", False, 4, 3, 4),
    ("ELPI", "ALL", False, 4, 2, 3),
    ("ELPI", "ALL", False, 4, 1, 2),
    ("ELPI", "ALL", False, 3, 5, 4),
    ("ELPI", "ALL", False, 3, 4, 4),
    ("ELPI", "ALL", False, 3, 3, 3),
    ("ELPI", "ALL", False, 3, 2, 2),
    ("ELPI", "ALL", False, 3, 1, 2),
    ("ELPI", "ALL", False, 2, 5, 3),
    ("ELPI", "ALL", False, 2, 4, 3),
    ("ELPI", "ALL", False, 2, 3, 2),
    ("ELPI", "ALL", False, 2, 2, 2),
    ("ELPI", "ALL", False, 2, 1, 1),
    ("ELPI", "ALL", False, 1, 5, 3),
    ("ELPI", "ALL", False, 1, 4, 2),
    ("ELPI", "ALL", False, 1, 3, 1),
    ("ELPI", "ALL", False, 1, 2, 1),
    ("ELPI", "ALL", False, 1, 1, 1),
    ("GRAD", "ALL", False, 5, 5, 5),
    ("GRAD", "ALL", False, 5, 4, 5),
    ("GRAD", "ALL", False, 5, 3, 5),
    ("GRAD", "ALL", False, 5, 2, 5),
    ("GRAD", "ALL", False, 5, 1, None),
    ("GRAD", "ALL", False, 4, 5, 5),
    ("GRAD", "ALL", False, 4, 4, 4),
    ("GRAD", "ALL", False, 4, 3, 4),
    ("GRAD", "ALL", False, 4, 2, 3),
    ("GRAD", "ALL", False, 4, 1, 2),
    ("GRAD", "ALL", False, 3, 5, 4),
    ("GRAD", "ALL", False, 3, 4, 4),
    ("GRAD", "ALL", False, 3, 3, 3),
    ("GRAD", "ALL", False, 3, 2, 2),
    ("GRAD", "ALL", False, 3, 1, 2),
    ("GRAD", "ALL", False, 2, 5, 3),
    ("GRAD", "ALL", False, 2, 4, 3),
    ("GRAD", "ALL", False, 2, 3, 2),
    ("GRAD", "ALL", False, 2, 2, 2),
    ("GRAD", "ALL", False, 2, 1, 1),
    ("GRAD", "ALL", False, 1, 5, 1),
    ("GRAD", "ALL", False, 1, 4, 1),
    ("GRAD", "ALL", False, 1, 3, 1),
    ("GRAD", "ALL", False, 1, 2, 1),
    ("GRAD", "ALL", False, 1, 1, 1),
    ("GRAD", "ALL", True, 5, 5, 5),
    ("GRAD", "ALL", True, 5, 4, 5),
    ("GRAD", "ALL", True, 5, 3, 5),
    ("GRAD", "ALL", True, 5, 2, 5),
    ("GRAD", "ALL", True, 4, 5, 4),
    ("GRAD", "ALL", True, 4, 4, 4),
    ("GRAD", "ALL", True, 4, 3, 4),
    ("GRAD", "ALL", True, 4, 2, 3),
    ("GRAD", "ALL", True, 4, 1, 3),
    ("GRAD", "ALL", True, 3, 5, 4),
    ("GRAD", "ALL", True, 3, 4, 4),
    ("GRAD", "ALL", True, 3, 3, 3),
    ("GRAD", "ALL", True, 3, 2, 2),
    ("GRAD", "ALL", True, 3, 1, 2),
    ("GRAD", "ALL", True, 2, 5, 3),
    ("GRAD", "ALL", True, 2, 4, 3),
    ("GRAD", "ALL", True, 2, 3, 2),
    ("GRAD", "ALL", True, 2, 2, 2),
    ("GRAD", "ALL", True, 2, 1, 2),
    ("GRAD", "ALL", True, 1, 5, 1),
    ("GRAD", "ALL", True, 1, 4, 1),
    ("GRAD", "ALL", True, 1, 3, 1),
    ("GRAD", "ALL", True, 1, 2, 1),
    ("GRAD", "ALL", True, 1, 1, 1),
    ("MATH", "ALL", False, 5, 5, 5),
    ("MATH", "ALL", False, 5, 4, 5),
    ("MATH", "ALL", False, 5, 3, 5),
    ("MATH", "ALL", False, 5, 2, 4),
    ("MATH", "ALL", False, 5, 1, 4),
    ("MATH", "ALL", False, 4, 5, 5),
    ("MATH", "ALL", False, 4, 4, 4),
    ("MATH", "ALL", False, 4, 3, 4),
    ("MATH", "ALL", False, 4, 2, 4),
    ("MATH", "ALL", False, 4, 1, 4),
    ("MATH", "ALL", False, 3, 5, 4),
    ("MATH", "ALL", False, 3, 4, 4),
    ("MATH", "ALL", False, 3, 3, 3),
    ("MATH", "ALL", False, 3, 2, 3),
    ("MATH", "ALL", False, 3, 1, 3),
    ("MATH", "ALL", False, 2, 5, 3),
    ("MATH", "ALL", False, 2, 4, 3),
    ("MATH", "ALL", False, 2, 3, 2),
    ("MATH", "ALL", False, 2, 2, 2),
    ("MATH", "ALL", False, 2, 1, 2),
    ("MATH", "ALL", False, 1, 5, 2),
    ("MATH", "ALL", False, 1, 4, 2),
    ("MATH", "ALL", False, 1, 3, 1),
    ("MATH", "ALL", False, 1, 2, 1),
    ("MATH", "ALL", False, 1, 1, 1),
    ("MATH", "HS", False, 5, 5, 5),
    ("MATH", "HS", False, 5, 4, 5),
    ("MATH", "HS", False, 5, 3, 5),
    ("MATH", "HS", False, 5, 2, 4),
    ("MATH", "HS", False, 5, 1, 4),
    ("MATH", "HS", False, 4, 5, 5),
    ("MATH", "HS", False, 4, 4, 4),
    ("MATH", "HS", False, 4, 3, 4),
    ("MATH", "HS", False, 4, 2, 4),
    ("MATH", "HS", False, 4, 1, 4),
    ("MATH", "HS", False, 3, 5, 4),
    ("MATH", "HS", False, 3, 4, 4),
    ("MATH", "HS", False, 3, 3, 3),
    ("MATH", "HS", False, 3, 2, 3),
    ("MATH", "HS", False, 3, 1, 3),
    ("MATH", "HS", False, 2, 5, 3),
    ("MATH", "HS", False, 2, 4, 3),
    ("MATH", "HS", False, 2, 3, 2),
    ("MATH", "HS", False, 2, 2, 2),
    ("MATH", "HS", False, 2, 1, 2),
    ("MATH", "HS", False, 1, 5, 2),
    ("MATH", "HS", False, 1, 4, 2),
    ("MATH", "HS", False, 1, 3, 1),
    ("MATH", "HS", False, 1, 2, 1),
    ("MATH", "HS", False, 1, 1, 1),
    ("SCIENCE", "ALL", False, 5, 5, 5),
    ("SCIENCE", "ALL", False, 5, 4, 5),
    ("SCIENCE", "ALL", False, 5, 3, 5),
    ("SCIENCE", "ALL", False, 5, 2, 4),
    ("SCIENCE", "ALL", False, 5, 1, 4),
    ("SCIENCE", "ALL", False, 4, 5, 5),
    ("SCIENCE", "ALL", False, 4, 4, 4),
    ("SCIENCE", "ALL", False, 4, 3, 4),
    ("SCIENCE", "ALL", False, 4, 2, 4),
    ("SCIENCE", "ALL", False, 4, 1, 4),
    ("SCIENCE", "ALL", False, 3, 5, 4),
    ("SCIENCE", "ALL", False, 3, 4, 4),
    ("SCIENCE", "ALL", False, 3, 3, 3),
    ("SCIENCE", "ALL", False, 3, 2, 3),
    ("SCIENCE", "ALL", False, 3, 1, 3),
    ("SCIENCE", "ALL", False, 2, 5, 3),
    ("SCIENCE", "ALL", False, 2, 4, 3),
    ("SCIENCE", "ALL", False, 2, 3, 2),
    ("SCIENCE", "ALL", False, 2, 2, 2),
    ("SCIENCE", "ALL", False, 2, 1, 2),
    ("SCIENCE", "ALL", False, 1, 5, 2),
    ("SCIENCE", "ALL", False, 1, 4, 2),
    ("SCIENCE", "ALL", False, 1, 3, 1),
    ("SCIENCE", "ALL", False, 1, 2, 1),
    ("SCIENCE", "ALL", False, 1, 1, 1),
    ("SUSP", "ED", False, 5, 5, 5),
    ("SUSP", "ED", False, 5, 4, 5),
    ("SUSP", "ED", False, 5, 3, 5),
    ("SUSP", "ED", False, 5, 2, 4),
    ("SUSP", "ED", False, 5, 1, None),
    ("SUSP", "ED", False, 4, 5, 5),
    ("SUSP", "ED", False, 4, 4, 4),
    ("SUSP", "ED", False, 4, 3, 4),
    ("SUSP", "ED", False, 4, 2, 3),
    ("SUSP", "ED", False, 4, 1, None),
    ("SUSP", "ED", False, 3, 5, 4),
    ("SUSP", "ED", False, 3, 4, 4),
    ("SUSP", "ED", False, 3, 3, 3),
    ("SUSP", "ED", False, 3, 2, 2),
    ("SUSP", "ED", False, 3, 1, 2),
    ("SUSP", "ED", False, 2, 5, 3),
    ("SUSP", "ED", False, 2, 4, 3),
    ("SUSP", "ED", False, 2, 3, 2),
    ("SUSP", "ED", False, 2, 2, 2),
    ("SUSP", "ED", False, 2, 1, 1),
    ("SUSP", "ED", False, 1, 5, 3),
    ("SUSP", "ED", False, 1, 4, 2),
    ("SUSP", "ED", False, 1, 3, 1),
    ("SUSP", "ED", False, 1, 2, 1),
    ("SUSP", "ED", False, 1, 1, 1),
    ("SUSP", "ED", True, 5, 4, 5),
    ("SUSP", "ED", True, 5, 3, 5),
    ("SUSP", "ED", True, 4, 4, 4),
    ("SUSP", "ED", True, 4, 3, 4),
    ("SUSP", "ED", True, 4, 2, 3),
    ("SUSP", "ED", True, 3, 4, 4),
    ("SUSP", "ED", True, 3, 3, 3),
    ("SUSP", "ED", True, 3, 2, 2),
    ("SUSP", "ED", True, 2, 4, 3),
    ("SUSP", "ED", True, 2, 3, 2),
    ("SUSP", "ED", True, 2, 2, 2),
    ("SUSP", "ED", True, 1, 4, 2),
    ("SUSP", "ED", True, 1, 3, 1),
    ("SUSP", "ED", True, 1, 2, 1),
    ("SUSP", "ES", False, 5, 5, 5),
    ("SUSP", "ES", False, 5, 4, 5),
    ("SUSP", "ES", False, 5, 3, 5),
    ("SUSP", "ES", False, 5, 2, 4),
    ("SUSP", "ES", False, 5, 1, None),
    ("SUSP", "ES", False, 4, 5, 5),
    ("SUSP", "ES", False, 4, 4, 4),
    ("SUSP", "ES", False, 4, 3, 4),
    ("SUSP", "ES", False, 4, 2, 3),
    ("SUSP", "ES", False, 4, 1, None),
    ("SUSP", "ES", False, 3, 5, 4),
    ("SUSP", "ES", False, 3, 4, 4),
    ("SUSP", "ES", False, 3, 3, 3),
    ("SUSP", "ES", False, 3, 2, 2),
    ("SUSP", "ES", False, 3, 1, 2),
    ("SUSP", "ES", False, 2, 5, 3),
    ("SUSP", "ES", False, 2, 4, 3),
    ("SUSP", "ES", False, 2, 3, 2),
    ("SUSP", "ES", False, 2, 2, 2),
    ("SUSP", "ES", False, 2, 1, 1),
    ("SUSP", "ES", False, 1, 5, 3),
    ("SUSP", "ES", False, 1, 4, 2),
    ("SUSP", "ES", False, 1, 3, 1),
    ("SUSP", "ES", False, 1, 2, 1),
    ("SUSP", "ES", False, 1, 1, 1),
    ("SUSP", "ES", True, 5, 4, 5),
    ("SUSP", "ES", True, 5, 3, 5),
    ("SUSP", "ES", True, 4, 4, 4),
    ("SUSP", "ES", True, 4, 3, 4),
    ("SUSP", "ES", True, 4, 2, 3),
    ("SUSP", "ES", True, 3, 4, 4),
    ("SUSP", "ES", True, 3, 3, 3),
    ("SUSP", "ES", True, 3, 2, 2),
    ("SUSP", "ES", True, 2, 4, 3),
    ("SUSP", "ES", True, 2, 3, 2),
    ("SUSP", "ES", True, 2, 2, 2),
    ("SUSP", "ES", True, 1, 4, 2),
    ("SUSP", "ES", True, 1, 3, 1),
    ("SUSP", "ES", True, 1, 2, 1),
    ("SUSP", "HD", False, 5, 5, 5),
    ("SUSP", "HD", False, 5, 4, 5),
    ("SUSP", "HD", False, 5, 3, 5),
    ("SUSP", "HD", False, 5, 2, 4),
    ("SUSP", "HD", False, 5, 1, None),
    ("SUSP", "HD", False, 4, 5, 5),
    ("SUSP", "HD", False, 4, 4, 4),
    ("SUSP", "HD", False, 4, 3, 4),
    ("SUSP", "HD", False, 4, 2, 3),
    ("SUSP", "HD", False, 4, 1, 2),
    ("SUSP", "HD", False, 3, 5, 4),
    ("SUSP", "HD", False, 3, 4, 4),
    ("SUSP", "HD", False, 3, 3, 3),
    ("SUSP", "HD", False, 3, 2, 2),
    ("SUSP", "HD", False, 3, 1, 2),
    ("SUSP", "HD", False, 2, 5, 3),
    ("SUSP", "HD", False, 2, 4, 3),
    ("SUSP", "HD", False, 2, 3, 2),
    ("SUSP", "HD", False, 2, 2, 2),
    ("SUSP", "HD", False, 2, 1, 1),
    ("SUSP", "HD", False, 1, 5, 3),
    ("SUSP", "HD", False, 1, 4, 2),
    ("SUSP", "HD", False, 1, 3, 1),
    ("SUSP", "HD", False, 1, 2, 1),
    ("SUSP", "HD", False, 1, 1, 1),
    ("SUSP", "HD", True, 5, 4, 5),
    ("SUSP", "HD", True, 5, 3, 5),
    ("SUSP", "HD", True, 5, 2, 4),
    ("SUSP", "HD", True, 4, 4, 4),
    ("SUSP", "HD", True, 4, 3, 4),
    ("SUSP", "HD", True, 4, 2, 3),
    ("SUSP", "HD", True, 3, 4, 4),
    ("SUSP", "HD", True, 3, 3, 3),
    ("SUSP", "HD", True, 3, 2, 2),
    ("SUSP", "HD", True, 2, 4, 3),
    ("SUSP", "HD", True, 2, 3, 2),
    ("SUSP", "HD", True, 2, 2, 2),
    ("SUSP", "HD", True, 1, 4, 2),
    ("SUSP", "HD", True, 1, 3, 1),
    ("SUSP", "HD", True, 1, 2, 1),
    ("SUSP", "HS", False, 5, 5, 5),
    ("SUSP", "HS", False, 5, 4, 5),
    ("SUSP", "HS", False, 5, 3, 5),
    ("SUSP", "HS", False, 5, 2, 4),
    ("SUSP", "HS", False, 5, 1, None),
    ("SUSP", "HS", False, 4, 5, 5),
    ("SUSP", "HS", False, 4, 4, 4),
    ("SUSP", "HS", False, 4, 3, 4),
    ("SUSP", "HS", False, 4, 2, 3),
    ("SUSP", "HS", False, 4, 1, None),
    ("SUSP", "HS", False, 3, 5, 4),
    ("SUSP", "HS", False, 3, 4, 4),
    ("SUSP", "HS", False, 3, 3, 3),
    ("SUSP", "HS", False, 3, 2, 2),
    ("SUSP", "HS", False, 3, 1, 2),
    ("SUSP", "HS", False, 2, 5, 3),
    ("SUSP", "HS", False, 2, 4, 3),
    ("SUSP", "HS", False, 2, 3, 2),
    ("SUSP", "HS", False, 2, 2, 2),
    ("SUSP", "HS", False, 2, 1, 1),
    ("SUSP", "HS", False, 1, 5, 3),
    ("SUSP", "HS", False, 1, 4, 2),
    ("SUSP", "HS", False, 1, 3, 1),
    ("SUSP", "HS", False, 1, 2, 1),
    ("SUSP", "HS", False, 1, 1, 1),
    ("SUSP", "HS", True, 5, 4, 5),
    ("SUSP", "HS", True, 5, 3, 5),
    ("SUSP", "HS", True, 4, 4, 4),
    ("SUSP", "HS", True, 4, 3, 4),
    ("SUSP", "HS", True, 4, 2, 3),
    ("SUSP", "HS", True, 3, 4, 4),
    ("SUSP", "HS", True, 3, 3, 3),
    ("SUSP", "HS", True, 3, 2, 2),
    ("SUSP", "HS", True, 2, 4, 3),
    ("SUSP", "HS", True, 2, 3, 2),
    ("SUSP", "HS", True, 2, 2, 2),
    ("SUSP", "HS", True, 1, 4, 2),
    ("SUSP", "HS", True, 1, 3, 1),
    ("SUSP", "HS", True, 1, 2, 1),
    ("SUSP", "MS", False, 5, 5, 5),
    ("SUSP", "MS", False, 5, 4, 5),
    ("SUSP", "MS", False, 5, 3, 5),
    ("SUSP", "MS", False, 5, 2, 4),
    ("SUSP", "MS", False, 5, 1, None),
    ("SUSP", "MS", False, 4, 5, 5),
    ("SUSP", "MS", False, 4, 4, 4),
    ("SUSP", "MS", False, 4, 3, 4),
    ("SUSP", "MS", False, 4, 2, 3),
    ("SUSP", "MS", False, 4, 1, None),
    ("SUSP", "MS", False, 3, 5, 4),
    ("SUSP", "MS", False, 3, 4, 4),
    ("SUSP", "MS", False, 3, 3, 3),
    ("SUSP", "MS", False, 3, 2, 2),
    ("SUSP", "MS", False, 3, 1, 2),
    ("SUSP", "MS", False, 2, 5, 3),
    ("SUSP", "MS", False, 2, 4, 3),
    ("SUSP", "MS", False, 2, 3, 2),
    ("SUSP", "MS", False, 2, 2, 2),
    ("SUSP", "MS", False, 2, 1, 1),
    ("SUSP", "MS", False, 1, 5, 3),
    ("SUSP", "MS", False, 1, 4, 2),
    ("SUSP", "MS", False, 1, 3, 1),
    ("SUSP", "MS", False, 1, 2, 1),
    ("SUSP", "MS", False, 1, 1, 1),
    ("SUSP", "MS", True, 5, 4, 5),
    ("SUSP", "MS", True, 5, 3, 5),
    ("SUSP", "MS", True, 4, 4, 4),
    ("SUSP", "MS", True, 4, 3, 4),
    ("SUSP", "MS", True, 4, 2, 3),
    ("SUSP", "MS", True, 3, 4, 4),
    ("SUSP", "MS", True, 3, 3, 3),
    ("SUSP", "MS", True, 3, 2, 2),
    ("SUSP", "MS", True, 2, 4, 3),
    ("SUSP", "MS", True, 2, 3, 2),
    ("SUSP", "MS", True, 2, 2, 2),
    ("SUSP", "MS", True, 1, 4, 2),
    ("SUSP", "MS", True, 1, 3, 1),
    ("SUSP", "MS", True, 1, 2, 1),
    ("SUSP", "UD", False, 5, 5, 5),
    ("SUSP", "UD", False, 5, 4, 5),
    ("SUSP", "UD", False, 5, 3, 5),
    ("SUSP", "UD", False, 5, 2, 4),
    ("SUSP", "UD", False, 5, 1, None),
    ("SUSP", "UD", False, 4, 5, 5),
    ("SUSP", "UD", False, 4, 4, 4),
    ("SUSP", "UD", False, 4, 3, 4),
    ("SUSP", "UD", False, 4, 2, 3),
    ("SUSP", "UD", False, 4, 1, 2),
    ("SUSP", "UD", False, 3, 5, 4),
    ("SUSP", "UD", False, 3, 4, 4),
    ("SUSP", "UD", False, 3, 3, 3),
    ("SUSP", "UD", False, 3, 2, 2),
    ("SUSP", "UD", False, 3, 1, 2),
    ("SUSP", "UD", False, 2, 5, 3),
    ("SUSP", "UD", False, 2, 4, 3),
    ("SUSP", "UD", False, 2, 3, 2),
    ("SUSP", "UD", False, 2, 2, 2),
    ("SUSP", "UD", False, 2, 1, 1),
    ("SUSP", "UD", False, 1, 5, 3),
    ("SUSP", "UD", False, 1, 4, 2),
    ("SUSP", "UD", False, 1, 3, 1),
    ("SUSP", "UD", False, 1, 2, 1),
    ("SUSP", "UD", False, 1, 1, 1),
    ("SUSP", "UD", True, 5, 4, 5),
    ("SUSP", "UD", True, 5, 3, 5),
    ("SUSP", "UD", True, 5, 2, 4),
    ("SUSP", "UD", True, 4, 4, 4),
    ("SUSP", "UD", True, 4, 3, 4),
    ("SUSP", "UD", True, 4, 2, 3),
    ("SUSP", "UD", True, 3, 4, 4),
    ("SUSP", "UD", True, 3, 3, 3),
    ("SUSP", "UD", True, 3, 2, 2),
    ("SUSP", "UD", True, 2, 4, 3),
    ("SUSP", "UD", True, 2, 3, 2),
    ("SUSP", "UD", True, 2, 2, 2),
    ("SUSP", "UD", True, 1, 4, 2),
    ("SUSP", "UD", True, 1, 3, 1),
    ("SUSP", "UD", True, 1, 2, 1),
)


def seed_dashboard_reference(session: Session) -> None:
    """Populate the Dashboard reference tables.  Safe to call repeatedly."""
    from app.ingest.reference_data import _upsert

    _upsert(
        session,
        DashboardIndicator,
        [
            {
                "code": code,
                "name": name,
                "short_name": short_name,
                "lower_is_better": lower_is_better,
                "unit": unit,
                "sort_order": sort_order,
                "is_informational": informational,
            }
            for (
                code,
                name,
                short_name,
                lower_is_better,
                unit,
                sort_order,
                informational,
            ) in _INDICATORS
        ],
    )
    _upsert(
        session,
        DashboardStudentGroup,
        [
            {
                "code": code,
                "name": name,
                "category": category,
                "sort_order": sort_order,
            }
            for code, name, category, sort_order in _STUDENT_GROUPS
        ],
    )
    _upsert(
        session,
        DashboardCutpoint,
        [
            {
                "indicator_code": indicator,
                "variant": variant,
                "kind": kind,
                "level": level,
                "lower_bound": lower,
                "upper_bound": upper,
                "label": label,
            }
            for indicator, variant, kind, level, lower, upper, label in _CUTPOINTS
        ],
    )
    _upsert(
        session,
        DashboardColorCell,
        [
            {
                "indicator_code": indicator,
                "variant": variant,
                "small_denominator": small,
                "status_level": status,
                "change_level": change,
                "color": color,
            }
            for indicator, variant, small, status, change, color in _COLOR_CELLS
        ],
    )
