// This file is auto-generated by @hey-api/openapi-ts

import {
	type DefaultError,
	type InfiniteData,
	infiniteQueryOptions,
	queryOptions,
	type UseMutationOptions,
} from '@tanstack/react-query'

import { client } from '../client.gen'
import {
	CensusdataService,
	DashboardService,
	EntitiesService,
	IngestService,
	ItemsService,
	LocalIndicatorsService,
	LoginService,
	type Options,
	PrivateService,
	ReferenceService,
	ReportsService,
	SchoolsService,
	UsersService,
	UtilsService,
} from '../sdk.gen'
import type {
	CensusdataCountOfCensusDataData,
	CensusdataCountOfCensusDataError,
	CensusdataCountOfCensusDataResponse,
	CensusdataCreateCensusDataData,
	CensusdataCreateCensusDataError,
	CensusdataCreateCensusDataResponse,
	CensusdataDeleteCensusDataData,
	CensusdataDeleteCensusDataError,
	CensusdataDeleteCensusDataResponse,
	CensusdataReadCensusDataData,
	CensusdataReadCensusDataError,
	CensusdataReadCensusDataResponse,
	CensusdataUpdateCensusDataData,
	CensusdataUpdateCensusDataError,
	CensusdataUpdateCensusDataResponse,
	DashboardReadCatalogData,
	DashboardReadCatalogError,
	DashboardReadCatalogResponse,
	DashboardReadChildrenData,
	DashboardReadChildrenError,
	DashboardReadChildrenResponse,
	DashboardReadEnrollmentData,
	DashboardReadEnrollmentError,
	DashboardReadEnrollmentResponse,
	DashboardReadGrowthData,
	DashboardReadGrowthError,
	DashboardReadGrowthResponse,
	DashboardReadIndicatorData,
	DashboardReadIndicatorError,
	DashboardReadIndicatorResponse,
	DashboardReadIndicatorsData,
	DashboardReadIndicatorsError,
	DashboardReadIndicatorsResponse,
	DashboardReadTrendData,
	DashboardReadTrendError,
	DashboardReadTrendResponse,
	EntitiesReadChildrenData,
	EntitiesReadChildrenError,
	EntitiesReadChildrenResponse,
	EntitiesReadEntityData,
	EntitiesReadEntityError,
	EntitiesReadEntityResponse,
	EntitiesSearchEntitiesData,
	EntitiesSearchEntitiesError,
	EntitiesSearchEntitiesResponse,
	IngestListRunsData,
	IngestListRunsError,
	IngestListRunsResponse,
	IngestReadRunData,
	IngestReadRunError,
	IngestReadRunResponse,
	IngestStartIngestData,
	IngestStartIngestError,
	IngestStartIngestResponse,
	ItemsCreateItemData,
	ItemsCreateItemError,
	ItemsCreateItemResponse,
	ItemsDeleteItemData,
	ItemsDeleteItemError,
	ItemsDeleteItemResponse,
	ItemsReadItemData,
	ItemsReadItemError,
	ItemsReadItemResponse,
	ItemsReadItemsData,
	ItemsReadItemsError,
	ItemsReadItemsResponse,
	ItemsUpdateItemData,
	ItemsUpdateItemError,
	ItemsUpdateItemResponse,
	LocalIndicatorsReadCatalogData,
	LocalIndicatorsReadCatalogError,
	LocalIndicatorsReadCatalogResponse,
	LocalIndicatorsReadLocalIndicatorsData,
	LocalIndicatorsReadLocalIndicatorsError,
	LocalIndicatorsReadLocalIndicatorsResponse,
	LocalIndicatorsReadPriorityData,
	LocalIndicatorsReadPriorityError,
	LocalIndicatorsReadPriorityResponse,
	LocalIndicatorsReadTrendData,
	LocalIndicatorsReadTrendError,
	LocalIndicatorsReadTrendResponse,
	LoginForcePasswordResetForUsersData,
	LoginForcePasswordResetForUsersError,
	LoginForcePasswordResetForUsersResponse,
	LoginLoginAccessTokenData,
	LoginLoginAccessTokenError,
	LoginLoginAccessTokenResponse,
	LoginRecoverPasswordData,
	LoginRecoverPasswordError,
	LoginRecoverPasswordHtmlContentData,
	LoginRecoverPasswordHtmlContentError,
	LoginRecoverPasswordHtmlContentResponse,
	LoginRecoverPasswordResponse,
	LoginResetPasswordData,
	LoginResetPasswordError,
	LoginResetPasswordResponse,
	LoginTestTokenData,
	LoginTestTokenResponse,
	PrivateCreateUserData,
	PrivateCreateUserError,
	PrivateCreateUserResponse,
	ReferenceReadCatalogData,
	ReferenceReadCatalogError,
	ReferenceReadCatalogResponse,
	ReportsReadChildResultsData,
	ReportsReadChildResultsError,
	ReportsReadChildResultsResponse,
	ReportsReadComparisonData,
	ReportsReadComparisonError,
	ReportsReadComparisonResponse,
	ReportsReadGradesData,
	ReportsReadGradesError,
	ReportsReadGradesResponse,
	ReportsReadOverviewData,
	ReportsReadOverviewError,
	ReportsReadOverviewResponse,
	ReportsReadStudentGroupsData,
	ReportsReadStudentGroupsError,
	ReportsReadStudentGroupsResponse,
	ReportsReadSubscoresData,
	ReportsReadSubscoresError,
	ReportsReadSubscoresResponse,
	ReportsReadTrendData,
	ReportsReadTrendError,
	ReportsReadTrendResponse,
	SchoolsReadSchoolsData,
	SchoolsReadSchoolsError,
	SchoolsReadSchoolsResponse,
	SchoolsReadSchoolsSummaryData,
	SchoolsReadSchoolsSummaryError,
	SchoolsReadSchoolsSummaryResponse,
	UsersCreateUserData,
	UsersCreateUserError,
	UsersCreateUserResponse,
	UsersDeleteUserData,
	UsersDeleteUserError,
	UsersDeleteUserMeData,
	UsersDeleteUserMeResponse,
	UsersDeleteUserResponse,
	UsersGetUserPreferencesData,
	UsersGetUserPreferencesResponse,
	UsersReadUserByIdData,
	UsersReadUserByIdError,
	UsersReadUserByIdResponse,
	UsersReadUserMeData,
	UsersReadUserMeResponse,
	UsersReadUsersData,
	UsersReadUsersError,
	UsersReadUsersResponse,
	UsersRegisterUserData,
	UsersRegisterUserError,
	UsersRegisterUserResponse,
	UsersUpdatePasswordMeData,
	UsersUpdatePasswordMeError,
	UsersUpdatePasswordMeResponse,
	UsersUpdateUserData,
	UsersUpdateUserError,
	UsersUpdateUserMeData,
	UsersUpdateUserMeError,
	UsersUpdateUserMeResponse,
	UsersUpdateUserPreferencesData,
	UsersUpdateUserPreferencesError,
	UsersUpdateUserPreferencesResponse,
	UsersUpdateUserResponse,
	UtilsHealthCheckData,
	UtilsHealthCheckResponse,
	UtilsTestEmailData,
	UtilsTestEmailError,
	UtilsTestEmailResponse,
} from '../types.gen'

/**
 * Login Access Token
 *
 * OAuth2 compatible token login, get an access token for future requests.
 */
export const loginLoginAccessTokenMutation = (
	options?: Partial<Options<LoginLoginAccessTokenData>>,
): UseMutationOptions<
	LoginLoginAccessTokenResponse,
	LoginLoginAccessTokenError,
	Options<LoginLoginAccessTokenData>
> => {
	const mutationOptions: UseMutationOptions<
		LoginLoginAccessTokenResponse,
		LoginLoginAccessTokenError,
		Options<LoginLoginAccessTokenData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await LoginService.loginLoginAccessToken({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

/**
 * Test Token
 *
 * Test access token.
 */
export const loginTestTokenMutation = (
	options?: Partial<Options<LoginTestTokenData>>,
): UseMutationOptions<LoginTestTokenResponse, DefaultError, Options<LoginTestTokenData>> => {
	const mutationOptions: UseMutationOptions<
		LoginTestTokenResponse,
		DefaultError,
		Options<LoginTestTokenData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await LoginService.loginTestToken({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

/**
 * Recover Password
 *
 * Password recovery. Always return the same response to prevent email enumeration attacks. Only send email if user actually exists.
 */
export const loginRecoverPasswordMutation = (
	options?: Partial<Options<LoginRecoverPasswordData>>,
): UseMutationOptions<
	LoginRecoverPasswordResponse,
	LoginRecoverPasswordError,
	Options<LoginRecoverPasswordData>
> => {
	const mutationOptions: UseMutationOptions<
		LoginRecoverPasswordResponse,
		LoginRecoverPasswordError,
		Options<LoginRecoverPasswordData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await LoginService.loginRecoverPassword({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

/**
 * Reset Password
 *
 * Reset password. Don't reveal that the user doesn't exist - use same error as invalid token.
 */
export const loginResetPasswordMutation = (
	options?: Partial<Options<LoginResetPasswordData>>,
): UseMutationOptions<
	LoginResetPasswordResponse,
	LoginResetPasswordError,
	Options<LoginResetPasswordData>
> => {
	const mutationOptions: UseMutationOptions<
		LoginResetPasswordResponse,
		LoginResetPasswordError,
		Options<LoginResetPasswordData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await LoginService.loginResetPassword({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

/**
 * Recover Password Html Content
 *
 * HTML content for password recovery.
 */
export const loginRecoverPasswordHtmlContentMutation = (
	options?: Partial<Options<LoginRecoverPasswordHtmlContentData>>,
): UseMutationOptions<
	LoginRecoverPasswordHtmlContentResponse,
	LoginRecoverPasswordHtmlContentError,
	Options<LoginRecoverPasswordHtmlContentData>
> => {
	const mutationOptions: UseMutationOptions<
		LoginRecoverPasswordHtmlContentResponse,
		LoginRecoverPasswordHtmlContentError,
		Options<LoginRecoverPasswordHtmlContentData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await LoginService.loginRecoverPasswordHtmlContent({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

/**
 * Force Password Reset For Users
 *
 * Force password reset for a targeted list of users or all active users.
 */
export const loginForcePasswordResetForUsersMutation = (
	options?: Partial<Options<LoginForcePasswordResetForUsersData>>,
): UseMutationOptions<
	LoginForcePasswordResetForUsersResponse,
	LoginForcePasswordResetForUsersError,
	Options<LoginForcePasswordResetForUsersData>
> => {
	const mutationOptions: UseMutationOptions<
		LoginForcePasswordResetForUsersResponse,
		LoginForcePasswordResetForUsersError,
		Options<LoginForcePasswordResetForUsersData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await LoginService.loginForcePasswordResetForUsers({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export type QueryKey<TOptions extends Options> = [
	Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
		_id: string
		_infinite?: boolean
		tags?: ReadonlyArray<string>
	},
]

const createQueryKey = <TOptions extends Options>(
	id: string,
	options?: TOptions,
	infinite?: boolean,
	tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
	const params: QueryKey<TOptions>[0] = {
		_id: id,
		baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
	} as QueryKey<TOptions>[0]
	if (infinite) {
		params._infinite = infinite
	}
	if (tags) {
		params.tags = tags
	}
	if (options?.body) {
		params.body = options.body
	}
	if (options?.headers) {
		params.headers = options.headers
	}
	if (options?.path) {
		params.path = options.path
	}
	if (options?.query) {
		params.query = options.query
	}
	return [params]
}

export const usersReadUsersQueryKey = (options?: Options<UsersReadUsersData>) =>
	createQueryKey('usersReadUsers', options)

/**
 * Read Users
 *
 * Retrieve users.
 */
export const usersReadUsersOptions = (options?: Options<UsersReadUsersData>) =>
	queryOptions<
		UsersReadUsersResponse,
		UsersReadUsersError,
		UsersReadUsersResponse,
		ReturnType<typeof usersReadUsersQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await UsersService.usersReadUsers({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: usersReadUsersQueryKey(options),
	})

/**
 * Create User
 *
 * Create new user.
 */
export const usersCreateUserMutation = (
	options?: Partial<Options<UsersCreateUserData>>,
): UseMutationOptions<
	UsersCreateUserResponse,
	UsersCreateUserError,
	Options<UsersCreateUserData>
> => {
	const mutationOptions: UseMutationOptions<
		UsersCreateUserResponse,
		UsersCreateUserError,
		Options<UsersCreateUserData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await UsersService.usersCreateUser({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

/**
 * Delete User Me
 *
 * Delete own user.
 */
export const usersDeleteUserMeMutation = (
	options?: Partial<Options<UsersDeleteUserMeData>>,
): UseMutationOptions<UsersDeleteUserMeResponse, DefaultError, Options<UsersDeleteUserMeData>> => {
	const mutationOptions: UseMutationOptions<
		UsersDeleteUserMeResponse,
		DefaultError,
		Options<UsersDeleteUserMeData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await UsersService.usersDeleteUserMe({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const usersReadUserMeQueryKey = (options?: Options<UsersReadUserMeData>) =>
	createQueryKey('usersReadUserMe', options)

/**
 * Read User Me
 *
 * Get current user.
 */
export const usersReadUserMeOptions = (options?: Options<UsersReadUserMeData>) =>
	queryOptions<
		UsersReadUserMeResponse,
		DefaultError,
		UsersReadUserMeResponse,
		ReturnType<typeof usersReadUserMeQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await UsersService.usersReadUserMe({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: usersReadUserMeQueryKey(options),
	})

/**
 * Update User Me
 *
 * Update own user.
 */
export const usersUpdateUserMeMutation = (
	options?: Partial<Options<UsersUpdateUserMeData>>,
): UseMutationOptions<
	UsersUpdateUserMeResponse,
	UsersUpdateUserMeError,
	Options<UsersUpdateUserMeData>
> => {
	const mutationOptions: UseMutationOptions<
		UsersUpdateUserMeResponse,
		UsersUpdateUserMeError,
		Options<UsersUpdateUserMeData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await UsersService.usersUpdateUserMe({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

/**
 * Update Password Me
 *
 * Update own password.
 */
export const usersUpdatePasswordMeMutation = (
	options?: Partial<Options<UsersUpdatePasswordMeData>>,
): UseMutationOptions<
	UsersUpdatePasswordMeResponse,
	UsersUpdatePasswordMeError,
	Options<UsersUpdatePasswordMeData>
> => {
	const mutationOptions: UseMutationOptions<
		UsersUpdatePasswordMeResponse,
		UsersUpdatePasswordMeError,
		Options<UsersUpdatePasswordMeData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await UsersService.usersUpdatePasswordMe({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const usersGetUserPreferencesQueryKey = (options?: Options<UsersGetUserPreferencesData>) =>
	createQueryKey('usersGetUserPreferences', options)

/**
 * Get User Preferences
 *
 * Get current user's preferences.
 */
export const usersGetUserPreferencesOptions = (options?: Options<UsersGetUserPreferencesData>) =>
	queryOptions<
		UsersGetUserPreferencesResponse,
		DefaultError,
		UsersGetUserPreferencesResponse,
		ReturnType<typeof usersGetUserPreferencesQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await UsersService.usersGetUserPreferences({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: usersGetUserPreferencesQueryKey(options),
	})

/**
 * Update User Preferences
 *
 * Update own user's preferences.
 */
export const usersUpdateUserPreferencesMutation = (
	options?: Partial<Options<UsersUpdateUserPreferencesData>>,
): UseMutationOptions<
	UsersUpdateUserPreferencesResponse,
	UsersUpdateUserPreferencesError,
	Options<UsersUpdateUserPreferencesData>
> => {
	const mutationOptions: UseMutationOptions<
		UsersUpdateUserPreferencesResponse,
		UsersUpdateUserPreferencesError,
		Options<UsersUpdateUserPreferencesData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await UsersService.usersUpdateUserPreferences({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

/**
 * Register User
 *
 * Create new user without the need to be logged in.
 */
export const usersRegisterUserMutation = (
	options?: Partial<Options<UsersRegisterUserData>>,
): UseMutationOptions<
	UsersRegisterUserResponse,
	UsersRegisterUserError,
	Options<UsersRegisterUserData>
> => {
	const mutationOptions: UseMutationOptions<
		UsersRegisterUserResponse,
		UsersRegisterUserError,
		Options<UsersRegisterUserData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await UsersService.usersRegisterUser({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

/**
 * Delete User
 *
 * Delete a user.
 */
export const usersDeleteUserMutation = (
	options?: Partial<Options<UsersDeleteUserData>>,
): UseMutationOptions<
	UsersDeleteUserResponse,
	UsersDeleteUserError,
	Options<UsersDeleteUserData>
> => {
	const mutationOptions: UseMutationOptions<
		UsersDeleteUserResponse,
		UsersDeleteUserError,
		Options<UsersDeleteUserData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await UsersService.usersDeleteUser({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const usersReadUserByIdQueryKey = (options: Options<UsersReadUserByIdData>) =>
	createQueryKey('usersReadUserById', options)

/**
 * Read User By Id
 *
 * Get a specific user by id.
 */
export const usersReadUserByIdOptions = (options: Options<UsersReadUserByIdData>) =>
	queryOptions<
		UsersReadUserByIdResponse,
		UsersReadUserByIdError,
		UsersReadUserByIdResponse,
		ReturnType<typeof usersReadUserByIdQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await UsersService.usersReadUserById({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: usersReadUserByIdQueryKey(options),
	})

/**
 * Update User
 *
 * Update a user.
 */
export const usersUpdateUserMutation = (
	options?: Partial<Options<UsersUpdateUserData>>,
): UseMutationOptions<
	UsersUpdateUserResponse,
	UsersUpdateUserError,
	Options<UsersUpdateUserData>
> => {
	const mutationOptions: UseMutationOptions<
		UsersUpdateUserResponse,
		UsersUpdateUserError,
		Options<UsersUpdateUserData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await UsersService.usersUpdateUser({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

/**
 * Test Email
 *
 * Test emails.
 */
export const utilsTestEmailMutation = (
	options?: Partial<Options<UtilsTestEmailData>>,
): UseMutationOptions<UtilsTestEmailResponse, UtilsTestEmailError, Options<UtilsTestEmailData>> => {
	const mutationOptions: UseMutationOptions<
		UtilsTestEmailResponse,
		UtilsTestEmailError,
		Options<UtilsTestEmailData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await UtilsService.utilsTestEmail({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const utilsHealthCheckQueryKey = (options?: Options<UtilsHealthCheckData>) =>
	createQueryKey('utilsHealthCheck', options)

/**
 * Health Check
 */
export const utilsHealthCheckOptions = (options?: Options<UtilsHealthCheckData>) =>
	queryOptions<
		UtilsHealthCheckResponse,
		DefaultError,
		UtilsHealthCheckResponse,
		ReturnType<typeof utilsHealthCheckQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await UtilsService.utilsHealthCheck({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: utilsHealthCheckQueryKey(options),
	})

export const itemsReadItemsQueryKey = (options?: Options<ItemsReadItemsData>) =>
	createQueryKey('itemsReadItems', options)

/**
 * Read Items
 *
 * Retrieve items.
 */
export const itemsReadItemsOptions = (options?: Options<ItemsReadItemsData>) =>
	queryOptions<
		ItemsReadItemsResponse,
		ItemsReadItemsError,
		ItemsReadItemsResponse,
		ReturnType<typeof itemsReadItemsQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await ItemsService.itemsReadItems({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: itemsReadItemsQueryKey(options),
	})

/**
 * Create Item
 *
 * Create new item.
 */
export const itemsCreateItemMutation = (
	options?: Partial<Options<ItemsCreateItemData>>,
): UseMutationOptions<
	ItemsCreateItemResponse,
	ItemsCreateItemError,
	Options<ItemsCreateItemData>
> => {
	const mutationOptions: UseMutationOptions<
		ItemsCreateItemResponse,
		ItemsCreateItemError,
		Options<ItemsCreateItemData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await ItemsService.itemsCreateItem({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

/**
 * Delete Item
 *
 * Delete an item.
 */
export const itemsDeleteItemMutation = (
	options?: Partial<Options<ItemsDeleteItemData>>,
): UseMutationOptions<
	ItemsDeleteItemResponse,
	ItemsDeleteItemError,
	Options<ItemsDeleteItemData>
> => {
	const mutationOptions: UseMutationOptions<
		ItemsDeleteItemResponse,
		ItemsDeleteItemError,
		Options<ItemsDeleteItemData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await ItemsService.itemsDeleteItem({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const itemsReadItemQueryKey = (options: Options<ItemsReadItemData>) =>
	createQueryKey('itemsReadItem', options)

/**
 * Read Item
 *
 * Get item by ID.
 */
export const itemsReadItemOptions = (options: Options<ItemsReadItemData>) =>
	queryOptions<
		ItemsReadItemResponse,
		ItemsReadItemError,
		ItemsReadItemResponse,
		ReturnType<typeof itemsReadItemQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await ItemsService.itemsReadItem({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: itemsReadItemQueryKey(options),
	})

/**
 * Update Item
 *
 * Update an item.
 */
export const itemsUpdateItemMutation = (
	options?: Partial<Options<ItemsUpdateItemData>>,
): UseMutationOptions<
	ItemsUpdateItemResponse,
	ItemsUpdateItemError,
	Options<ItemsUpdateItemData>
> => {
	const mutationOptions: UseMutationOptions<
		ItemsUpdateItemResponse,
		ItemsUpdateItemError,
		Options<ItemsUpdateItemData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await ItemsService.itemsUpdateItem({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const censusdataCountOfCensusDataQueryKey = (
	options?: Options<CensusdataCountOfCensusDataData>,
) => createQueryKey('censusdataCountOfCensusData', options)

/**
 * Count Of Census Data
 *
 * Retrieve census data.
 */
export const censusdataCountOfCensusDataOptions = (
	options?: Options<CensusdataCountOfCensusDataData>,
) =>
	queryOptions<
		CensusdataCountOfCensusDataResponse,
		CensusdataCountOfCensusDataError,
		CensusdataCountOfCensusDataResponse,
		ReturnType<typeof censusdataCountOfCensusDataQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await CensusdataService.censusdataCountOfCensusData({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: censusdataCountOfCensusDataQueryKey(options),
	})

/**
 * Create Census Data
 *
 * Create new census data.
 */
export const censusdataCreateCensusDataMutation = (
	options?: Partial<Options<CensusdataCreateCensusDataData>>,
): UseMutationOptions<
	CensusdataCreateCensusDataResponse,
	CensusdataCreateCensusDataError,
	Options<CensusdataCreateCensusDataData>
> => {
	const mutationOptions: UseMutationOptions<
		CensusdataCreateCensusDataResponse,
		CensusdataCreateCensusDataError,
		Options<CensusdataCreateCensusDataData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await CensusdataService.censusdataCreateCensusData({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

/**
 * Delete Census Data
 *
 * Delete census data by ID.
 */
export const censusdataDeleteCensusDataMutation = (
	options?: Partial<Options<CensusdataDeleteCensusDataData>>,
): UseMutationOptions<
	CensusdataDeleteCensusDataResponse,
	CensusdataDeleteCensusDataError,
	Options<CensusdataDeleteCensusDataData>
> => {
	const mutationOptions: UseMutationOptions<
		CensusdataDeleteCensusDataResponse,
		CensusdataDeleteCensusDataError,
		Options<CensusdataDeleteCensusDataData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await CensusdataService.censusdataDeleteCensusData({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const censusdataReadCensusDataQueryKey = (options: Options<CensusdataReadCensusDataData>) =>
	createQueryKey('censusdataReadCensusData', options)

/**
 * Read Census Data
 *
 * Get census data by ID.
 */
export const censusdataReadCensusDataOptions = (options: Options<CensusdataReadCensusDataData>) =>
	queryOptions<
		CensusdataReadCensusDataResponse,
		CensusdataReadCensusDataError,
		CensusdataReadCensusDataResponse,
		ReturnType<typeof censusdataReadCensusDataQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await CensusdataService.censusdataReadCensusData({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: censusdataReadCensusDataQueryKey(options),
	})

/**
 * Update Census Data
 *
 * Update census data by ID.
 */
export const censusdataUpdateCensusDataMutation = (
	options?: Partial<Options<CensusdataUpdateCensusDataData>>,
): UseMutationOptions<
	CensusdataUpdateCensusDataResponse,
	CensusdataUpdateCensusDataError,
	Options<CensusdataUpdateCensusDataData>
> => {
	const mutationOptions: UseMutationOptions<
		CensusdataUpdateCensusDataResponse,
		CensusdataUpdateCensusDataError,
		Options<CensusdataUpdateCensusDataData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await CensusdataService.censusdataUpdateCensusData({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const schoolsReadSchoolsQueryKey = (options?: Options<SchoolsReadSchoolsData>) =>
	createQueryKey('schoolsReadSchools', options)

/**
 * Read Schools
 *
 * Retrieve schools.
 */
export const schoolsReadSchoolsOptions = (options?: Options<SchoolsReadSchoolsData>) =>
	queryOptions<
		SchoolsReadSchoolsResponse,
		SchoolsReadSchoolsError,
		SchoolsReadSchoolsResponse,
		ReturnType<typeof schoolsReadSchoolsQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await SchoolsService.schoolsReadSchools({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: schoolsReadSchoolsQueryKey(options),
	})

export const schoolsReadSchoolsSummaryQueryKey = (
	options?: Options<SchoolsReadSchoolsSummaryData>,
) => createQueryKey('schoolsReadSchoolsSummary', options)

/**
 * Read Schools Summary
 *
 * Retrieve schools with a summarized view.
 */
export const schoolsReadSchoolsSummaryOptions = (
	options?: Options<SchoolsReadSchoolsSummaryData>,
) =>
	queryOptions<
		SchoolsReadSchoolsSummaryResponse,
		SchoolsReadSchoolsSummaryError,
		SchoolsReadSchoolsSummaryResponse,
		ReturnType<typeof schoolsReadSchoolsSummaryQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await SchoolsService.schoolsReadSchoolsSummary({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: schoolsReadSchoolsSummaryQueryKey(options),
	})

export const referenceReadCatalogQueryKey = (options?: Options<ReferenceReadCatalogData>) =>
	createQueryKey('referenceReadCatalog', options)

/**
 * Read Catalog
 *
 * Everything needed to populate the report filters for one year.
 */
export const referenceReadCatalogOptions = (options?: Options<ReferenceReadCatalogData>) =>
	queryOptions<
		ReferenceReadCatalogResponse,
		ReferenceReadCatalogError,
		ReferenceReadCatalogResponse,
		ReturnType<typeof referenceReadCatalogQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await ReferenceService.referenceReadCatalog({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: referenceReadCatalogQueryKey(options),
	})

export const entitiesSearchEntitiesQueryKey = (options?: Options<EntitiesSearchEntitiesData>) =>
	createQueryKey('entitiesSearchEntities', options)

/**
 * Search Entities
 *
 * Find entities by name or CDS code.
 */
export const entitiesSearchEntitiesOptions = (options?: Options<EntitiesSearchEntitiesData>) =>
	queryOptions<
		EntitiesSearchEntitiesResponse,
		EntitiesSearchEntitiesError,
		EntitiesSearchEntitiesResponse,
		ReturnType<typeof entitiesSearchEntitiesQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await EntitiesService.entitiesSearchEntities({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: entitiesSearchEntitiesQueryKey(options),
	})

const createInfiniteParams = <
	K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
	queryKey: QueryKey<Options>,
	page: K,
) => {
	const params = { ...queryKey[0] }
	if (page.body) {
		params.body = {
			...(queryKey[0].body as any),
			...(page.body as any),
		}
	}
	if (page.headers) {
		params.headers = {
			...queryKey[0].headers,
			...page.headers,
		}
	}
	if (page.path) {
		params.path = {
			...(queryKey[0].path as any),
			...(page.path as any),
		}
	}
	if (page.query) {
		params.query = {
			...(queryKey[0].query as any),
			...(page.query as any),
		}
	}
	return params as unknown as typeof page
}

export const entitiesSearchEntitiesInfiniteQueryKey = (
	options?: Options<EntitiesSearchEntitiesData>,
): QueryKey<Options<EntitiesSearchEntitiesData>> =>
	createQueryKey('entitiesSearchEntities', options, true)

/**
 * Search Entities
 *
 * Find entities by name or CDS code.
 */
export const entitiesSearchEntitiesInfiniteOptions = (
	options?: Options<EntitiesSearchEntitiesData>,
) => {
	const opts = infiniteQueryOptions<
		EntitiesSearchEntitiesResponse,
		EntitiesSearchEntitiesError,
		InfiniteData<EntitiesSearchEntitiesResponse>,
		QueryKey<Options<EntitiesSearchEntitiesData>>,
		| number
		| Pick<QueryKey<Options<EntitiesSearchEntitiesData>>[0], 'body' | 'headers' | 'path' | 'query'>
	>(
		// @ts-ignore
		{
			queryFn: async ({ pageParam, queryKey, signal }) => {
				// @ts-ignore
				const page: Pick<
					QueryKey<Options<EntitiesSearchEntitiesData>>[0],
					'body' | 'headers' | 'path' | 'query'
				> =
					typeof pageParam === 'object'
						? pageParam
						: {
								query: {
									offset: pageParam,
								},
							}
				const params = createInfiniteParams(queryKey, page)
				const { data } = await EntitiesService.entitiesSearchEntities({
					...options,
					...params,
					signal,
					throwOnError: true,
				})
				return data
			},
			queryKey: entitiesSearchEntitiesInfiniteQueryKey(options),
		},
	)
	return opts as Omit<typeof opts, 'initialData'>
}

export const entitiesReadEntityQueryKey = (options: Options<EntitiesReadEntityData>) =>
	createQueryKey('entitiesReadEntity', options)

/**
 * Read Entity
 *
 * One entity together with the entities it rolls up into.
 */
export const entitiesReadEntityOptions = (options: Options<EntitiesReadEntityData>) =>
	queryOptions<
		EntitiesReadEntityResponse,
		EntitiesReadEntityError,
		EntitiesReadEntityResponse,
		ReturnType<typeof entitiesReadEntityQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await EntitiesService.entitiesReadEntity({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: entitiesReadEntityQueryKey(options),
	})

export const entitiesReadChildrenQueryKey = (options: Options<EntitiesReadChildrenData>) =>
	createQueryKey('entitiesReadChildren', options)

/**
 * Read Children
 *
 * The entities directly inside this one.
 */
export const entitiesReadChildrenOptions = (options: Options<EntitiesReadChildrenData>) =>
	queryOptions<
		EntitiesReadChildrenResponse,
		EntitiesReadChildrenError,
		EntitiesReadChildrenResponse,
		ReturnType<typeof entitiesReadChildrenQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await EntitiesService.entitiesReadChildren({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: entitiesReadChildrenQueryKey(options),
	})

export const entitiesReadChildrenInfiniteQueryKey = (
	options: Options<EntitiesReadChildrenData>,
): QueryKey<Options<EntitiesReadChildrenData>> =>
	createQueryKey('entitiesReadChildren', options, true)

/**
 * Read Children
 *
 * The entities directly inside this one.
 */
export const entitiesReadChildrenInfiniteOptions = (options: Options<EntitiesReadChildrenData>) => {
	const opts = infiniteQueryOptions<
		EntitiesReadChildrenResponse,
		EntitiesReadChildrenError,
		InfiniteData<EntitiesReadChildrenResponse>,
		QueryKey<Options<EntitiesReadChildrenData>>,
		| number
		| Pick<QueryKey<Options<EntitiesReadChildrenData>>[0], 'body' | 'headers' | 'path' | 'query'>
	>(
		// @ts-ignore
		{
			queryFn: async ({ pageParam, queryKey, signal }) => {
				// @ts-ignore
				const page: Pick<
					QueryKey<Options<EntitiesReadChildrenData>>[0],
					'body' | 'headers' | 'path' | 'query'
				> =
					typeof pageParam === 'object'
						? pageParam
						: {
								query: {
									offset: pageParam,
								},
							}
				const params = createInfiniteParams(queryKey, page)
				const { data } = await EntitiesService.entitiesReadChildren({
					...options,
					...params,
					signal,
					throwOnError: true,
				})
				return data
			},
			queryKey: entitiesReadChildrenInfiniteQueryKey(options),
		},
	)
	return opts as Omit<typeof opts, 'initialData'>
}

export const reportsReadOverviewQueryKey = (options?: Options<ReportsReadOverviewData>) =>
	createQueryKey('reportsReadOverview', options)

/**
 * Read Overview
 *
 * Overall results for one entity, year, student group and grade.
 */
export const reportsReadOverviewOptions = (options?: Options<ReportsReadOverviewData>) =>
	queryOptions<
		ReportsReadOverviewResponse,
		ReportsReadOverviewError,
		ReportsReadOverviewResponse,
		ReturnType<typeof reportsReadOverviewQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await ReportsService.reportsReadOverview({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: reportsReadOverviewQueryKey(options),
	})

export const reportsReadSubscoresQueryKey = (options: Options<ReportsReadSubscoresData>) =>
	createQueryKey('reportsReadSubscores', options)

/**
 * Read Subscores
 *
 * The areas, domains and composites reported beneath one test.
 */
export const reportsReadSubscoresOptions = (options: Options<ReportsReadSubscoresData>) =>
	queryOptions<
		ReportsReadSubscoresResponse,
		ReportsReadSubscoresError,
		ReportsReadSubscoresResponse,
		ReturnType<typeof reportsReadSubscoresQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await ReportsService.reportsReadSubscores({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: reportsReadSubscoresQueryKey(options),
	})

export const reportsReadTrendQueryKey = (options: Options<ReportsReadTrendData>) =>
	createQueryKey('reportsReadTrend', options)

/**
 * Read Trend
 *
 * One cell's results across every year the state reported them.
 */
export const reportsReadTrendOptions = (options: Options<ReportsReadTrendData>) =>
	queryOptions<
		ReportsReadTrendResponse,
		ReportsReadTrendError,
		ReportsReadTrendResponse,
		ReturnType<typeof reportsReadTrendQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await ReportsService.reportsReadTrend({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: reportsReadTrendQueryKey(options),
	})

export const reportsReadStudentGroupsQueryKey = (options: Options<ReportsReadStudentGroupsData>) =>
	createQueryKey('reportsReadStudentGroups', options)

/**
 * Read Student Groups
 *
 * Every student group's result for one entity, test and grade.
 */
export const reportsReadStudentGroupsOptions = (options: Options<ReportsReadStudentGroupsData>) =>
	queryOptions<
		ReportsReadStudentGroupsResponse,
		ReportsReadStudentGroupsError,
		ReportsReadStudentGroupsResponse,
		ReturnType<typeof reportsReadStudentGroupsQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await ReportsService.reportsReadStudentGroups({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: reportsReadStudentGroupsQueryKey(options),
	})

export const reportsReadGradesQueryKey = (options: Options<ReportsReadGradesData>) =>
	createQueryKey('reportsReadGrades', options)

/**
 * Read Grades
 *
 * One entity's result for every grade a test reports.
 */
export const reportsReadGradesOptions = (options: Options<ReportsReadGradesData>) =>
	queryOptions<
		ReportsReadGradesResponse,
		ReportsReadGradesError,
		ReportsReadGradesResponse,
		ReturnType<typeof reportsReadGradesQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await ReportsService.reportsReadGrades({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: reportsReadGradesQueryKey(options),
	})

export const reportsReadChildResultsQueryKey = (options: Options<ReportsReadChildResultsData>) =>
	createQueryKey('reportsReadChildResults', options)

/**
 * Read Child Results
 *
 * Results for the counties, districts or schools inside one entity.
 */
export const reportsReadChildResultsOptions = (options: Options<ReportsReadChildResultsData>) =>
	queryOptions<
		ReportsReadChildResultsResponse,
		ReportsReadChildResultsError,
		ReportsReadChildResultsResponse,
		ReturnType<typeof reportsReadChildResultsQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await ReportsService.reportsReadChildResults({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: reportsReadChildResultsQueryKey(options),
	})

export const reportsReadChildResultsInfiniteQueryKey = (
	options: Options<ReportsReadChildResultsData>,
): QueryKey<Options<ReportsReadChildResultsData>> =>
	createQueryKey('reportsReadChildResults', options, true)

/**
 * Read Child Results
 *
 * Results for the counties, districts or schools inside one entity.
 */
export const reportsReadChildResultsInfiniteOptions = (
	options: Options<ReportsReadChildResultsData>,
) => {
	const opts = infiniteQueryOptions<
		ReportsReadChildResultsResponse,
		ReportsReadChildResultsError,
		InfiniteData<ReportsReadChildResultsResponse>,
		QueryKey<Options<ReportsReadChildResultsData>>,
		| number
		| Pick<QueryKey<Options<ReportsReadChildResultsData>>[0], 'body' | 'headers' | 'path' | 'query'>
	>(
		// @ts-ignore
		{
			queryFn: async ({ pageParam, queryKey, signal }) => {
				// @ts-ignore
				const page: Pick<
					QueryKey<Options<ReportsReadChildResultsData>>[0],
					'body' | 'headers' | 'path' | 'query'
				> =
					typeof pageParam === 'object'
						? pageParam
						: {
								query: {
									offset: pageParam,
								},
							}
				const params = createInfiniteParams(queryKey, page)
				const { data } = await ReportsService.reportsReadChildResults({
					...options,
					...params,
					signal,
					throwOnError: true,
				})
				return data
			},
			queryKey: reportsReadChildResultsInfiniteQueryKey(options),
		},
	)
	return opts as Omit<typeof opts, 'initialData'>
}

export const reportsReadComparisonQueryKey = (options: Options<ReportsReadComparisonData>) =>
	createQueryKey('reportsReadComparison', options)

/**
 * Read Comparison
 *
 * Side-by-side results for an explicit list of entities.
 */
export const reportsReadComparisonOptions = (options: Options<ReportsReadComparisonData>) =>
	queryOptions<
		ReportsReadComparisonResponse,
		ReportsReadComparisonError,
		ReportsReadComparisonResponse,
		ReturnType<typeof reportsReadComparisonQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await ReportsService.reportsReadComparison({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: reportsReadComparisonQueryKey(options),
	})

export const dashboardReadCatalogQueryKey = (options?: Options<DashboardReadCatalogData>) =>
	createQueryKey('dashboardReadCatalog', options)

/**
 * Read Catalog
 *
 * Everything needed to populate the accountability filters.
 */
export const dashboardReadCatalogOptions = (options?: Options<DashboardReadCatalogData>) =>
	queryOptions<
		DashboardReadCatalogResponse,
		DashboardReadCatalogError,
		DashboardReadCatalogResponse,
		ReturnType<typeof dashboardReadCatalogQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await DashboardService.dashboardReadCatalog({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: dashboardReadCatalogQueryKey(options),
	})

export const dashboardReadIndicatorsQueryKey = (options?: Options<DashboardReadIndicatorsData>) =>
	createQueryKey('dashboardReadIndicators', options)

/**
 * Read Indicators
 *
 * Every indicator for one entity -- the Dashboard landing view.
 */
export const dashboardReadIndicatorsOptions = (options?: Options<DashboardReadIndicatorsData>) =>
	queryOptions<
		DashboardReadIndicatorsResponse,
		DashboardReadIndicatorsError,
		DashboardReadIndicatorsResponse,
		ReturnType<typeof dashboardReadIndicatorsQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await DashboardService.dashboardReadIndicators({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: dashboardReadIndicatorsQueryKey(options),
	})

export const dashboardReadIndicatorQueryKey = (options: Options<DashboardReadIndicatorData>) =>
	createQueryKey('dashboardReadIndicator', options)

/**
 * Read Indicator
 *
 * One indicator for one entity, broken out by student group.
 */
export const dashboardReadIndicatorOptions = (options: Options<DashboardReadIndicatorData>) =>
	queryOptions<
		DashboardReadIndicatorResponse,
		DashboardReadIndicatorError,
		DashboardReadIndicatorResponse,
		ReturnType<typeof dashboardReadIndicatorQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await DashboardService.dashboardReadIndicator({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: dashboardReadIndicatorQueryKey(options),
	})

export const dashboardReadTrendQueryKey = (options: Options<DashboardReadTrendData>) =>
	createQueryKey('dashboardReadTrend', options)

/**
 * Read Trend
 *
 * One indicator over time for one entity.
 */
export const dashboardReadTrendOptions = (options: Options<DashboardReadTrendData>) =>
	queryOptions<
		DashboardReadTrendResponse,
		DashboardReadTrendError,
		DashboardReadTrendResponse,
		ReturnType<typeof dashboardReadTrendQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await DashboardService.dashboardReadTrend({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: dashboardReadTrendQueryKey(options),
	})

export const dashboardReadChildrenQueryKey = (options: Options<DashboardReadChildrenData>) =>
	createQueryKey('dashboardReadChildren', options)

/**
 * Read Children
 *
 * The entities inside a district or county, ranked on one indicator.
 */
export const dashboardReadChildrenOptions = (options: Options<DashboardReadChildrenData>) =>
	queryOptions<
		DashboardReadChildrenResponse,
		DashboardReadChildrenError,
		DashboardReadChildrenResponse,
		ReturnType<typeof dashboardReadChildrenQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await DashboardService.dashboardReadChildren({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: dashboardReadChildrenQueryKey(options),
	})

export const dashboardReadChildrenInfiniteQueryKey = (
	options: Options<DashboardReadChildrenData>,
): QueryKey<Options<DashboardReadChildrenData>> =>
	createQueryKey('dashboardReadChildren', options, true)

/**
 * Read Children
 *
 * The entities inside a district or county, ranked on one indicator.
 */
export const dashboardReadChildrenInfiniteOptions = (
	options: Options<DashboardReadChildrenData>,
) => {
	const opts = infiniteQueryOptions<
		DashboardReadChildrenResponse,
		DashboardReadChildrenError,
		InfiniteData<DashboardReadChildrenResponse>,
		QueryKey<Options<DashboardReadChildrenData>>,
		| number
		| Pick<QueryKey<Options<DashboardReadChildrenData>>[0], 'body' | 'headers' | 'path' | 'query'>
	>(
		// @ts-ignore
		{
			queryFn: async ({ pageParam, queryKey, signal }) => {
				// @ts-ignore
				const page: Pick<
					QueryKey<Options<DashboardReadChildrenData>>[0],
					'body' | 'headers' | 'path' | 'query'
				> =
					typeof pageParam === 'object'
						? pageParam
						: {
								query: {
									offset: pageParam,
								},
							}
				const params = createInfiniteParams(queryKey, page)
				const { data } = await DashboardService.dashboardReadChildren({
					...options,
					...params,
					signal,
					throwOnError: true,
				})
				return data
			},
			queryKey: dashboardReadChildrenInfiniteQueryKey(options),
		},
	)
	return opts as Omit<typeof opts, 'initialData'>
}

export const dashboardReadGrowthQueryKey = (options?: Options<DashboardReadGrowthData>) =>
	createQueryKey('dashboardReadGrowth', options)

/**
 * Read Growth
 *
 * Growth in ELA and mathematics -- how far students moved.
 *
 * Reported for information only.  Growth is not an accountability result and
 * carries no performance colour.
 */
export const dashboardReadGrowthOptions = (options?: Options<DashboardReadGrowthData>) =>
	queryOptions<
		DashboardReadGrowthResponse,
		DashboardReadGrowthError,
		DashboardReadGrowthResponse,
		ReturnType<typeof dashboardReadGrowthQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await DashboardService.dashboardReadGrowth({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: dashboardReadGrowthQueryKey(options),
	})

export const dashboardReadEnrollmentQueryKey = (options?: Options<DashboardReadEnrollmentData>) =>
	createQueryKey('dashboardReadEnrollment', options)

/**
 * Read Enrollment
 *
 * Who attends: every student group's share of Census Day enrolment.
 */
export const dashboardReadEnrollmentOptions = (options?: Options<DashboardReadEnrollmentData>) =>
	queryOptions<
		DashboardReadEnrollmentResponse,
		DashboardReadEnrollmentError,
		DashboardReadEnrollmentResponse,
		ReturnType<typeof dashboardReadEnrollmentQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await DashboardService.dashboardReadEnrollment({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: dashboardReadEnrollmentQueryKey(options),
	})

export const localIndicatorsReadCatalogQueryKey = (
	options?: Options<LocalIndicatorsReadCatalogData>,
) => createQueryKey('localIndicatorsReadCatalog', options)

/**
 * Read Catalog
 *
 * Everything needed to populate the local indicator filters.
 */
export const localIndicatorsReadCatalogOptions = (
	options?: Options<LocalIndicatorsReadCatalogData>,
) =>
	queryOptions<
		LocalIndicatorsReadCatalogResponse,
		LocalIndicatorsReadCatalogError,
		LocalIndicatorsReadCatalogResponse,
		ReturnType<typeof localIndicatorsReadCatalogQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await LocalIndicatorsService.localIndicatorsReadCatalog({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: localIndicatorsReadCatalogQueryKey(options),
	})

export const localIndicatorsReadLocalIndicatorsQueryKey = (
	options?: Options<LocalIndicatorsReadLocalIndicatorsData>,
) => createQueryKey('localIndicatorsReadLocalIndicators', options)

/**
 * Read Local Indicators
 *
 * Every priority one LEA reported, for one year.
 */
export const localIndicatorsReadLocalIndicatorsOptions = (
	options?: Options<LocalIndicatorsReadLocalIndicatorsData>,
) =>
	queryOptions<
		LocalIndicatorsReadLocalIndicatorsResponse,
		LocalIndicatorsReadLocalIndicatorsError,
		LocalIndicatorsReadLocalIndicatorsResponse,
		ReturnType<typeof localIndicatorsReadLocalIndicatorsQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await LocalIndicatorsService.localIndicatorsReadLocalIndicators({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: localIndicatorsReadLocalIndicatorsQueryKey(options),
	})

export const localIndicatorsReadPriorityQueryKey = (
	options: Options<LocalIndicatorsReadPriorityData>,
) => createQueryKey('localIndicatorsReadPriority', options)

/**
 * Read Priority
 *
 * One priority in full, including everything the LEA wrote.
 */
export const localIndicatorsReadPriorityOptions = (
	options: Options<LocalIndicatorsReadPriorityData>,
) =>
	queryOptions<
		LocalIndicatorsReadPriorityResponse,
		LocalIndicatorsReadPriorityError,
		LocalIndicatorsReadPriorityResponse,
		ReturnType<typeof localIndicatorsReadPriorityQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await LocalIndicatorsService.localIndicatorsReadPriority({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: localIndicatorsReadPriorityQueryKey(options),
	})

export const localIndicatorsReadTrendQueryKey = (options: Options<LocalIndicatorsReadTrendData>) =>
	createQueryKey('localIndicatorsReadTrend', options)

/**
 * Read Trend
 *
 * One priority across every year the LEA has reported.
 */
export const localIndicatorsReadTrendOptions = (options: Options<LocalIndicatorsReadTrendData>) =>
	queryOptions<
		LocalIndicatorsReadTrendResponse,
		LocalIndicatorsReadTrendError,
		LocalIndicatorsReadTrendResponse,
		ReturnType<typeof localIndicatorsReadTrendQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await LocalIndicatorsService.localIndicatorsReadTrend({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: localIndicatorsReadTrendQueryKey(options),
	})

export const ingestListRunsQueryKey = (options?: Options<IngestListRunsData>) =>
	createQueryKey('ingestListRuns', options)

/**
 * List Runs
 *
 * The most recent import runs, newest first.
 */
export const ingestListRunsOptions = (options?: Options<IngestListRunsData>) =>
	queryOptions<
		IngestListRunsResponse,
		IngestListRunsError,
		IngestListRunsResponse,
		ReturnType<typeof ingestListRunsQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await IngestService.ingestListRuns({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: ingestListRunsQueryKey(options),
	})

/**
 * Start Ingest
 *
 * Start an import in the background.
 */
export const ingestStartIngestMutation = (
	options?: Partial<Options<IngestStartIngestData>>,
): UseMutationOptions<
	IngestStartIngestResponse,
	IngestStartIngestError,
	Options<IngestStartIngestData>
> => {
	const mutationOptions: UseMutationOptions<
		IngestStartIngestResponse,
		IngestStartIngestError,
		Options<IngestStartIngestData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await IngestService.ingestStartIngest({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const ingestReadRunQueryKey = (options: Options<IngestReadRunData>) =>
	createQueryKey('ingestReadRun', options)

/**
 * Read Run
 *
 * One run with the outcome of every file it touched.
 */
export const ingestReadRunOptions = (options: Options<IngestReadRunData>) =>
	queryOptions<
		IngestReadRunResponse,
		IngestReadRunError,
		IngestReadRunResponse,
		ReturnType<typeof ingestReadRunQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await IngestService.ingestReadRun({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: ingestReadRunQueryKey(options),
	})

/**
 * Create User
 *
 * Create a new user.
 */
export const privateCreateUserMutation = (
	options?: Partial<Options<PrivateCreateUserData>>,
): UseMutationOptions<
	PrivateCreateUserResponse,
	PrivateCreateUserError,
	Options<PrivateCreateUserData>
> => {
	const mutationOptions: UseMutationOptions<
		PrivateCreateUserResponse,
		PrivateCreateUserError,
		Options<PrivateCreateUserData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await PrivateService.privateCreateUser({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}
