FROM mcr.microsoft.com/playwright:v1.58.0-noble

WORKDIR /app

RUN apt-get update && apt-get install -y unzip \
    && rm -rf /var/lib/apt/lists/*

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml /app/

COPY frontend/package.json /app/frontend/

WORKDIR /app/frontend

RUN pnpm install --frozen-lockfile

COPY ./frontend /app/frontend

ARG VITE_API_URL
