services:

  db:
    restart: "no"
    ports:
      - "5432:5432"

  prestart:
    environment:
      - IMPORT_ELA_DATA_FILE=${IMPORT_ELA_DATA_FILE-/app/backend/resources/cde-2025/eladownload2025.xlsx}
      - IMPORT_INDICATORS_SOURCE=${IMPORT_INDICATORS_SOURCE-cde}
      - IMPORT_INDICATORS_PATH=${IMPORT_INDICATORS_PATH-/app/backend/resources/cde-2024}
    volumes:
      - ${IMPORT_RESOURCES_HOST_PATH?You must set a path, like the folder ~/Downloads/resources, for local database importing. It needs to mount the volume to Docker. You can use an empty folder.}:/app/backend/resources:ro

  backend:
    restart: "no"
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: backend/Dockerfile
    command:
      - fastapi
      - dev
      - --host
      - "0.0.0.0"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend
          ignore:
            - .venv
            - app/frontend_dist
        - path: ./backend/pyproject.toml
          action: rebuild

  frontend:
    ports:
      - "5173:5173"
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: build-stage
    command: pnpm --filter frontend dev --host
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    develop:
      watch:
        - path: ./frontend
          action: sync
          target: /app/frontend
          ignore:
            - node_modules
            - dist
