apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: capanel-service
  labels:
    cloud.googleapis.com/location: us-west1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: ca-panel-001:us-west1:capanel-pg
    spec:
      containers:
      - name: frontend
        image: us-west1-docker.pkg.dev/ca-panel-001/capanel-repo/frontend:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
      - name: backend
        image: us-west1-docker.pkg.dev/ca-panel-001/capanel-repo/backend:latest
        env:
        - name: PORT
          value: "8000"
        - name: ENVIRONMENT
          value: "production"
        - name: PROJECT_NAME
          value: "California Accountability Panel"
        - name: SECRET_KEY
          value: "O6lM5GlFK2Uqjj+QDSxXN8jO2XXVNWip"
        - name: FIRST_SUPERUSER
          value: "admin@innovateforcalifornia.com"
        - name: FIRST_SUPERUSER_PASSWORD
          value: "jO1ytU+RRa8+mg=="
        - name: POSTGRES_SERVER
          value: "localhost"
        - name: POSTGRES_USER
          value: "capanel_app"
        - name: POSTGRES_PASSWORD
          value: "DgQ1ACgfl/zaXA=="
        - name: POSTGRES_DB
          value: "capanel"
        - name: CLOUD_SQL_INSTANCE_CONNECTION_NAME
          value: "ca-panel-001:us-west1:capanel-pg"
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
