// This file is auto-generated by @hey-api/openapi-ts

export const AcademicIndicatorCreateSchema = {
	properties: {
		cds: {
			type: 'string',
			maxLength: 14,
			title: 'Cds',
		},
		rtype: {
			type: 'string',
			maxLength: 1,
			title: 'Rtype',
		},
		schoolname: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Schoolname',
		},
		districtname: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Districtname',
		},
		countyname: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Countyname',
		},
		charter_flag: {
			anyOf: [
				{
					type: 'string',
					maxLength: 1,
				},
				{
					type: 'null',
				},
			],
			title: 'Charter Flag',
		},
		coe_flag: {
			anyOf: [
				{
					type: 'string',
					maxLength: 1,
				},
				{
					type: 'null',
				},
			],
			title: 'Coe Flag',
		},
		dass_flag: {
			anyOf: [
				{
					type: 'string',
					maxLength: 1,
				},
				{
					type: 'null',
				},
			],
			title: 'Dass Flag',
		},
		studentgroup: {
			type: 'string',
			maxLength: 10,
			title: 'Studentgroup',
		},
		priordenom: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priordenom',
		},
		priorstatus: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorstatus',
		},
		change: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Change',
		},
		statuslevel: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Statuslevel',
		},
		changelevel: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Changelevel',
		},
		color: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Color',
		},
		box: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Box',
		},
		priornsizemet: {
			anyOf: [
				{
					type: 'string',
					maxLength: 10,
				},
				{
					type: 'null',
				},
			],
			title: 'Priornsizemet',
		},
		accountabilitymet: {
			anyOf: [
				{
					type: 'string',
					maxLength: 10,
				},
				{
					type: 'null',
				},
			],
			title: 'Accountabilitymet',
		},
		hscutpoints: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Hscutpoints',
		},
		pairshare_method: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Pairshare Method',
		},
		priorprate_enrolled: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorprate Enrolled',
		},
		priorprate_tested: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorprate Tested',
		},
		priorprate: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorprate',
		},
		priornumprloss: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priornumprloss',
		},
		priordenom_withoutprloss: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priordenom Withoutprloss',
		},
		priorstatus_withoutprloss: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorstatus Withoutprloss',
		},
		indicator: {
			type: 'string',
			maxLength: 10,
			title: 'Indicator',
			default: 'ELA',
		},
		reportingyear: {
			type: 'string',
			maxLength: 10,
			title: 'Reportingyear',
		},
		priornumer: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priornumer',
		},
		smalldenom: {
			anyOf: [
				{
					type: 'string',
					maxLength: 10,
				},
				{
					type: 'null',
				},
			],
			title: 'Smalldenom',
		},
		priorcertifyflag: {
			anyOf: [
				{
					type: 'string',
					maxLength: 10,
				},
				{
					type: 'null',
				},
			],
			title: 'Priorcertifyflag',
		},
		dataerrorflag: {
			anyOf: [
				{
					type: 'string',
					maxLength: 10,
				},
				{
					type: 'null',
				},
			],
			title: 'Dataerrorflag',
		},
		school_type: {
			anyOf: [
				{
					type: 'string',
					maxLength: 50,
				},
				{
					type: 'null',
				},
			],
			title: 'School Type',
		},
		fiveyrnumer: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Fiveyrnumer',
		},
		priorprogressed: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorprogressed',
		},
		priormaintainpl4: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priormaintainpl4',
		},
		priormaintainoth: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priormaintainoth',
		},
		priordeclined: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priordeclined',
		},
		priorprogressed_alternate: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorprogressed Alternate',
		},
		priormaintainpl3_alternate: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priormaintainpl3 Alternate',
		},
		priornotprognotmain_alternate: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priornotprognotmain Alternate',
		},
		prior95: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Prior95',
		},
		studentgroup_pct: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Studentgroup Pct',
		},
	},
	type: 'object',
	required: ['cds', 'rtype', 'studentgroup', 'reportingyear'],
	title: 'AcademicIndicatorCreate',
} as const

export const AcademicIndicatorPublicSchema = {
	properties: {
		cds: {
			type: 'string',
			maxLength: 14,
			title: 'Cds',
		},
		rtype: {
			type: 'string',
			maxLength: 1,
			title: 'Rtype',
		},
		schoolname: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Schoolname',
		},
		districtname: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Districtname',
		},
		countyname: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Countyname',
		},
		charter_flag: {
			anyOf: [
				{
					type: 'string',
					maxLength: 1,
				},
				{
					type: 'null',
				},
			],
			title: 'Charter Flag',
		},
		coe_flag: {
			anyOf: [
				{
					type: 'string',
					maxLength: 1,
				},
				{
					type: 'null',
				},
			],
			title: 'Coe Flag',
		},
		dass_flag: {
			anyOf: [
				{
					type: 'string',
					maxLength: 1,
				},
				{
					type: 'null',
				},
			],
			title: 'Dass Flag',
		},
		studentgroup: {
			type: 'string',
			maxLength: 10,
			title: 'Studentgroup',
		},
		priordenom: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priordenom',
		},
		priorstatus: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorstatus',
		},
		change: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Change',
		},
		statuslevel: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Statuslevel',
		},
		changelevel: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Changelevel',
		},
		color: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Color',
		},
		box: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Box',
		},
		priornsizemet: {
			anyOf: [
				{
					type: 'string',
					maxLength: 10,
				},
				{
					type: 'null',
				},
			],
			title: 'Priornsizemet',
		},
		accountabilitymet: {
			anyOf: [
				{
					type: 'string',
					maxLength: 10,
				},
				{
					type: 'null',
				},
			],
			title: 'Accountabilitymet',
		},
		hscutpoints: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Hscutpoints',
		},
		pairshare_method: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Pairshare Method',
		},
		priorprate_enrolled: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorprate Enrolled',
		},
		priorprate_tested: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorprate Tested',
		},
		priorprate: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorprate',
		},
		priornumprloss: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priornumprloss',
		},
		priordenom_withoutprloss: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priordenom Withoutprloss',
		},
		priorstatus_withoutprloss: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorstatus Withoutprloss',
		},
		indicator: {
			type: 'string',
			maxLength: 10,
			title: 'Indicator',
			default: 'ELA',
		},
		reportingyear: {
			type: 'string',
			maxLength: 10,
			title: 'Reportingyear',
		},
		priornumer: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priornumer',
		},
		smalldenom: {
			anyOf: [
				{
					type: 'string',
					maxLength: 10,
				},
				{
					type: 'null',
				},
			],
			title: 'Smalldenom',
		},
		priorcertifyflag: {
			anyOf: [
				{
					type: 'string',
					maxLength: 10,
				},
				{
					type: 'null',
				},
			],
			title: 'Priorcertifyflag',
		},
		dataerrorflag: {
			anyOf: [
				{
					type: 'string',
					maxLength: 10,
				},
				{
					type: 'null',
				},
			],
			title: 'Dataerrorflag',
		},
		school_type: {
			anyOf: [
				{
					type: 'string',
					maxLength: 50,
				},
				{
					type: 'null',
				},
			],
			title: 'School Type',
		},
		fiveyrnumer: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Fiveyrnumer',
		},
		priorprogressed: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorprogressed',
		},
		priormaintainpl4: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priormaintainpl4',
		},
		priormaintainoth: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priormaintainoth',
		},
		priordeclined: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priordeclined',
		},
		priorprogressed_alternate: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorprogressed Alternate',
		},
		priormaintainpl3_alternate: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priormaintainpl3 Alternate',
		},
		priornotprognotmain_alternate: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priornotprognotmain Alternate',
		},
		prior95: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Prior95',
		},
		studentgroup_pct: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Studentgroup Pct',
		},
		id: {
			type: 'string',
			format: 'uuid',
			title: 'Id',
		},
		created_at: {
			anyOf: [
				{
					type: 'string',
					format: 'date-time',
				},
				{
					type: 'null',
				},
			],
			title: 'Created At',
		},
	},
	type: 'object',
	required: ['cds', 'rtype', 'studentgroup', 'reportingyear', 'id'],
	title: 'AcademicIndicatorPublic',
} as const

export const AcademicIndicatorUpdateSchema = {
	properties: {
		cds: {
			anyOf: [
				{
					type: 'string',
					maxLength: 14,
				},
				{
					type: 'null',
				},
			],
			title: 'Cds',
		},
		rtype: {
			anyOf: [
				{
					type: 'string',
					maxLength: 1,
				},
				{
					type: 'null',
				},
			],
			title: 'Rtype',
		},
		schoolname: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Schoolname',
		},
		districtname: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Districtname',
		},
		countyname: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Countyname',
		},
		charter_flag: {
			anyOf: [
				{
					type: 'string',
					maxLength: 1,
				},
				{
					type: 'null',
				},
			],
			title: 'Charter Flag',
		},
		coe_flag: {
			anyOf: [
				{
					type: 'string',
					maxLength: 1,
				},
				{
					type: 'null',
				},
			],
			title: 'Coe Flag',
		},
		dass_flag: {
			anyOf: [
				{
					type: 'string',
					maxLength: 1,
				},
				{
					type: 'null',
				},
			],
			title: 'Dass Flag',
		},
		studentgroup: {
			anyOf: [
				{
					type: 'string',
					maxLength: 10,
				},
				{
					type: 'null',
				},
			],
			title: 'Studentgroup',
		},
		priordenom: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priordenom',
		},
		priorstatus: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorstatus',
		},
		change: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Change',
		},
		statuslevel: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Statuslevel',
		},
		changelevel: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Changelevel',
		},
		color: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Color',
		},
		box: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Box',
		},
		priornsizemet: {
			anyOf: [
				{
					type: 'string',
					maxLength: 10,
				},
				{
					type: 'null',
				},
			],
			title: 'Priornsizemet',
		},
		accountabilitymet: {
			anyOf: [
				{
					type: 'string',
					maxLength: 10,
				},
				{
					type: 'null',
				},
			],
			title: 'Accountabilitymet',
		},
		hscutpoints: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Hscutpoints',
		},
		pairshare_method: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Pairshare Method',
		},
		priorprate_enrolled: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorprate Enrolled',
		},
		priorprate_tested: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorprate Tested',
		},
		priorprate: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorprate',
		},
		priornumprloss: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priornumprloss',
		},
		priordenom_withoutprloss: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Priordenom Withoutprloss',
		},
		priorstatus_withoutprloss: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorstatus Withoutprloss',
		},
		indicator: {
			anyOf: [
				{
					type: 'string',
					maxLength: 10,
				},
				{
					type: 'null',
				},
			],
			title: 'Indicator',
		},
		reportingyear: {
			anyOf: [
				{
					type: 'string',
					maxLength: 10,
				},
				{
					type: 'null',
				},
			],
			title: 'Reportingyear',
		},
	},
	type: 'object',
	title: 'AcademicIndicatorUpdate',
} as const

export const AcademicIndicatorsPublicSchema = {
	properties: {
		data: {
			items: {
				$ref: '#/components/schemas/AcademicIndicatorPublic',
			},
			type: 'array',
			title: 'Data',
		},
		count: {
			type: 'integer',
			title: 'Count',
		},
	},
	type: 'object',
	required: ['data', 'count'],
	title: 'AcademicIndicatorsPublic',
} as const

export const Body_login_login_access_tokenSchema = {
	properties: {
		grant_type: {
			anyOf: [
				{
					type: 'string',
					pattern: '^password$',
				},
				{
					type: 'null',
				},
			],
			title: 'Grant Type',
		},
		username: {
			type: 'string',
			title: 'Username',
		},
		password: {
			type: 'string',
			format: 'password',
			title: 'Password',
		},
		scope: {
			type: 'string',
			title: 'Scope',
			default: '',
		},
		client_id: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Client Id',
		},
		client_secret: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			format: 'password',
			title: 'Client Secret',
		},
	},
	type: 'object',
	required: ['username', 'password'],
	title: 'Body_login-login_access_token',
} as const

export const DashboardAggregationSchema = {
	properties: {
		cds: {
			type: 'string',
			title: 'Cds',
		},
		schoolname: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Schoolname',
		},
		districtname: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Districtname',
		},
		countyname: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Countyname',
		},
		studentgroup: {
			type: 'string',
			title: 'Studentgroup',
		},
		currstatus: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Currstatus',
		},
		priorstatus: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorstatus',
		},
		change: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Change',
		},
		statuslevel: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Statuslevel',
		},
		changelevel: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Changelevel',
		},
		color: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Color',
		},
		indicator: {
			type: 'string',
			title: 'Indicator',
		},
		reportingyear: {
			type: 'string',
			title: 'Reportingyear',
		},
	},
	type: 'object',
	required: ['cds', 'studentgroup', 'indicator', 'reportingyear'],
	title: 'DashboardAggregation',
	description: 'Dashboard aggregation response model (legacy single-indicator)',
} as const

export const DashboardSummaryResponseSchema = {
	properties: {
		cds: {
			type: 'string',
			title: 'Cds',
		},
		rtype: {
			type: 'string',
			title: 'Rtype',
		},
		schoolname: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Schoolname',
		},
		districtname: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Districtname',
		},
		countyname: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Countyname',
		},
		charter_flag: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Charter Flag',
		},
		reportingyear: {
			type: 'string',
			title: 'Reportingyear',
		},
		indicators: {
			items: {
				$ref: '#/components/schemas/IndicatorSummary',
			},
			type: 'array',
			title: 'Indicators',
		},
	},
	type: 'object',
	required: ['cds', 'rtype', 'reportingyear', 'indicators'],
	title: 'DashboardSummaryResponse',
	description: 'Response containing all indicators for a school/district/state.',
} as const

export const EquityGroupSummarySchema = {
	properties: {
		studentgroup: {
			type: 'string',
			title: 'Studentgroup',
		},
		statuslevel: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Statuslevel',
		},
		color: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Color',
		},
		currdenom: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Currdenom',
		},
	},
	type: 'object',
	required: ['studentgroup'],
	title: 'EquityGroupSummary',
	description: 'Summary of a student group for the equity report.',
} as const

export const EquityReportResponseSchema = {
	properties: {
		cds: {
			type: 'string',
			title: 'Cds',
		},
		indicator: {
			type: 'string',
			title: 'Indicator',
		},
		reportingyear: {
			type: 'string',
			title: 'Reportingyear',
		},
		color_counts: {
			additionalProperties: {
				type: 'integer',
			},
			type: 'object',
			title: 'Color Counts',
		},
		groups: {
			items: {
				$ref: '#/components/schemas/EquityGroupSummary',
			},
			type: 'array',
			title: 'Groups',
		},
	},
	type: 'object',
	required: ['cds', 'indicator', 'reportingyear', 'color_counts', 'groups'],
	title: 'EquityReportResponse',
	description: 'Response containing student group breakdown for an indicator.',
} as const

export const HTTPValidationErrorSchema = {
	properties: {
		detail: {
			items: {
				$ref: '#/components/schemas/ValidationError',
			},
			type: 'array',
			title: 'Detail',
		},
	},
	type: 'object',
	title: 'HTTPValidationError',
} as const

export const IndicatorSummarySchema = {
	properties: {
		indicator: {
			type: 'string',
			title: 'Indicator',
		},
		currstatus: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Currstatus',
		},
		priorstatus: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Priorstatus',
		},
		change: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Change',
		},
		statuslevel: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Statuslevel',
		},
		changelevel: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Changelevel',
		},
		color: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Color',
		},
		currdenom: {
			anyOf: [
				{
					type: 'integer',
				},
				{
					type: 'null',
				},
			],
			title: 'Currdenom',
		},
	},
	type: 'object',
	required: ['indicator'],
	title: 'IndicatorSummary',
	description:
		'New dashboard summary response models\nSummary of a single indicator for the dashboard.',
} as const

export const ItemCreateSchema = {
	properties: {
		title: {
			type: 'string',
			maxLength: 255,
			minLength: 1,
			title: 'Title',
		},
		description: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Description',
		},
	},
	type: 'object',
	required: ['title'],
	title: 'ItemCreate',
	description: 'Properties to receive on item creation',
} as const

export const ItemPublicSchema = {
	properties: {
		title: {
			type: 'string',
			maxLength: 255,
			minLength: 1,
			title: 'Title',
		},
		description: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Description',
		},
		id: {
			type: 'string',
			format: 'uuid',
			title: 'Id',
		},
		owner_id: {
			type: 'string',
			format: 'uuid',
			title: 'Owner Id',
		},
		created_at: {
			anyOf: [
				{
					type: 'string',
					format: 'date-time',
				},
				{
					type: 'null',
				},
			],
			title: 'Created At',
		},
	},
	type: 'object',
	required: ['title', 'id', 'owner_id'],
	title: 'ItemPublic',
	description: 'Properties to return via API, id is always required',
} as const

export const ItemUpdateSchema = {
	properties: {
		title: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
					minLength: 1,
				},
				{
					type: 'null',
				},
			],
			title: 'Title',
		},
		description: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Description',
		},
	},
	type: 'object',
	title: 'ItemUpdate',
	description: 'Properties to receive on item update',
} as const

export const ItemsPublicSchema = {
	properties: {
		data: {
			items: {
				$ref: '#/components/schemas/ItemPublic',
			},
			type: 'array',
			title: 'Data',
		},
		count: {
			type: 'integer',
			title: 'Count',
		},
	},
	type: 'object',
	required: ['data', 'count'],
	title: 'ItemsPublic',
} as const

export const MessageSchema = {
	properties: {
		message: {
			type: 'string',
			title: 'Message',
		},
	},
	type: 'object',
	required: ['message'],
	title: 'Message',
	description: 'Generic message',
} as const

export const NewPasswordSchema = {
	properties: {
		token: {
			type: 'string',
			title: 'Token',
		},
		new_password: {
			type: 'string',
			maxLength: 128,
			minLength: 8,
			title: 'New Password',
		},
	},
	type: 'object',
	required: ['token', 'new_password'],
	title: 'NewPassword',
} as const

export const PrivateUserCreateSchema = {
	properties: {
		email: {
			type: 'string',
			title: 'Email',
		},
		password: {
			type: 'string',
			title: 'Password',
		},
		full_name: {
			type: 'string',
			title: 'Full Name',
		},
		is_verified: {
			type: 'boolean',
			title: 'Is Verified',
			default: false,
		},
	},
	type: 'object',
	required: ['email', 'password', 'full_name'],
	title: 'PrivateUserCreate',
} as const

export const TokenSchema = {
	properties: {
		access_token: {
			type: 'string',
			title: 'Access Token',
		},
		token_type: {
			type: 'string',
			title: 'Token Type',
			default: 'bearer',
		},
	},
	type: 'object',
	required: ['access_token'],
	title: 'Token',
	description: 'A JSON payload containing the access token.',
} as const

export const UpdatePasswordSchema = {
	properties: {
		current_password: {
			type: 'string',
			maxLength: 128,
			minLength: 8,
			title: 'Current Password',
		},
		new_password: {
			type: 'string',
			maxLength: 128,
			minLength: 8,
			title: 'New Password',
		},
	},
	type: 'object',
	required: ['current_password', 'new_password'],
	title: 'UpdatePassword',
} as const

export const UserCreateSchema = {
	properties: {
		email: {
			type: 'string',
			maxLength: 255,
			format: 'email',
			title: 'Email',
		},
		is_active: {
			type: 'boolean',
			title: 'Is Active',
			default: true,
		},
		is_superuser: {
			type: 'boolean',
			title: 'Is Superuser',
			default: false,
		},
		full_name: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Full Name',
		},
		password: {
			type: 'string',
			maxLength: 128,
			minLength: 8,
			title: 'Password',
		},
	},
	type: 'object',
	required: ['email', 'password'],
	title: 'UserCreate',
} as const

export const UserPreferencesUpdateSchema = {
	properties: {
		last_viewed_cds: {
			anyOf: [
				{
					type: 'string',
					maxLength: 14,
				},
				{
					type: 'null',
				},
			],
			title: 'Last Viewed Cds',
		},
	},
	type: 'object',
	title: 'UserPreferencesUpdate',
	description: 'Request model for updating user preferences.',
} as const

export const UserPublicSchema = {
	properties: {
		email: {
			type: 'string',
			maxLength: 255,
			format: 'email',
			title: 'Email',
		},
		is_active: {
			type: 'boolean',
			title: 'Is Active',
			default: true,
		},
		is_superuser: {
			type: 'boolean',
			title: 'Is Superuser',
			default: false,
		},
		full_name: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Full Name',
		},
		id: {
			type: 'string',
			format: 'uuid',
			title: 'Id',
		},
		created_at: {
			anyOf: [
				{
					type: 'string',
					format: 'date-time',
				},
				{
					type: 'null',
				},
			],
			title: 'Created At',
		},
	},
	type: 'object',
	required: ['email', 'id'],
	title: 'UserPublic',
} as const

export const UserRegisterSchema = {
	properties: {
		email: {
			type: 'string',
			maxLength: 255,
			format: 'email',
			title: 'Email',
		},
		password: {
			type: 'string',
			maxLength: 128,
			minLength: 8,
			title: 'Password',
		},
		full_name: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Full Name',
		},
	},
	type: 'object',
	required: ['email', 'password'],
	title: 'UserRegister',
} as const

export const UserUpdateSchema = {
	properties: {
		email: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
					format: 'email',
				},
				{
					type: 'null',
				},
			],
			title: 'Email',
		},
		is_active: {
			type: 'boolean',
			title: 'Is Active',
			default: true,
		},
		is_superuser: {
			type: 'boolean',
			title: 'Is Superuser',
			default: false,
		},
		full_name: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Full Name',
		},
		password: {
			anyOf: [
				{
					type: 'string',
					maxLength: 128,
					minLength: 8,
				},
				{
					type: 'null',
				},
			],
			title: 'Password',
		},
	},
	type: 'object',
	title: 'UserUpdate',
} as const

export const UserUpdateMeSchema = {
	properties: {
		full_name: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Full Name',
		},
		email: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
					format: 'email',
				},
				{
					type: 'null',
				},
			],
			title: 'Email',
		},
	},
	type: 'object',
	title: 'UserUpdateMe',
} as const

export const UsersPublicSchema = {
	properties: {
		data: {
			items: {
				$ref: '#/components/schemas/UserPublic',
			},
			type: 'array',
			title: 'Data',
		},
		count: {
			type: 'integer',
			title: 'Count',
		},
	},
	type: 'object',
	required: ['data', 'count'],
	title: 'UsersPublic',
} as const

export const ValidationErrorSchema = {
	properties: {
		loc: {
			items: {
				anyOf: [
					{
						type: 'string',
					},
					{
						type: 'integer',
					},
				],
			},
			type: 'array',
			title: 'Location',
		},
		msg: {
			type: 'string',
			title: 'Message',
		},
		type: {
			type: 'string',
			title: 'Error Type',
		},
	},
	type: 'object',
	required: ['loc', 'msg', 'type'],
	title: 'ValidationError',
} as const
