// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

import {
	type Client,
	type ClientMeta,
	type Options as Options2,
	type RequestResult,
	type TDataShape,
	urlSearchParamsBodySerializer,
} from './client'
import { client } from './client.gen'
import type {
	CensusdataCountOfCensusDataData,
	CensusdataCountOfCensusDataErrors,
	CensusdataCountOfCensusDataResponses,
	CensusdataCreateCensusDataData,
	CensusdataCreateCensusDataErrors,
	CensusdataCreateCensusDataResponses,
	CensusdataDeleteCensusDataData,
	CensusdataDeleteCensusDataErrors,
	CensusdataDeleteCensusDataResponses,
	CensusdataReadCensusDataData,
	CensusdataReadCensusDataErrors,
	CensusdataReadCensusDataResponses,
	CensusdataUpdateCensusDataData,
	CensusdataUpdateCensusDataErrors,
	CensusdataUpdateCensusDataResponses,
	DashboardReadCatalogData,
	DashboardReadCatalogErrors,
	DashboardReadCatalogResponses,
	DashboardReadChildrenData,
	DashboardReadChildrenErrors,
	DashboardReadChildrenResponses,
	DashboardReadEnrollmentData,
	DashboardReadEnrollmentErrors,
	DashboardReadEnrollmentResponses,
	DashboardReadGrowthData,
	DashboardReadGrowthErrors,
	DashboardReadGrowthResponses,
	DashboardReadIndicatorData,
	DashboardReadIndicatorErrors,
	DashboardReadIndicatorResponses,
	DashboardReadIndicatorsData,
	DashboardReadIndicatorsErrors,
	DashboardReadIndicatorsResponses,
	DashboardReadTrendData,
	DashboardReadTrendErrors,
	DashboardReadTrendResponses,
	EntitiesReadChildrenData,
	EntitiesReadChildrenErrors,
	EntitiesReadChildrenResponses,
	EntitiesReadEntityData,
	EntitiesReadEntityErrors,
	EntitiesReadEntityResponses,
	EntitiesSearchEntitiesData,
	EntitiesSearchEntitiesErrors,
	EntitiesSearchEntitiesResponses,
	IngestListRunsData,
	IngestListRunsErrors,
	IngestListRunsResponses,
	IngestReadRunData,
	IngestReadRunErrors,
	IngestReadRunResponses,
	IngestStartIngestData,
	IngestStartIngestErrors,
	IngestStartIngestResponses,
	ItemsCreateItemData,
	ItemsCreateItemErrors,
	ItemsCreateItemResponses,
	ItemsDeleteItemData,
	ItemsDeleteItemErrors,
	ItemsDeleteItemResponses,
	ItemsReadItemData,
	ItemsReadItemErrors,
	ItemsReadItemResponses,
	ItemsReadItemsData,
	ItemsReadItemsErrors,
	ItemsReadItemsResponses,
	ItemsUpdateItemData,
	ItemsUpdateItemErrors,
	ItemsUpdateItemResponses,
	LocalIndicatorsReadCatalogData,
	LocalIndicatorsReadCatalogErrors,
	LocalIndicatorsReadCatalogResponses,
	LocalIndicatorsReadLocalIndicatorsData,
	LocalIndicatorsReadLocalIndicatorsErrors,
	LocalIndicatorsReadLocalIndicatorsResponses,
	LocalIndicatorsReadPriorityData,
	LocalIndicatorsReadPriorityErrors,
	LocalIndicatorsReadPriorityResponses,
	LocalIndicatorsReadTrendData,
	LocalIndicatorsReadTrendErrors,
	LocalIndicatorsReadTrendResponses,
	LoginForcePasswordResetForUsersData,
	LoginForcePasswordResetForUsersErrors,
	LoginForcePasswordResetForUsersResponses,
	LoginLoginAccessTokenData,
	LoginLoginAccessTokenErrors,
	LoginLoginAccessTokenResponses,
	LoginRecoverPasswordData,
	LoginRecoverPasswordErrors,
	LoginRecoverPasswordHtmlContentData,
	LoginRecoverPasswordHtmlContentErrors,
	LoginRecoverPasswordHtmlContentResponses,
	LoginRecoverPasswordResponses,
	LoginResetPasswordData,
	LoginResetPasswordErrors,
	LoginResetPasswordResponses,
	LoginTestTokenData,
	LoginTestTokenResponses,
	PrivateCreateUserData,
	PrivateCreateUserErrors,
	PrivateCreateUserResponses,
	ReferenceReadCatalogData,
	ReferenceReadCatalogErrors,
	ReferenceReadCatalogResponses,
	ReportsReadChildResultsData,
	ReportsReadChildResultsErrors,
	ReportsReadChildResultsResponses,
	ReportsReadComparisonData,
	ReportsReadComparisonErrors,
	ReportsReadComparisonResponses,
	ReportsReadGradesData,
	ReportsReadGradesErrors,
	ReportsReadGradesResponses,
	ReportsReadOverviewData,
	ReportsReadOverviewErrors,
	ReportsReadOverviewResponses,
	ReportsReadStudentGroupsData,
	ReportsReadStudentGroupsErrors,
	ReportsReadStudentGroupsResponses,
	ReportsReadSubscoresData,
	ReportsReadSubscoresErrors,
	ReportsReadSubscoresResponses,
	ReportsReadTrendData,
	ReportsReadTrendErrors,
	ReportsReadTrendResponses,
	SchoolsReadSchoolsData,
	SchoolsReadSchoolsErrors,
	SchoolsReadSchoolsResponses,
	SchoolsReadSchoolsSummaryData,
	SchoolsReadSchoolsSummaryErrors,
	SchoolsReadSchoolsSummaryResponses,
	UsersCreateUserData,
	UsersCreateUserErrors,
	UsersCreateUserResponses,
	UsersDeleteUserData,
	UsersDeleteUserErrors,
	UsersDeleteUserMeData,
	UsersDeleteUserMeResponses,
	UsersDeleteUserResponses,
	UsersGetUserPreferencesData,
	UsersGetUserPreferencesResponses,
	UsersReadUserByIdData,
	UsersReadUserByIdErrors,
	UsersReadUserByIdResponses,
	UsersReadUserMeData,
	UsersReadUserMeResponses,
	UsersReadUsersData,
	UsersReadUsersErrors,
	UsersReadUsersResponses,
	UsersRegisterUserData,
	UsersRegisterUserErrors,
	UsersRegisterUserResponses,
	UsersUpdatePasswordMeData,
	UsersUpdatePasswordMeErrors,
	UsersUpdatePasswordMeResponses,
	UsersUpdateUserData,
	UsersUpdateUserErrors,
	UsersUpdateUserMeData,
	UsersUpdateUserMeErrors,
	UsersUpdateUserMeResponses,
	UsersUpdateUserPreferencesData,
	UsersUpdateUserPreferencesErrors,
	UsersUpdateUserPreferencesResponses,
	UsersUpdateUserResponses,
	UtilsHealthCheckData,
	UtilsHealthCheckResponses,
	UtilsTestEmailData,
	UtilsTestEmailErrors,
	UtilsTestEmailResponses,
} from './types.gen'
import {
	zCensusdataCountOfCensusDataQuery,
	zCensusdataCountOfCensusDataResponse,
	zCensusdataCreateCensusDataBody,
	zCensusdataCreateCensusDataResponse,
	zCensusdataDeleteCensusDataPath,
	zCensusdataDeleteCensusDataResponse,
	zCensusdataReadCensusDataPath,
	zCensusdataReadCensusDataResponse,
	zCensusdataUpdateCensusDataBody,
	zCensusdataUpdateCensusDataPath,
	zCensusdataUpdateCensusDataResponse,
	zDashboardReadCatalogQuery,
	zDashboardReadCatalogResponse,
	zDashboardReadChildrenQuery,
	zDashboardReadChildrenResponse,
	zDashboardReadEnrollmentQuery,
	zDashboardReadEnrollmentResponse,
	zDashboardReadGrowthQuery,
	zDashboardReadGrowthResponse,
	zDashboardReadIndicatorQuery,
	zDashboardReadIndicatorResponse,
	zDashboardReadIndicatorsQuery,
	zDashboardReadIndicatorsResponse,
	zDashboardReadTrendQuery,
	zDashboardReadTrendResponse,
	zEntitiesReadChildrenPath,
	zEntitiesReadChildrenQuery,
	zEntitiesReadChildrenResponse,
	zEntitiesReadEntityPath,
	zEntitiesReadEntityResponse,
	zEntitiesSearchEntitiesQuery,
	zEntitiesSearchEntitiesResponse,
	zIngestListRunsQuery,
	zIngestListRunsResponse,
	zIngestReadRunPath,
	zIngestReadRunResponse,
	zIngestStartIngestBody,
	zIngestStartIngestResponse,
	zItemsCreateItemBody,
	zItemsCreateItemResponse,
	zItemsDeleteItemPath,
	zItemsDeleteItemResponse,
	zItemsReadItemPath,
	zItemsReadItemResponse,
	zItemsReadItemsQuery,
	zItemsReadItemsResponse,
	zItemsUpdateItemBody,
	zItemsUpdateItemPath,
	zItemsUpdateItemResponse,
	zLocalIndicatorsReadCatalogQuery,
	zLocalIndicatorsReadCatalogResponse,
	zLocalIndicatorsReadLocalIndicatorsQuery,
	zLocalIndicatorsReadLocalIndicatorsResponse,
	zLocalIndicatorsReadPriorityQuery,
	zLocalIndicatorsReadPriorityResponse,
	zLocalIndicatorsReadTrendQuery,
	zLocalIndicatorsReadTrendResponse,
	zLoginForcePasswordResetForUsersBody,
	zLoginForcePasswordResetForUsersResponse,
	zLoginLoginAccessTokenBody,
	zLoginLoginAccessTokenResponse,
	zLoginRecoverPasswordHtmlContentPath,
	zLoginRecoverPasswordHtmlContentResponse,
	zLoginRecoverPasswordPath,
	zLoginRecoverPasswordResponse,
	zLoginResetPasswordBody,
	zLoginResetPasswordResponse,
	zLoginTestTokenResponse,
	zPrivateCreateUserBody,
	zPrivateCreateUserResponse,
	zReferenceReadCatalogQuery,
	zReferenceReadCatalogResponse,
	zReportsReadChildResultsQuery,
	zReportsReadChildResultsResponse,
	zReportsReadComparisonQuery,
	zReportsReadComparisonResponse,
	zReportsReadGradesQuery,
	zReportsReadGradesResponse,
	zReportsReadOverviewQuery,
	zReportsReadOverviewResponse,
	zReportsReadStudentGroupsQuery,
	zReportsReadStudentGroupsResponse,
	zReportsReadSubscoresQuery,
	zReportsReadSubscoresResponse,
	zReportsReadTrendQuery,
	zReportsReadTrendResponse,
	zSchoolsReadSchoolsQuery,
	zSchoolsReadSchoolsResponse,
	zSchoolsReadSchoolsSummaryQuery,
	zSchoolsReadSchoolsSummaryResponse,
	zUsersCreateUserBody,
	zUsersCreateUserResponse,
	zUsersDeleteUserMeResponse,
	zUsersDeleteUserPath,
	zUsersDeleteUserResponse,
	zUsersGetUserPreferencesResponse,
	zUsersReadUserByIdPath,
	zUsersReadUserByIdResponse,
	zUsersReadUserMeResponse,
	zUsersReadUsersQuery,
	zUsersReadUsersResponse,
	zUsersRegisterUserBody,
	zUsersRegisterUserResponse,
	zUsersUpdatePasswordMeBody,
	zUsersUpdatePasswordMeResponse,
	zUsersUpdateUserBody,
	zUsersUpdateUserMeBody,
	zUsersUpdateUserMeResponse,
	zUsersUpdateUserPath,
	zUsersUpdateUserPreferencesBody,
	zUsersUpdateUserPreferencesResponse,
	zUsersUpdateUserResponse,
	zUtilsHealthCheckResponse,
	zUtilsTestEmailQuery,
	zUtilsTestEmailResponse,
} from './zod.gen'

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
	TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

export class LoginService {
	/**
	 * Login Access Token
	 *
	 * OAuth2 compatible token login, get an access token for future requests.
	 */
	public static loginLoginAccessToken<ThrowOnError extends boolean = false>(
		options: Options<LoginLoginAccessTokenData, ThrowOnError>,
	): RequestResult<LoginLoginAccessTokenResponses, LoginLoginAccessTokenErrors, ThrowOnError> {
		return (options.client ?? client).post<
			LoginLoginAccessTokenResponses,
			LoginLoginAccessTokenErrors,
			ThrowOnError
		>({
			...urlSearchParamsBodySerializer,
			requestValidator: async (data) =>
				await z
					.object({
						body: zLoginLoginAccessTokenBody,
						path: z.never().optional(),
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zLoginLoginAccessTokenResponse.parseAsync(data),
			url: '/api/v1/login/access-token',
			...options,
			headers: {
				'Content-Type': 'application/x-www-form-urlencoded',
				...options.headers,
			},
		})
	}

	/**
	 * Test Token
	 *
	 * Test access token.
	 */
	public static loginTestToken<ThrowOnError extends boolean = false>(
		options?: Options<LoginTestTokenData, ThrowOnError>,
	): RequestResult<LoginTestTokenResponses, unknown, ThrowOnError> {
		return (options?.client ?? client).post<LoginTestTokenResponses, unknown, ThrowOnError>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zLoginTestTokenResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/login/test-token',
			...options,
		})
	}

	/**
	 * Recover Password
	 *
	 * Password recovery. Always return the same response to prevent email enumeration attacks. Only send email if user actually exists.
	 */
	public static loginRecoverPassword<ThrowOnError extends boolean = false>(
		options: Options<LoginRecoverPasswordData, ThrowOnError>,
	): RequestResult<LoginRecoverPasswordResponses, LoginRecoverPasswordErrors, ThrowOnError> {
		return (options.client ?? client).post<
			LoginRecoverPasswordResponses,
			LoginRecoverPasswordErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: zLoginRecoverPasswordPath,
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zLoginRecoverPasswordResponse.parseAsync(data),
			url: '/api/v1/password-recovery/{email}',
			...options,
		})
	}

	/**
	 * Reset Password
	 *
	 * Reset password. Don't reveal that the user doesn't exist - use same error as invalid token.
	 */
	public static loginResetPassword<ThrowOnError extends boolean = false>(
		options: Options<LoginResetPasswordData, ThrowOnError>,
	): RequestResult<LoginResetPasswordResponses, LoginResetPasswordErrors, ThrowOnError> {
		return (options.client ?? client).post<
			LoginResetPasswordResponses,
			LoginResetPasswordErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: zLoginResetPasswordBody,
						path: z.never().optional(),
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zLoginResetPasswordResponse.parseAsync(data),
			url: '/api/v1/reset-password/',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers,
			},
		})
	}

	/**
	 * Recover Password Html Content
	 *
	 * HTML content for password recovery.
	 */
	public static loginRecoverPasswordHtmlContent<ThrowOnError extends boolean = false>(
		options: Options<LoginRecoverPasswordHtmlContentData, ThrowOnError>,
	): RequestResult<
		LoginRecoverPasswordHtmlContentResponses,
		LoginRecoverPasswordHtmlContentErrors,
		ThrowOnError
	> {
		return (options.client ?? client).post<
			LoginRecoverPasswordHtmlContentResponses,
			LoginRecoverPasswordHtmlContentErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: zLoginRecoverPasswordHtmlContentPath,
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) =>
				await zLoginRecoverPasswordHtmlContentResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/password-recovery-html-content/{email}',
			...options,
		})
	}

	/**
	 * Force Password Reset For Users
	 *
	 * Force password reset for a targeted list of users or all active users.
	 */
	public static loginForcePasswordResetForUsers<ThrowOnError extends boolean = false>(
		options: Options<LoginForcePasswordResetForUsersData, ThrowOnError>,
	): RequestResult<
		LoginForcePasswordResetForUsersResponses,
		LoginForcePasswordResetForUsersErrors,
		ThrowOnError
	> {
		return (options.client ?? client).post<
			LoginForcePasswordResetForUsersResponses,
			LoginForcePasswordResetForUsersErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: zLoginForcePasswordResetForUsersBody,
						path: z.never().optional(),
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) =>
				await zLoginForcePasswordResetForUsersResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/login/force-password-reset',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers,
			},
		})
	}
}

export class UsersService {
	/**
	 * Read Users
	 *
	 * Retrieve users.
	 */
	public static usersReadUsers<ThrowOnError extends boolean = false>(
		options?: Options<UsersReadUsersData, ThrowOnError>,
	): RequestResult<UsersReadUsersResponses, UsersReadUsersErrors, ThrowOnError> {
		return (options?.client ?? client).get<
			UsersReadUsersResponses,
			UsersReadUsersErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zUsersReadUsersQuery.optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zUsersReadUsersResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/users/',
			...options,
		})
	}

	/**
	 * Create User
	 *
	 * Create new user.
	 */
	public static usersCreateUser<ThrowOnError extends boolean = false>(
		options: Options<UsersCreateUserData, ThrowOnError>,
	): RequestResult<UsersCreateUserResponses, UsersCreateUserErrors, ThrowOnError> {
		return (options.client ?? client).post<
			UsersCreateUserResponses,
			UsersCreateUserErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: zUsersCreateUserBody,
						path: z.never().optional(),
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zUsersCreateUserResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/users/',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers,
			},
		})
	}

	/**
	 * Delete User Me
	 *
	 * Delete own user.
	 */
	public static usersDeleteUserMe<ThrowOnError extends boolean = false>(
		options?: Options<UsersDeleteUserMeData, ThrowOnError>,
	): RequestResult<UsersDeleteUserMeResponses, unknown, ThrowOnError> {
		return (options?.client ?? client).delete<UsersDeleteUserMeResponses, unknown, ThrowOnError>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zUsersDeleteUserMeResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/users/me',
			...options,
		})
	}

	/**
	 * Read User Me
	 *
	 * Get current user.
	 */
	public static usersReadUserMe<ThrowOnError extends boolean = false>(
		options?: Options<UsersReadUserMeData, ThrowOnError>,
	): RequestResult<UsersReadUserMeResponses, unknown, ThrowOnError> {
		return (options?.client ?? client).get<UsersReadUserMeResponses, unknown, ThrowOnError>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zUsersReadUserMeResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/users/me',
			...options,
		})
	}

	/**
	 * Update User Me
	 *
	 * Update own user.
	 */
	public static usersUpdateUserMe<ThrowOnError extends boolean = false>(
		options: Options<UsersUpdateUserMeData, ThrowOnError>,
	): RequestResult<UsersUpdateUserMeResponses, UsersUpdateUserMeErrors, ThrowOnError> {
		return (options.client ?? client).patch<
			UsersUpdateUserMeResponses,
			UsersUpdateUserMeErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: zUsersUpdateUserMeBody,
						path: z.never().optional(),
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zUsersUpdateUserMeResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/users/me',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers,
			},
		})
	}

	/**
	 * Update Password Me
	 *
	 * Update own password.
	 */
	public static usersUpdatePasswordMe<ThrowOnError extends boolean = false>(
		options: Options<UsersUpdatePasswordMeData, ThrowOnError>,
	): RequestResult<UsersUpdatePasswordMeResponses, UsersUpdatePasswordMeErrors, ThrowOnError> {
		return (options.client ?? client).patch<
			UsersUpdatePasswordMeResponses,
			UsersUpdatePasswordMeErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: zUsersUpdatePasswordMeBody,
						path: z.never().optional(),
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zUsersUpdatePasswordMeResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/users/me/password',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers,
			},
		})
	}

	/**
	 * Get User Preferences
	 *
	 * Get current user's preferences.
	 */
	public static usersGetUserPreferences<ThrowOnError extends boolean = false>(
		options?: Options<UsersGetUserPreferencesData, ThrowOnError>,
	): RequestResult<UsersGetUserPreferencesResponses, unknown, ThrowOnError> {
		return (options?.client ?? client).get<UsersGetUserPreferencesResponses, unknown, ThrowOnError>(
			{
				requestValidator: async (data) =>
					await z
						.object({
							body: z.never().optional(),
							path: z.never().optional(),
							query: z.never().optional(),
						})
						.parseAsync(data),
				responseValidator: async (data) => await zUsersGetUserPreferencesResponse.parseAsync(data),
				security: [{ scheme: 'bearer', type: 'http' }],
				url: '/api/v1/users/me/preferences',
				...options,
			},
		)
	}

	/**
	 * Update User Preferences
	 *
	 * Update own user's preferences.
	 */
	public static usersUpdateUserPreferences<ThrowOnError extends boolean = false>(
		options: Options<UsersUpdateUserPreferencesData, ThrowOnError>,
	): RequestResult<
		UsersUpdateUserPreferencesResponses,
		UsersUpdateUserPreferencesErrors,
		ThrowOnError
	> {
		return (options.client ?? client).patch<
			UsersUpdateUserPreferencesResponses,
			UsersUpdateUserPreferencesErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: zUsersUpdateUserPreferencesBody,
						path: z.never().optional(),
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zUsersUpdateUserPreferencesResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/users/me/preferences',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers,
			},
		})
	}

	/**
	 * Register User
	 *
	 * Create new user without the need to be logged in.
	 */
	public static usersRegisterUser<ThrowOnError extends boolean = false>(
		options: Options<UsersRegisterUserData, ThrowOnError>,
	): RequestResult<UsersRegisterUserResponses, UsersRegisterUserErrors, ThrowOnError> {
		return (options.client ?? client).post<
			UsersRegisterUserResponses,
			UsersRegisterUserErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: zUsersRegisterUserBody,
						path: z.never().optional(),
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zUsersRegisterUserResponse.parseAsync(data),
			url: '/api/v1/users/signup',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers,
			},
		})
	}

	/**
	 * Delete User
	 *
	 * Delete a user.
	 */
	public static usersDeleteUser<ThrowOnError extends boolean = false>(
		options: Options<UsersDeleteUserData, ThrowOnError>,
	): RequestResult<UsersDeleteUserResponses, UsersDeleteUserErrors, ThrowOnError> {
		return (options.client ?? client).delete<
			UsersDeleteUserResponses,
			UsersDeleteUserErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: zUsersDeleteUserPath,
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zUsersDeleteUserResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/users/{user_id}',
			...options,
		})
	}

	/**
	 * Read User By Id
	 *
	 * Get a specific user by id.
	 */
	public static usersReadUserById<ThrowOnError extends boolean = false>(
		options: Options<UsersReadUserByIdData, ThrowOnError>,
	): RequestResult<UsersReadUserByIdResponses, UsersReadUserByIdErrors, ThrowOnError> {
		return (options.client ?? client).get<
			UsersReadUserByIdResponses,
			UsersReadUserByIdErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: zUsersReadUserByIdPath,
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zUsersReadUserByIdResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/users/{user_id}',
			...options,
		})
	}

	/**
	 * Update User
	 *
	 * Update a user.
	 */
	public static usersUpdateUser<ThrowOnError extends boolean = false>(
		options: Options<UsersUpdateUserData, ThrowOnError>,
	): RequestResult<UsersUpdateUserResponses, UsersUpdateUserErrors, ThrowOnError> {
		return (options.client ?? client).patch<
			UsersUpdateUserResponses,
			UsersUpdateUserErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: zUsersUpdateUserBody,
						path: zUsersUpdateUserPath,
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zUsersUpdateUserResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/users/{user_id}',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers,
			},
		})
	}
}

export class UtilsService {
	/**
	 * Test Email
	 *
	 * Test emails.
	 */
	public static utilsTestEmail<ThrowOnError extends boolean = false>(
		options: Options<UtilsTestEmailData, ThrowOnError>,
	): RequestResult<UtilsTestEmailResponses, UtilsTestEmailErrors, ThrowOnError> {
		return (options.client ?? client).post<
			UtilsTestEmailResponses,
			UtilsTestEmailErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zUtilsTestEmailQuery,
					})
					.parseAsync(data),
			responseValidator: async (data) => await zUtilsTestEmailResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/utils/test-email/',
			...options,
		})
	}

	/**
	 * Health Check
	 */
	public static utilsHealthCheck<ThrowOnError extends boolean = false>(
		options?: Options<UtilsHealthCheckData, ThrowOnError>,
	): RequestResult<UtilsHealthCheckResponses, unknown, ThrowOnError> {
		return (options?.client ?? client).get<UtilsHealthCheckResponses, unknown, ThrowOnError>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zUtilsHealthCheckResponse.parseAsync(data),
			url: '/api/v1/utils/health-check/',
			...options,
		})
	}
}

export class ItemsService {
	/**
	 * Read Items
	 *
	 * Retrieve items.
	 */
	public static itemsReadItems<ThrowOnError extends boolean = false>(
		options?: Options<ItemsReadItemsData, ThrowOnError>,
	): RequestResult<ItemsReadItemsResponses, ItemsReadItemsErrors, ThrowOnError> {
		return (options?.client ?? client).get<
			ItemsReadItemsResponses,
			ItemsReadItemsErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zItemsReadItemsQuery.optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zItemsReadItemsResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/items/',
			...options,
		})
	}

	/**
	 * Create Item
	 *
	 * Create new item.
	 */
	public static itemsCreateItem<ThrowOnError extends boolean = false>(
		options: Options<ItemsCreateItemData, ThrowOnError>,
	): RequestResult<ItemsCreateItemResponses, ItemsCreateItemErrors, ThrowOnError> {
		return (options.client ?? client).post<
			ItemsCreateItemResponses,
			ItemsCreateItemErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: zItemsCreateItemBody,
						path: z.never().optional(),
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zItemsCreateItemResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/items/',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers,
			},
		})
	}

	/**
	 * Delete Item
	 *
	 * Delete an item.
	 */
	public static itemsDeleteItem<ThrowOnError extends boolean = false>(
		options: Options<ItemsDeleteItemData, ThrowOnError>,
	): RequestResult<ItemsDeleteItemResponses, ItemsDeleteItemErrors, ThrowOnError> {
		return (options.client ?? client).delete<
			ItemsDeleteItemResponses,
			ItemsDeleteItemErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: zItemsDeleteItemPath,
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zItemsDeleteItemResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/items/{id}',
			...options,
		})
	}

	/**
	 * Read Item
	 *
	 * Get item by ID.
	 */
	public static itemsReadItem<ThrowOnError extends boolean = false>(
		options: Options<ItemsReadItemData, ThrowOnError>,
	): RequestResult<ItemsReadItemResponses, ItemsReadItemErrors, ThrowOnError> {
		return (options.client ?? client).get<
			ItemsReadItemResponses,
			ItemsReadItemErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: zItemsReadItemPath,
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zItemsReadItemResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/items/{id}',
			...options,
		})
	}

	/**
	 * Update Item
	 *
	 * Update an item.
	 */
	public static itemsUpdateItem<ThrowOnError extends boolean = false>(
		options: Options<ItemsUpdateItemData, ThrowOnError>,
	): RequestResult<ItemsUpdateItemResponses, ItemsUpdateItemErrors, ThrowOnError> {
		return (options.client ?? client).put<
			ItemsUpdateItemResponses,
			ItemsUpdateItemErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: zItemsUpdateItemBody,
						path: zItemsUpdateItemPath,
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zItemsUpdateItemResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/items/{id}',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers,
			},
		})
	}
}

export class CensusdataService {
	/**
	 * Count Of Census Data
	 *
	 * Retrieve census data.
	 */
	public static censusdataCountOfCensusData<ThrowOnError extends boolean = false>(
		options?: Options<CensusdataCountOfCensusDataData, ThrowOnError>,
	): RequestResult<
		CensusdataCountOfCensusDataResponses,
		CensusdataCountOfCensusDataErrors,
		ThrowOnError
	> {
		return (options?.client ?? client).get<
			CensusdataCountOfCensusDataResponses,
			CensusdataCountOfCensusDataErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zCensusdataCountOfCensusDataQuery.optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) =>
				await zCensusdataCountOfCensusDataResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/censusdata/',
			...options,
		})
	}

	/**
	 * Create Census Data
	 *
	 * Create new census data.
	 */
	public static censusdataCreateCensusData<ThrowOnError extends boolean = false>(
		options: Options<CensusdataCreateCensusDataData, ThrowOnError>,
	): RequestResult<
		CensusdataCreateCensusDataResponses,
		CensusdataCreateCensusDataErrors,
		ThrowOnError
	> {
		return (options.client ?? client).post<
			CensusdataCreateCensusDataResponses,
			CensusdataCreateCensusDataErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: zCensusdataCreateCensusDataBody,
						path: z.never().optional(),
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zCensusdataCreateCensusDataResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/censusdata/',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers,
			},
		})
	}

	/**
	 * Delete Census Data
	 *
	 * Delete census data by ID.
	 */
	public static censusdataDeleteCensusData<ThrowOnError extends boolean = false>(
		options: Options<CensusdataDeleteCensusDataData, ThrowOnError>,
	): RequestResult<
		CensusdataDeleteCensusDataResponses,
		CensusdataDeleteCensusDataErrors,
		ThrowOnError
	> {
		return (options.client ?? client).delete<
			CensusdataDeleteCensusDataResponses,
			CensusdataDeleteCensusDataErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: zCensusdataDeleteCensusDataPath,
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zCensusdataDeleteCensusDataResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/censusdata/{id}',
			...options,
		})
	}

	/**
	 * Read Census Data
	 *
	 * Get census data by ID.
	 */
	public static censusdataReadCensusData<ThrowOnError extends boolean = false>(
		options: Options<CensusdataReadCensusDataData, ThrowOnError>,
	): RequestResult<
		CensusdataReadCensusDataResponses,
		CensusdataReadCensusDataErrors,
		ThrowOnError
	> {
		return (options.client ?? client).get<
			CensusdataReadCensusDataResponses,
			CensusdataReadCensusDataErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: zCensusdataReadCensusDataPath,
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zCensusdataReadCensusDataResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/censusdata/{id}',
			...options,
		})
	}

	/**
	 * Update Census Data
	 *
	 * Update census data by ID.
	 */
	public static censusdataUpdateCensusData<ThrowOnError extends boolean = false>(
		options: Options<CensusdataUpdateCensusDataData, ThrowOnError>,
	): RequestResult<
		CensusdataUpdateCensusDataResponses,
		CensusdataUpdateCensusDataErrors,
		ThrowOnError
	> {
		return (options.client ?? client).put<
			CensusdataUpdateCensusDataResponses,
			CensusdataUpdateCensusDataErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: zCensusdataUpdateCensusDataBody,
						path: zCensusdataUpdateCensusDataPath,
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zCensusdataUpdateCensusDataResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/censusdata/{id}',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers,
			},
		})
	}
}

export class SchoolsService {
	/**
	 * Read Schools
	 *
	 * Retrieve schools.
	 */
	public static schoolsReadSchools<ThrowOnError extends boolean = false>(
		options?: Options<SchoolsReadSchoolsData, ThrowOnError>,
	): RequestResult<SchoolsReadSchoolsResponses, SchoolsReadSchoolsErrors, ThrowOnError> {
		return (options?.client ?? client).get<
			SchoolsReadSchoolsResponses,
			SchoolsReadSchoolsErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zSchoolsReadSchoolsQuery.optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zSchoolsReadSchoolsResponse.parseAsync(data),
			url: '/api/v1/schools/',
			...options,
		})
	}

	/**
	 * Read Schools Summary
	 *
	 * Retrieve schools with a summarized view.
	 */
	public static schoolsReadSchoolsSummary<ThrowOnError extends boolean = false>(
		options?: Options<SchoolsReadSchoolsSummaryData, ThrowOnError>,
	): RequestResult<
		SchoolsReadSchoolsSummaryResponses,
		SchoolsReadSchoolsSummaryErrors,
		ThrowOnError
	> {
		return (options?.client ?? client).get<
			SchoolsReadSchoolsSummaryResponses,
			SchoolsReadSchoolsSummaryErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zSchoolsReadSchoolsSummaryQuery.optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zSchoolsReadSchoolsSummaryResponse.parseAsync(data),
			url: '/api/v1/schools/summary',
			...options,
		})
	}
}

export class ReferenceService {
	/**
	 * Read Catalog
	 *
	 * Everything needed to populate the report filters for one year.
	 */
	public static referenceReadCatalog<ThrowOnError extends boolean = false>(
		options?: Options<ReferenceReadCatalogData, ThrowOnError>,
	): RequestResult<ReferenceReadCatalogResponses, ReferenceReadCatalogErrors, ThrowOnError> {
		return (options?.client ?? client).get<
			ReferenceReadCatalogResponses,
			ReferenceReadCatalogErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zReferenceReadCatalogQuery.optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zReferenceReadCatalogResponse.parseAsync(data),
			url: '/api/v1/reference/catalog',
			...options,
		})
	}
}

export class EntitiesService {
	/**
	 * Search Entities
	 *
	 * Find entities by name or CDS code.
	 */
	public static entitiesSearchEntities<ThrowOnError extends boolean = false>(
		options?: Options<EntitiesSearchEntitiesData, ThrowOnError>,
	): RequestResult<EntitiesSearchEntitiesResponses, EntitiesSearchEntitiesErrors, ThrowOnError> {
		return (options?.client ?? client).get<
			EntitiesSearchEntitiesResponses,
			EntitiesSearchEntitiesErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zEntitiesSearchEntitiesQuery.optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zEntitiesSearchEntitiesResponse.parseAsync(data),
			url: '/api/v1/entities/search',
			...options,
		})
	}

	/**
	 * Read Entity
	 *
	 * One entity together with the entities it rolls up into.
	 */
	public static entitiesReadEntity<ThrowOnError extends boolean = false>(
		options: Options<EntitiesReadEntityData, ThrowOnError>,
	): RequestResult<EntitiesReadEntityResponses, EntitiesReadEntityErrors, ThrowOnError> {
		return (options.client ?? client).get<
			EntitiesReadEntityResponses,
			EntitiesReadEntityErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: zEntitiesReadEntityPath,
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zEntitiesReadEntityResponse.parseAsync(data),
			url: '/api/v1/entities/{cds_code}',
			...options,
		})
	}

	/**
	 * Read Children
	 *
	 * The entities directly inside this one.
	 */
	public static entitiesReadChildren<ThrowOnError extends boolean = false>(
		options: Options<EntitiesReadChildrenData, ThrowOnError>,
	): RequestResult<EntitiesReadChildrenResponses, EntitiesReadChildrenErrors, ThrowOnError> {
		return (options.client ?? client).get<
			EntitiesReadChildrenResponses,
			EntitiesReadChildrenErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: zEntitiesReadChildrenPath,
						query: zEntitiesReadChildrenQuery.optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zEntitiesReadChildrenResponse.parseAsync(data),
			url: '/api/v1/entities/{cds_code}/children',
			...options,
		})
	}
}

export class ReportsService {
	/**
	 * Read Overview
	 *
	 * Overall results for one entity, year, student group and grade.
	 */
	public static reportsReadOverview<ThrowOnError extends boolean = false>(
		options?: Options<ReportsReadOverviewData, ThrowOnError>,
	): RequestResult<ReportsReadOverviewResponses, ReportsReadOverviewErrors, ThrowOnError> {
		return (options?.client ?? client).get<
			ReportsReadOverviewResponses,
			ReportsReadOverviewErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zReportsReadOverviewQuery.optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zReportsReadOverviewResponse.parseAsync(data),
			url: '/api/v1/reports/overview',
			...options,
		})
	}

	/**
	 * Read Subscores
	 *
	 * The areas, domains and composites reported beneath one test.
	 */
	public static reportsReadSubscores<ThrowOnError extends boolean = false>(
		options: Options<ReportsReadSubscoresData, ThrowOnError>,
	): RequestResult<ReportsReadSubscoresResponses, ReportsReadSubscoresErrors, ThrowOnError> {
		return (options.client ?? client).get<
			ReportsReadSubscoresResponses,
			ReportsReadSubscoresErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zReportsReadSubscoresQuery,
					})
					.parseAsync(data),
			responseValidator: async (data) => await zReportsReadSubscoresResponse.parseAsync(data),
			url: '/api/v1/reports/subscores',
			...options,
		})
	}

	/**
	 * Read Trend
	 *
	 * One cell's results across every year the state reported them.
	 */
	public static reportsReadTrend<ThrowOnError extends boolean = false>(
		options: Options<ReportsReadTrendData, ThrowOnError>,
	): RequestResult<ReportsReadTrendResponses, ReportsReadTrendErrors, ThrowOnError> {
		return (options.client ?? client).get<
			ReportsReadTrendResponses,
			ReportsReadTrendErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zReportsReadTrendQuery,
					})
					.parseAsync(data),
			responseValidator: async (data) => await zReportsReadTrendResponse.parseAsync(data),
			url: '/api/v1/reports/trend',
			...options,
		})
	}

	/**
	 * Read Student Groups
	 *
	 * Every student group's result for one entity, test and grade.
	 */
	public static reportsReadStudentGroups<ThrowOnError extends boolean = false>(
		options: Options<ReportsReadStudentGroupsData, ThrowOnError>,
	): RequestResult<
		ReportsReadStudentGroupsResponses,
		ReportsReadStudentGroupsErrors,
		ThrowOnError
	> {
		return (options.client ?? client).get<
			ReportsReadStudentGroupsResponses,
			ReportsReadStudentGroupsErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zReportsReadStudentGroupsQuery,
					})
					.parseAsync(data),
			responseValidator: async (data) => await zReportsReadStudentGroupsResponse.parseAsync(data),
			url: '/api/v1/reports/student-groups',
			...options,
		})
	}

	/**
	 * Read Grades
	 *
	 * One entity's result for every grade a test reports.
	 */
	public static reportsReadGrades<ThrowOnError extends boolean = false>(
		options: Options<ReportsReadGradesData, ThrowOnError>,
	): RequestResult<ReportsReadGradesResponses, ReportsReadGradesErrors, ThrowOnError> {
		return (options.client ?? client).get<
			ReportsReadGradesResponses,
			ReportsReadGradesErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zReportsReadGradesQuery,
					})
					.parseAsync(data),
			responseValidator: async (data) => await zReportsReadGradesResponse.parseAsync(data),
			url: '/api/v1/reports/grades',
			...options,
		})
	}

	/**
	 * Read Child Results
	 *
	 * Results for the counties, districts or schools inside one entity.
	 */
	public static reportsReadChildResults<ThrowOnError extends boolean = false>(
		options: Options<ReportsReadChildResultsData, ThrowOnError>,
	): RequestResult<ReportsReadChildResultsResponses, ReportsReadChildResultsErrors, ThrowOnError> {
		return (options.client ?? client).get<
			ReportsReadChildResultsResponses,
			ReportsReadChildResultsErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zReportsReadChildResultsQuery,
					})
					.parseAsync(data),
			responseValidator: async (data) => await zReportsReadChildResultsResponse.parseAsync(data),
			url: '/api/v1/reports/children',
			...options,
		})
	}

	/**
	 * Read Comparison
	 *
	 * Side-by-side results for an explicit list of entities.
	 */
	public static reportsReadComparison<ThrowOnError extends boolean = false>(
		options: Options<ReportsReadComparisonData, ThrowOnError>,
	): RequestResult<ReportsReadComparisonResponses, ReportsReadComparisonErrors, ThrowOnError> {
		return (options.client ?? client).get<
			ReportsReadComparisonResponses,
			ReportsReadComparisonErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zReportsReadComparisonQuery,
					})
					.parseAsync(data),
			responseValidator: async (data) => await zReportsReadComparisonResponse.parseAsync(data),
			url: '/api/v1/reports/compare',
			...options,
		})
	}
}

export class DashboardService {
	/**
	 * Read Catalog
	 *
	 * Everything needed to populate the accountability filters.
	 */
	public static dashboardReadCatalog<ThrowOnError extends boolean = false>(
		options?: Options<DashboardReadCatalogData, ThrowOnError>,
	): RequestResult<DashboardReadCatalogResponses, DashboardReadCatalogErrors, ThrowOnError> {
		return (options?.client ?? client).get<
			DashboardReadCatalogResponses,
			DashboardReadCatalogErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zDashboardReadCatalogQuery.optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zDashboardReadCatalogResponse.parseAsync(data),
			url: '/api/v1/dashboard/catalog',
			...options,
		})
	}

	/**
	 * Read Indicators
	 *
	 * Every indicator for one entity -- the Dashboard landing view.
	 */
	public static dashboardReadIndicators<ThrowOnError extends boolean = false>(
		options?: Options<DashboardReadIndicatorsData, ThrowOnError>,
	): RequestResult<DashboardReadIndicatorsResponses, DashboardReadIndicatorsErrors, ThrowOnError> {
		return (options?.client ?? client).get<
			DashboardReadIndicatorsResponses,
			DashboardReadIndicatorsErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zDashboardReadIndicatorsQuery.optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zDashboardReadIndicatorsResponse.parseAsync(data),
			url: '/api/v1/dashboard/indicators',
			...options,
		})
	}

	/**
	 * Read Indicator
	 *
	 * One indicator for one entity, broken out by student group.
	 */
	public static dashboardReadIndicator<ThrowOnError extends boolean = false>(
		options: Options<DashboardReadIndicatorData, ThrowOnError>,
	): RequestResult<DashboardReadIndicatorResponses, DashboardReadIndicatorErrors, ThrowOnError> {
		return (options.client ?? client).get<
			DashboardReadIndicatorResponses,
			DashboardReadIndicatorErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zDashboardReadIndicatorQuery,
					})
					.parseAsync(data),
			responseValidator: async (data) => await zDashboardReadIndicatorResponse.parseAsync(data),
			url: '/api/v1/dashboard/indicator',
			...options,
		})
	}

	/**
	 * Read Trend
	 *
	 * One indicator over time for one entity.
	 */
	public static dashboardReadTrend<ThrowOnError extends boolean = false>(
		options: Options<DashboardReadTrendData, ThrowOnError>,
	): RequestResult<DashboardReadTrendResponses, DashboardReadTrendErrors, ThrowOnError> {
		return (options.client ?? client).get<
			DashboardReadTrendResponses,
			DashboardReadTrendErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zDashboardReadTrendQuery,
					})
					.parseAsync(data),
			responseValidator: async (data) => await zDashboardReadTrendResponse.parseAsync(data),
			url: '/api/v1/dashboard/trend',
			...options,
		})
	}

	/**
	 * Read Children
	 *
	 * The entities inside a district or county, ranked on one indicator.
	 */
	public static dashboardReadChildren<ThrowOnError extends boolean = false>(
		options: Options<DashboardReadChildrenData, ThrowOnError>,
	): RequestResult<DashboardReadChildrenResponses, DashboardReadChildrenErrors, ThrowOnError> {
		return (options.client ?? client).get<
			DashboardReadChildrenResponses,
			DashboardReadChildrenErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zDashboardReadChildrenQuery,
					})
					.parseAsync(data),
			responseValidator: async (data) => await zDashboardReadChildrenResponse.parseAsync(data),
			url: '/api/v1/dashboard/children',
			...options,
		})
	}

	/**
	 * Read Growth
	 *
	 * Growth in ELA and mathematics -- how far students moved.
	 *
	 * Reported for information only.  Growth is not an accountability result and
	 * carries no performance colour.
	 */
	public static dashboardReadGrowth<ThrowOnError extends boolean = false>(
		options?: Options<DashboardReadGrowthData, ThrowOnError>,
	): RequestResult<DashboardReadGrowthResponses, DashboardReadGrowthErrors, ThrowOnError> {
		return (options?.client ?? client).get<
			DashboardReadGrowthResponses,
			DashboardReadGrowthErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zDashboardReadGrowthQuery.optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zDashboardReadGrowthResponse.parseAsync(data),
			url: '/api/v1/dashboard/growth',
			...options,
		})
	}

	/**
	 * Read Enrollment
	 *
	 * Who attends: every student group's share of Census Day enrolment.
	 */
	public static dashboardReadEnrollment<ThrowOnError extends boolean = false>(
		options?: Options<DashboardReadEnrollmentData, ThrowOnError>,
	): RequestResult<DashboardReadEnrollmentResponses, DashboardReadEnrollmentErrors, ThrowOnError> {
		return (options?.client ?? client).get<
			DashboardReadEnrollmentResponses,
			DashboardReadEnrollmentErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zDashboardReadEnrollmentQuery.optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zDashboardReadEnrollmentResponse.parseAsync(data),
			url: '/api/v1/dashboard/enrollment',
			...options,
		})
	}
}

export class LocalIndicatorsService {
	/**
	 * Read Catalog
	 *
	 * Everything needed to populate the local indicator filters.
	 */
	public static localIndicatorsReadCatalog<ThrowOnError extends boolean = false>(
		options?: Options<LocalIndicatorsReadCatalogData, ThrowOnError>,
	): RequestResult<
		LocalIndicatorsReadCatalogResponses,
		LocalIndicatorsReadCatalogErrors,
		ThrowOnError
	> {
		return (options?.client ?? client).get<
			LocalIndicatorsReadCatalogResponses,
			LocalIndicatorsReadCatalogErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zLocalIndicatorsReadCatalogQuery.optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zLocalIndicatorsReadCatalogResponse.parseAsync(data),
			url: '/api/v1/local-indicators/catalog',
			...options,
		})
	}

	/**
	 * Read Local Indicators
	 *
	 * Every priority one LEA reported, for one year.
	 */
	public static localIndicatorsReadLocalIndicators<ThrowOnError extends boolean = false>(
		options?: Options<LocalIndicatorsReadLocalIndicatorsData, ThrowOnError>,
	): RequestResult<
		LocalIndicatorsReadLocalIndicatorsResponses,
		LocalIndicatorsReadLocalIndicatorsErrors,
		ThrowOnError
	> {
		return (options?.client ?? client).get<
			LocalIndicatorsReadLocalIndicatorsResponses,
			LocalIndicatorsReadLocalIndicatorsErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zLocalIndicatorsReadLocalIndicatorsQuery.optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) =>
				await zLocalIndicatorsReadLocalIndicatorsResponse.parseAsync(data),
			url: '/api/v1/local-indicators/',
			...options,
		})
	}

	/**
	 * Read Priority
	 *
	 * One priority in full, including everything the LEA wrote.
	 */
	public static localIndicatorsReadPriority<ThrowOnError extends boolean = false>(
		options: Options<LocalIndicatorsReadPriorityData, ThrowOnError>,
	): RequestResult<
		LocalIndicatorsReadPriorityResponses,
		LocalIndicatorsReadPriorityErrors,
		ThrowOnError
	> {
		return (options.client ?? client).get<
			LocalIndicatorsReadPriorityResponses,
			LocalIndicatorsReadPriorityErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zLocalIndicatorsReadPriorityQuery,
					})
					.parseAsync(data),
			responseValidator: async (data) =>
				await zLocalIndicatorsReadPriorityResponse.parseAsync(data),
			url: '/api/v1/local-indicators/priority',
			...options,
		})
	}

	/**
	 * Read Trend
	 *
	 * One priority across every year the LEA has reported.
	 */
	public static localIndicatorsReadTrend<ThrowOnError extends boolean = false>(
		options: Options<LocalIndicatorsReadTrendData, ThrowOnError>,
	): RequestResult<
		LocalIndicatorsReadTrendResponses,
		LocalIndicatorsReadTrendErrors,
		ThrowOnError
	> {
		return (options.client ?? client).get<
			LocalIndicatorsReadTrendResponses,
			LocalIndicatorsReadTrendErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zLocalIndicatorsReadTrendQuery,
					})
					.parseAsync(data),
			responseValidator: async (data) => await zLocalIndicatorsReadTrendResponse.parseAsync(data),
			url: '/api/v1/local-indicators/trend',
			...options,
		})
	}
}

export class IngestService {
	/**
	 * List Runs
	 *
	 * The most recent import runs, newest first.
	 */
	public static ingestListRuns<ThrowOnError extends boolean = false>(
		options?: Options<IngestListRunsData, ThrowOnError>,
	): RequestResult<IngestListRunsResponses, IngestListRunsErrors, ThrowOnError> {
		return (options?.client ?? client).get<
			IngestListRunsResponses,
			IngestListRunsErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: z.never().optional(),
						query: zIngestListRunsQuery.optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zIngestListRunsResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/ingest/runs',
			...options,
		})
	}

	/**
	 * Start Ingest
	 *
	 * Start an import in the background.
	 */
	public static ingestStartIngest<ThrowOnError extends boolean = false>(
		options: Options<IngestStartIngestData, ThrowOnError>,
	): RequestResult<IngestStartIngestResponses, IngestStartIngestErrors, ThrowOnError> {
		return (options.client ?? client).post<
			IngestStartIngestResponses,
			IngestStartIngestErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: zIngestStartIngestBody,
						path: z.never().optional(),
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zIngestStartIngestResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/ingest/runs',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers,
			},
		})
	}

	/**
	 * Read Run
	 *
	 * One run with the outcome of every file it touched.
	 */
	public static ingestReadRun<ThrowOnError extends boolean = false>(
		options: Options<IngestReadRunData, ThrowOnError>,
	): RequestResult<IngestReadRunResponses, IngestReadRunErrors, ThrowOnError> {
		return (options.client ?? client).get<
			IngestReadRunResponses,
			IngestReadRunErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: z.never().optional(),
						path: zIngestReadRunPath,
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zIngestReadRunResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/v1/ingest/runs/{run_id}',
			...options,
		})
	}
}

export class PrivateService {
	/**
	 * Create User
	 *
	 * Create a new user.
	 */
	public static privateCreateUser<ThrowOnError extends boolean = false>(
		options: Options<PrivateCreateUserData, ThrowOnError>,
	): RequestResult<PrivateCreateUserResponses, PrivateCreateUserErrors, ThrowOnError> {
		return (options.client ?? client).post<
			PrivateCreateUserResponses,
			PrivateCreateUserErrors,
			ThrowOnError
		>({
			requestValidator: async (data) =>
				await z
					.object({
						body: zPrivateCreateUserBody,
						path: z.never().optional(),
						query: z.never().optional(),
					})
					.parseAsync(data),
			responseValidator: async (data) => await zPrivateCreateUserResponse.parseAsync(data),
			url: '/api/v1/private/users/',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers,
			},
		})
	}
}
