// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: `${string}://${string}` | (string & {})
}

/**
 * AcademicIndicatorCreate
 */
export type AcademicIndicatorCreate = {
	/**
	 * County Code
	 */
	county_code?: string | null
	/**
	 * District Code
	 */
	district_code: string
	/**
	 * School Code
	 */
	school_code?: string | null
	/**
	 * Record Type Id
	 */
	record_type_id?: string | null
	/**
	 * Charter Number
	 */
	charter_number?: string | null
	/**
	 * Test Year
	 */
	test_year: string
	/**
	 * Test Type
	 */
	test_type: string
	/**
	 * Test Id
	 */
	test_id: string
	/**
	 * Student Group Id
	 */
	student_group_id: string
	/**
	 * Grade
	 */
	grade: string
	/**
	 * Students Enrolled
	 */
	students_enrolled: string
	/**
	 * Students Tested
	 */
	students_tested: string
	/**
	 * Students Tested With Scores
	 */
	students_tested_with_scores?: string | null
	/**
	 * Overall Mean Scale Score
	 */
	overall_mean_scale_score?: string | null
	/**
	 * Overall Total
	 */
	overall_total?: string | null
	/**
	 * Overall Level 1 Pct
	 */
	overall_level_1_pct?: string | null
	/**
	 * Overall Level 1 Count
	 */
	overall_level_1_count?: string | null
	/**
	 * Overall Level 2 Pct
	 */
	overall_level_2_pct?: string | null
	/**
	 * Overall Level 2 Count
	 */
	overall_level_2_count?: string | null
	/**
	 * Overall Level 3 Pct
	 */
	overall_level_3_pct?: string | null
	/**
	 * Overall Level 3 Count
	 */
	overall_level_3_count?: string | null
	/**
	 * Overall Level 4 Pct
	 */
	overall_level_4_pct?: string | null
	/**
	 * Overall Level 4 Count
	 */
	overall_level_4_count?: string | null
	/**
	 * Overall Met And Above Pct
	 */
	overall_met_and_above_pct?: string | null
	/**
	 * Overall Met And Above Count
	 */
	overall_met_and_above_count?: string | null
	/**
	 * Domain Data
	 */
	domain_data?: {
		[key: string]: unknown
	} | null
}

/**
 * AcademicIndicatorPublic
 */
export type AcademicIndicatorPublic = {
	/**
	 * County Code
	 */
	county_code?: string | null
	/**
	 * District Code
	 */
	district_code: string
	/**
	 * School Code
	 */
	school_code?: string | null
	/**
	 * Record Type Id
	 */
	record_type_id?: string | null
	/**
	 * Charter Number
	 */
	charter_number?: string | null
	/**
	 * Test Year
	 */
	test_year: string
	/**
	 * Test Type
	 */
	test_type: string
	/**
	 * Test Id
	 */
	test_id: string
	/**
	 * Student Group Id
	 */
	student_group_id: string
	/**
	 * Grade
	 */
	grade: string
	/**
	 * Students Enrolled
	 */
	students_enrolled: string
	/**
	 * Students Tested
	 */
	students_tested: string
	/**
	 * Students Tested With Scores
	 */
	students_tested_with_scores?: string | null
	/**
	 * Overall Mean Scale Score
	 */
	overall_mean_scale_score?: string | null
	/**
	 * Overall Total
	 */
	overall_total?: string | null
	/**
	 * Overall Level 1 Pct
	 */
	overall_level_1_pct?: string | null
	/**
	 * Overall Level 1 Count
	 */
	overall_level_1_count?: string | null
	/**
	 * Overall Level 2 Pct
	 */
	overall_level_2_pct?: string | null
	/**
	 * Overall Level 2 Count
	 */
	overall_level_2_count?: string | null
	/**
	 * Overall Level 3 Pct
	 */
	overall_level_3_pct?: string | null
	/**
	 * Overall Level 3 Count
	 */
	overall_level_3_count?: string | null
	/**
	 * Overall Level 4 Pct
	 */
	overall_level_4_pct?: string | null
	/**
	 * Overall Level 4 Count
	 */
	overall_level_4_count?: string | null
	/**
	 * Overall Met And Above Pct
	 */
	overall_met_and_above_pct?: string | null
	/**
	 * Overall Met And Above Count
	 */
	overall_met_and_above_count?: string | null
	/**
	 * Domain Data
	 */
	domain_data?: {
		[key: string]: unknown
	} | null
}

/**
 * AcademicIndicatorsPublic
 */
export type AcademicIndicatorsPublic = {
	/**
	 * Data
	 */
	data: Array<AcademicIndicatorPublic>
	/**
	 * Count
	 */
	count: number
}

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
	/**
	 * Grant Type
	 */
	grant_type?: string | null
	/**
	 * Username
	 */
	username: string
	/**
	 * Password
	 */
	password: string
	/**
	 * Scope
	 */
	scope?: string
	/**
	 * Client Id
	 */
	client_id?: string | null
	/**
	 * Client Secret
	 */
	client_secret?: string | null
}

/**
 * CensusData
 *
 * A simple CensusData model following the same pattern as User.
 */
export type CensusData = {
	/**
	 * Academic Year
	 */
	academic_year: number
	/**
	 * Aggregation Level
	 */
	aggregation_level: string
	/**
	 * County Code
	 */
	county_code: string
	/**
	 * District Code
	 */
	district_code: string
	/**
	 * School Code
	 */
	school_code: string
	/**
	 * County Name
	 */
	county_name: string
	/**
	 * District Name
	 */
	district_name: string
	/**
	 * School Name
	 */
	school_name: string
	/**
	 * Charter
	 */
	charter: string
	/**
	 * Reporting Category
	 */
	reporting_category: string
	/**
	 * Total Enr
	 */
	total_enr?: number
	/**
	 * Gr Tk
	 */
	gr_tk?: number
	/**
	 * Gr Kn
	 */
	gr_kn?: number
	/**
	 * Gr 1
	 */
	gr_1?: number
	/**
	 * Gr 2
	 */
	gr_2?: number
	/**
	 * Gr 3
	 */
	gr_3?: number
	/**
	 * Gr 4
	 */
	gr_4?: number
	/**
	 * Gr 5
	 */
	gr_5?: number
	/**
	 * Gr 6
	 */
	gr_6?: number
	/**
	 * Gr 7
	 */
	gr_7?: number
	/**
	 * Gr 8
	 */
	gr_8?: number
	/**
	 * Gr 9
	 */
	gr_9?: number
	/**
	 * Gr 10
	 */
	gr_10?: number
	/**
	 * Gr 11
	 */
	gr_11?: number
	/**
	 * Gr 12
	 */
	gr_12?: number
	/**
	 * Census Data Id
	 */
	census_data_id?: string
}

/**
 * DashboardAggregation
 *
 * Aggegrated test data for a CDS code.
 */
export type DashboardAggregation = {
	/**
	 * Cds
	 */
	cds: string
	/**
	 * Student Group Id
	 */
	student_group_id: string
	/**
	 * Test Year
	 */
	test_year: string
	/**
	 * Overall Met And Above Pct
	 */
	overall_met_and_above_pct?: string | null
	/**
	 * Overall Mean Scale Score
	 */
	overall_mean_scale_score?: string | null
}

/**
 * DashboardSummaryResponse
 *
 * Response containing multiple tests for a school/district/county.
 */
export type DashboardSummaryResponse = {
	/**
	 * Cds
	 */
	cds: string
	/**
	 * Test Year
	 */
	test_year: string
	/**
	 * Indicators
	 */
	indicators: Array<IndicatorSummary>
}

/**
 * EquityGroupSummary
 *
 * Summary of a student group for the equity report.
 */
export type EquityGroupSummary = {
	/**
	 * Studentgroup
	 */
	studentgroup: string
	/**
	 * Overall Met And Above Pct
	 */
	overall_met_and_above_pct?: string | null
	/**
	 * Students Tested
	 */
	students_tested?: string | null
}

/**
 * EquityReportResponse
 *
 * Response containing student group breakdown for a test.
 */
export type EquityReportResponse = {
	/**
	 * Cds
	 */
	cds: string
	/**
	 * Test Id
	 */
	test_id: string
	/**
	 * Test Year
	 */
	test_year: string
	/**
	 * Groups
	 */
	groups: Array<EquityGroupSummary>
}

/**
 * ForcePasswordResetRequest
 */
export type ForcePasswordResetRequest = {
	/**
	 * Emails
	 */
	emails?: Array<string>
	/**
	 * Include All Active Users
	 */
	include_all_active_users?: boolean
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
	/**
	 * Detail
	 */
	detail?: Array<ValidationError>
}

/**
 * IndicatorSummary
 *
 * Summary of a specific CAASPP test result.
 */
export type IndicatorSummary = {
	/**
	 * Test Id
	 */
	test_id: string
	/**
	 * Test Type
	 */
	test_type: string
	/**
	 * Grade
	 */
	grade: string
	/**
	 * Students Enrolled
	 */
	students_enrolled: string
	/**
	 * Students Tested
	 */
	students_tested: string
	/**
	 * Overall Mean Scale Score
	 */
	overall_mean_scale_score?: string | null
	/**
	 * Overall Met And Above Pct
	 */
	overall_met_and_above_pct?: string | null
}

/**
 * ItemCreate
 *
 * Properties to receive on item creation
 */
export type ItemCreate = {
	/**
	 * Title
	 */
	title: string
	/**
	 * Description
	 */
	description?: string | null
}

/**
 * ItemPublic
 *
 * Properties to return via API, id is always required
 */
export type ItemPublic = {
	/**
	 * Title
	 */
	title: string
	/**
	 * Description
	 */
	description?: string | null
	/**
	 * Id
	 */
	id: string
	/**
	 * Owner Id
	 */
	owner_id: string
	/**
	 * Created At
	 */
	created_at?: string | null
}

/**
 * ItemUpdate
 *
 * Properties to receive on item update
 */
export type ItemUpdate = {
	/**
	 * Title
	 */
	title?: string | null
	/**
	 * Description
	 */
	description?: string | null
}

/**
 * ItemsPublic
 */
export type ItemsPublic = {
	/**
	 * Data
	 */
	data: Array<ItemPublic>
	/**
	 * Count
	 */
	count: number
}

/**
 * Message
 *
 * Generic message
 */
export type Message = {
	/**
	 * Message
	 */
	message: string
}

/**
 * NewPassword
 */
export type NewPassword = {
	/**
	 * Token
	 */
	token: string
	/**
	 * New Password
	 */
	new_password: string
}

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
	/**
	 * Email
	 */
	email: string
	/**
	 * Password
	 */
	password: string
	/**
	 * Full Name
	 */
	full_name: string
	/**
	 * Is Verified
	 */
	is_verified?: boolean
}

/**
 * SchoolPublic
 *
 * Properties to return via API, id is always required
 */
export type SchoolPublic = {
	/**
	 * Cds Code
	 */
	cds_code: string
	/**
	 * Nces Dist
	 */
	nces_dist: string
	/**
	 * Nces School
	 */
	nces_school: string
	/**
	 * School Code
	 */
	school_code: string
	/**
	 * Status Type
	 */
	status_type?: string | null
	/**
	 * County
	 */
	county?: string | null
	/**
	 * District
	 */
	district?: string | null
	/**
	 * School
	 */
	school?: string | null
	/**
	 * Street
	 */
	street?: string | null
	/**
	 * Street Abr
	 */
	street_abr?: string | null
	/**
	 * City
	 */
	city?: string | null
	/**
	 * Zip
	 */
	zip?: string | null
	/**
	 * State
	 */
	state?: string | null
	/**
	 * Mail Street
	 */
	mail_street?: string | null
	/**
	 * Mail Street Abr
	 */
	mail_street_abr?: string | null
	/**
	 * Mail City
	 */
	mail_city?: string | null
	/**
	 * Mail Zip
	 */
	mail_zip?: string | null
	/**
	 * Mail State
	 */
	mail_state?: string | null
	/**
	 * Phone
	 */
	phone?: string | null
	/**
	 * Ext
	 */
	ext?: string | null
	/**
	 * Fax Number
	 */
	fax_number?: string | null
	/**
	 * Website
	 */
	website?: string | null
	/**
	 * Open Date
	 */
	open_date?: string | null
	/**
	 * Closed Date
	 */
	closed_date?: string | null
	/**
	 * Charter
	 */
	charter?: string | null
	/**
	 * Charter Num
	 */
	charter_num?: string | null
	/**
	 * Funding Type
	 */
	funding_type?: string | null
	/**
	 * Doc
	 */
	doc?: string | null
	/**
	 * Doc Type
	 */
	doc_type?: string | null
	/**
	 * Soc
	 */
	soc?: string | null
	/**
	 * Soc Type
	 */
	soc_type?: string | null
	/**
	 * Edops Code
	 */
	edops_code?: string | null
	/**
	 * Edops Name
	 */
	edops_name?: string | null
	/**
	 * Eil Code
	 */
	eil_code?: string | null
	/**
	 * Eil Name
	 */
	eil_name?: string | null
	/**
	 * Gs Offered
	 */
	gs_offered?: string | null
	/**
	 * Gs Served
	 */
	gs_served?: string | null
	/**
	 * Virtual
	 */
	virtual?: string | null
	/**
	 * Magnet
	 */
	magnet?: string | null
	/**
	 * Year Round Yn
	 */
	year_round_yn?: string | null
	/**
	 * Federal Dfc District Id
	 */
	federal_dfc_district_id?: string | null
	/**
	 * Latitude
	 */
	latitude?: number | null
	/**
	 * Longitude
	 */
	longitude?: number | null
	/**
	 * Adm Fname
	 */
	adm_fname?: string | null
	/**
	 * Adm Lname
	 */
	adm_lname?: string | null
	/**
	 * Last Up Date
	 */
	last_up_date?: string | null
	/**
	 * Multilingual
	 */
	multilingual?: string | null
	/**
	 * Id
	 */
	id: string
}

/**
 * SchoolSummary
 *
 * Properties for a refined school view.
 */
export type SchoolSummary = {
	/**
	 * Id
	 */
	id: string
	/**
	 * School
	 */
	school?: string | null
	/**
	 * City
	 */
	city?: string | null
	/**
	 * County
	 */
	county?: string | null
	/**
	 * Cds Code
	 */
	cds_code?: string | null
	/**
	 * School Code
	 */
	school_code?: string | null
}

/**
 * SchoolsPublic
 */
export type SchoolsPublic = {
	/**
	 * Data
	 */
	data: Array<SchoolPublic>
	/**
	 * Count
	 */
	count: number
}

/**
 * SchoolsSummary
 */
export type SchoolsSummary = {
	/**
	 * Data
	 */
	data: Array<SchoolSummary>
	/**
	 * Count
	 */
	count: number
}

/**
 * Token
 *
 * A JSON payload containing the access token.
 */
export type Token = {
	/**
	 * Access Token
	 */
	access_token: string
	/**
	 * Token Type
	 */
	token_type?: string
}

/**
 * UpdatePassword
 */
export type UpdatePassword = {
	/**
	 * Current Password
	 */
	current_password: string
	/**
	 * New Password
	 */
	new_password: string
}

/**
 * UserCreate
 */
export type UserCreate = {
	/**
	 * Email
	 */
	email: string
	/**
	 * Is Active
	 */
	is_active?: boolean
	/**
	 * Is Superuser
	 */
	is_superuser?: boolean
	/**
	 * Full Name
	 */
	full_name?: string | null
	/**
	 * Password
	 */
	password: string
}

/**
 * UserPreferencesUpdate
 *
 * Request model for updating user preferences.
 */
export type UserPreferencesUpdate = {
	/**
	 * Last Viewed Cds
	 */
	last_viewed_cds?: string | null
}

/**
 * UserPublic
 */
export type UserPublic = {
	/**
	 * Email
	 */
	email: string
	/**
	 * Is Active
	 */
	is_active?: boolean
	/**
	 * Is Superuser
	 */
	is_superuser?: boolean
	/**
	 * Full Name
	 */
	full_name?: string | null
	/**
	 * Id
	 */
	id: string
	/**
	 * Created At
	 */
	created_at?: string | null
	/**
	 * Force Password Reset
	 */
	force_password_reset?: boolean
}

/**
 * UserRegister
 */
export type UserRegister = {
	/**
	 * Email
	 */
	email: string
	/**
	 * Password
	 */
	password: string
	/**
	 * Full Name
	 */
	full_name?: string | null
}

/**
 * UserUpdate
 */
export type UserUpdate = {
	/**
	 * Email
	 */
	email?: string | null
	/**
	 * Is Active
	 */
	is_active?: boolean
	/**
	 * Is Superuser
	 */
	is_superuser?: boolean
	/**
	 * Full Name
	 */
	full_name?: string | null
	/**
	 * Password
	 */
	password?: string | null
	/**
	 * Force Password Reset
	 */
	force_password_reset?: boolean | null
}

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
	/**
	 * Full Name
	 */
	full_name?: string | null
	/**
	 * Email
	 */
	email?: string | null
}

/**
 * UsersPublic
 */
export type UsersPublic = {
	/**
	 * Data
	 */
	data: Array<UserPublic>
	/**
	 * Count
	 */
	count: number
}

/**
 * ValidationError
 */
export type ValidationError = {
	/**
	 * Location
	 */
	loc: Array<string | number>
	/**
	 * Message
	 */
	msg: string
	/**
	 * Error Type
	 */
	type: string
	/**
	 * Input
	 */
	input?: unknown
	/**
	 * Context
	 */
	ctx?: {
		[key: string]: unknown
	}
}

export type LoginLoginAccessTokenData = {
	body: BodyLoginLoginAccessToken
	path?: never
	query?: never
	url: '/api/v1/login/access-token'
}

export type LoginLoginAccessTokenErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type LoginLoginAccessTokenError =
	LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors]

export type LoginLoginAccessTokenResponses = {
	/**
	 * Successful Response
	 */
	200: Token
}

export type LoginLoginAccessTokenResponse =
	LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses]

export type LoginTestTokenData = {
	body?: never
	path?: never
	query?: never
	url: '/api/v1/login/test-token'
}

export type LoginTestTokenResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses]

export type LoginRecoverPasswordData = {
	body?: never
	path: {
		/**
		 * Email
		 */
		email: string
	}
	query?: never
	url: '/api/v1/password-recovery/{email}'
}

export type LoginRecoverPasswordErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors]

export type LoginRecoverPasswordResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type LoginRecoverPasswordResponse =
	LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses]

export type LoginResetPasswordData = {
	body: NewPassword
	path?: never
	query?: never
	url: '/api/v1/reset-password/'
}

export type LoginResetPasswordErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors]

export type LoginResetPasswordResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type LoginResetPasswordResponse =
	LoginResetPasswordResponses[keyof LoginResetPasswordResponses]

export type LoginRecoverPasswordHtmlContentData = {
	body?: never
	path: {
		/**
		 * Email
		 */
		email: string
	}
	query?: never
	url: '/api/v1/password-recovery-html-content/{email}'
}

export type LoginRecoverPasswordHtmlContentErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type LoginRecoverPasswordHtmlContentError =
	LoginRecoverPasswordHtmlContentErrors[keyof LoginRecoverPasswordHtmlContentErrors]

export type LoginRecoverPasswordHtmlContentResponses = {
	/**
	 * Successful Response
	 */
	200: string
}

export type LoginRecoverPasswordHtmlContentResponse =
	LoginRecoverPasswordHtmlContentResponses[keyof LoginRecoverPasswordHtmlContentResponses]

export type LoginForcePasswordResetForUsersData = {
	body: ForcePasswordResetRequest
	path?: never
	query?: never
	url: '/api/v1/login/force-password-reset'
}

export type LoginForcePasswordResetForUsersErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type LoginForcePasswordResetForUsersError =
	LoginForcePasswordResetForUsersErrors[keyof LoginForcePasswordResetForUsersErrors]

export type LoginForcePasswordResetForUsersResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type LoginForcePasswordResetForUsersResponse =
	LoginForcePasswordResetForUsersResponses[keyof LoginForcePasswordResetForUsersResponses]

export type UsersReadUsersData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Skip
		 */
		skip?: number
		/**
		 * Limit
		 */
		limit?: number
	}
	url: '/api/v1/users/'
}

export type UsersReadUsersErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors]

export type UsersReadUsersResponses = {
	/**
	 * Successful Response
	 */
	200: UsersPublic
}

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses]

export type UsersCreateUserData = {
	body: UserCreate
	path?: never
	query?: never
	url: '/api/v1/users/'
}

export type UsersCreateUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors]

export type UsersCreateUserResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses]

export type UsersDeleteUserMeData = {
	body?: never
	path?: never
	query?: never
	url: '/api/v1/users/me'
}

export type UsersDeleteUserMeResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses]

export type UsersReadUserMeData = {
	body?: never
	path?: never
	query?: never
	url: '/api/v1/users/me'
}

export type UsersReadUserMeResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses]

export type UsersUpdateUserMeData = {
	body: UserUpdateMe
	path?: never
	query?: never
	url: '/api/v1/users/me'
}

export type UsersUpdateUserMeErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors]

export type UsersUpdateUserMeResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses]

export type UsersUpdatePasswordMeData = {
	body: UpdatePassword
	path?: never
	query?: never
	url: '/api/v1/users/me/password'
}

export type UsersUpdatePasswordMeErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersUpdatePasswordMeError =
	UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors]

export type UsersUpdatePasswordMeResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type UsersUpdatePasswordMeResponse =
	UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses]

export type UsersRegisterUserData = {
	body: UserRegister
	path?: never
	query?: never
	url: '/api/v1/users/signup'
}

export type UsersRegisterUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors]

export type UsersRegisterUserResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses]

export type UsersDeleteUserData = {
	body?: never
	path: {
		/**
		 * User Id
		 */
		user_id: string
	}
	query?: never
	url: '/api/v1/users/{user_id}'
}

export type UsersDeleteUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors]

export type UsersDeleteUserResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses]

export type UsersReadUserByIdData = {
	body?: never
	path: {
		/**
		 * User Id
		 */
		user_id: string
	}
	query?: never
	url: '/api/v1/users/{user_id}'
}

export type UsersReadUserByIdErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors]

export type UsersReadUserByIdResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses]

export type UsersUpdateUserData = {
	body: UserUpdate
	path: {
		/**
		 * User Id
		 */
		user_id: string
	}
	query?: never
	url: '/api/v1/users/{user_id}'
}

export type UsersUpdateUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors]

export type UsersUpdateUserResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses]

export type UtilsTestEmailData = {
	body?: never
	path?: never
	query: {
		/**
		 * Email To
		 */
		email_to: string
	}
	url: '/api/v1/utils/test-email/'
}

export type UtilsTestEmailErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UtilsTestEmailError = UtilsTestEmailErrors[keyof UtilsTestEmailErrors]

export type UtilsTestEmailResponses = {
	/**
	 * Successful Response
	 */
	201: Message
}

export type UtilsTestEmailResponse = UtilsTestEmailResponses[keyof UtilsTestEmailResponses]

export type UtilsHealthCheckData = {
	body?: never
	path?: never
	query?: never
	url: '/api/v1/utils/health-check/'
}

export type UtilsHealthCheckResponses = {
	/**
	 * Response Utils-Health Check
	 *
	 * Successful Response
	 */
	200: boolean
}

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses]

export type ItemsReadItemsData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Skip
		 */
		skip?: number
		/**
		 * Limit
		 */
		limit?: number
	}
	url: '/api/v1/items/'
}

export type ItemsReadItemsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ItemsReadItemsError = ItemsReadItemsErrors[keyof ItemsReadItemsErrors]

export type ItemsReadItemsResponses = {
	/**
	 * Successful Response
	 */
	200: ItemsPublic
}

export type ItemsReadItemsResponse = ItemsReadItemsResponses[keyof ItemsReadItemsResponses]

export type ItemsCreateItemData = {
	body: ItemCreate
	path?: never
	query?: never
	url: '/api/v1/items/'
}

export type ItemsCreateItemErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ItemsCreateItemError = ItemsCreateItemErrors[keyof ItemsCreateItemErrors]

export type ItemsCreateItemResponses = {
	/**
	 * Successful Response
	 */
	200: ItemPublic
}

export type ItemsCreateItemResponse = ItemsCreateItemResponses[keyof ItemsCreateItemResponses]

export type ItemsDeleteItemData = {
	body?: never
	path: {
		/**
		 * Id
		 */
		id: string
	}
	query?: never
	url: '/api/v1/items/{id}'
}

export type ItemsDeleteItemErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ItemsDeleteItemError = ItemsDeleteItemErrors[keyof ItemsDeleteItemErrors]

export type ItemsDeleteItemResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type ItemsDeleteItemResponse = ItemsDeleteItemResponses[keyof ItemsDeleteItemResponses]

export type ItemsReadItemData = {
	body?: never
	path: {
		/**
		 * Id
		 */
		id: string
	}
	query?: never
	url: '/api/v1/items/{id}'
}

export type ItemsReadItemErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ItemsReadItemError = ItemsReadItemErrors[keyof ItemsReadItemErrors]

export type ItemsReadItemResponses = {
	/**
	 * Successful Response
	 */
	200: ItemPublic
}

export type ItemsReadItemResponse = ItemsReadItemResponses[keyof ItemsReadItemResponses]

export type ItemsUpdateItemData = {
	body: ItemUpdate
	path: {
		/**
		 * Id
		 */
		id: string
	}
	query?: never
	url: '/api/v1/items/{id}'
}

export type ItemsUpdateItemErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ItemsUpdateItemError = ItemsUpdateItemErrors[keyof ItemsUpdateItemErrors]

export type ItemsUpdateItemResponses = {
	/**
	 * Successful Response
	 */
	200: ItemPublic
}

export type ItemsUpdateItemResponse = ItemsUpdateItemResponses[keyof ItemsUpdateItemResponses]

export type CensusdataCountOfCensusDataData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Skip
		 */
		skip?: number
		/**
		 * Limit
		 */
		limit?: number
	}
	url: '/api/v1/censusdata/'
}

export type CensusdataCountOfCensusDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type CensusdataCountOfCensusDataError =
	CensusdataCountOfCensusDataErrors[keyof CensusdataCountOfCensusDataErrors]

export type CensusdataCountOfCensusDataResponses = {
	/**
	 * Response Censusdata-Count Of Census Data
	 *
	 * Successful Response
	 */
	200: Array<CensusData>
}

export type CensusdataCountOfCensusDataResponse =
	CensusdataCountOfCensusDataResponses[keyof CensusdataCountOfCensusDataResponses]

export type CensusdataCreateCensusDataData = {
	body: CensusData
	path?: never
	query?: never
	url: '/api/v1/censusdata/'
}

export type CensusdataCreateCensusDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type CensusdataCreateCensusDataError =
	CensusdataCreateCensusDataErrors[keyof CensusdataCreateCensusDataErrors]

export type CensusdataCreateCensusDataResponses = {
	/**
	 * Successful Response
	 */
	200: CensusData
}

export type CensusdataCreateCensusDataResponse =
	CensusdataCreateCensusDataResponses[keyof CensusdataCreateCensusDataResponses]

export type CensusdataDeleteCensusDataData = {
	body?: never
	path: {
		/**
		 * Id
		 */
		id: string
	}
	query?: never
	url: '/api/v1/censusdata/{id}'
}

export type CensusdataDeleteCensusDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type CensusdataDeleteCensusDataError =
	CensusdataDeleteCensusDataErrors[keyof CensusdataDeleteCensusDataErrors]

export type CensusdataDeleteCensusDataResponses = {
	/**
	 * Successful Response
	 */
	200: CensusData
}

export type CensusdataDeleteCensusDataResponse =
	CensusdataDeleteCensusDataResponses[keyof CensusdataDeleteCensusDataResponses]

export type CensusdataReadCensusDataData = {
	body?: never
	path: {
		/**
		 * Id
		 */
		id: string
	}
	query?: never
	url: '/api/v1/censusdata/{id}'
}

export type CensusdataReadCensusDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type CensusdataReadCensusDataError =
	CensusdataReadCensusDataErrors[keyof CensusdataReadCensusDataErrors]

export type CensusdataReadCensusDataResponses = {
	/**
	 * Successful Response
	 */
	200: CensusData
}

export type CensusdataReadCensusDataResponse =
	CensusdataReadCensusDataResponses[keyof CensusdataReadCensusDataResponses]

export type CensusdataUpdateCensusDataData = {
	body: CensusData
	path: {
		/**
		 * Id
		 */
		id: string
	}
	query?: never
	url: '/api/v1/censusdata/{id}'
}

export type CensusdataUpdateCensusDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type CensusdataUpdateCensusDataError =
	CensusdataUpdateCensusDataErrors[keyof CensusdataUpdateCensusDataErrors]

export type CensusdataUpdateCensusDataResponses = {
	/**
	 * Successful Response
	 */
	200: CensusData
}

export type CensusdataUpdateCensusDataResponse =
	CensusdataUpdateCensusDataResponses[keyof CensusdataUpdateCensusDataResponses]

export type SchoolsReadSchoolsData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Q
		 */
		q?: string | null
		/**
		 * Skip
		 */
		skip?: number
		/**
		 * Limit
		 */
		limit?: number
	}
	url: '/api/v1/schools/'
}

export type SchoolsReadSchoolsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type SchoolsReadSchoolsError = SchoolsReadSchoolsErrors[keyof SchoolsReadSchoolsErrors]

export type SchoolsReadSchoolsResponses = {
	/**
	 * Successful Response
	 */
	200: SchoolsPublic
}

export type SchoolsReadSchoolsResponse =
	SchoolsReadSchoolsResponses[keyof SchoolsReadSchoolsResponses]

export type SchoolsReadSchoolsSummaryData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Q
		 */
		q?: string | null
		/**
		 * Skip
		 */
		skip?: number
		/**
		 * Limit
		 */
		limit?: number
	}
	url: '/api/v1/schools/summary'
}

export type SchoolsReadSchoolsSummaryErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type SchoolsReadSchoolsSummaryError =
	SchoolsReadSchoolsSummaryErrors[keyof SchoolsReadSchoolsSummaryErrors]

export type SchoolsReadSchoolsSummaryResponses = {
	/**
	 * Successful Response
	 */
	200: SchoolsSummary
}

export type SchoolsReadSchoolsSummaryResponse =
	SchoolsReadSchoolsSummaryResponses[keyof SchoolsReadSchoolsSummaryResponses]

export type AcademicIndicatorsReadAcademicIndicatorsData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Skip
		 */
		skip?: number
		/**
		 * Limit
		 */
		limit?: number
		/**
		 * Cds
		 *
		 * Filter by CDS code
		 */
		cds?: string | null
		/**
		 * Studentgroup
		 *
		 * Filter by student group
		 */
		studentgroup?: string | null
		/**
		 * Reportingyear
		 *
		 * Filter by reporting year
		 */
		reportingyear?: string | null
	}
	url: '/api/v1/academic-indicators/'
}

export type AcademicIndicatorsReadAcademicIndicatorsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type AcademicIndicatorsReadAcademicIndicatorsError =
	AcademicIndicatorsReadAcademicIndicatorsErrors[keyof AcademicIndicatorsReadAcademicIndicatorsErrors]

export type AcademicIndicatorsReadAcademicIndicatorsResponses = {
	/**
	 * Successful Response
	 */
	200: AcademicIndicatorsPublic
}

export type AcademicIndicatorsReadAcademicIndicatorsResponse =
	AcademicIndicatorsReadAcademicIndicatorsResponses[keyof AcademicIndicatorsReadAcademicIndicatorsResponses]

export type AcademicIndicatorsCreateAcademicIndicatorData = {
	body: AcademicIndicatorCreate
	path?: never
	query?: never
	url: '/api/v1/academic-indicators/'
}

export type AcademicIndicatorsCreateAcademicIndicatorErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type AcademicIndicatorsCreateAcademicIndicatorError =
	AcademicIndicatorsCreateAcademicIndicatorErrors[keyof AcademicIndicatorsCreateAcademicIndicatorErrors]

export type AcademicIndicatorsCreateAcademicIndicatorResponses = {
	/**
	 * Successful Response
	 */
	200: AcademicIndicatorPublic
}

export type AcademicIndicatorsCreateAcademicIndicatorResponse =
	AcademicIndicatorsCreateAcademicIndicatorResponses[keyof AcademicIndicatorsCreateAcademicIndicatorResponses]

export type AcademicIndicatorsGetDashboardDataData = {
	body?: never
	path?: never
	query: {
		/**
		 * Q
		 *
		 * CDS code to query
		 */
		q: string
	}
	url: '/api/v1/academic-indicators/dashboard'
}

export type AcademicIndicatorsGetDashboardDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type AcademicIndicatorsGetDashboardDataError =
	AcademicIndicatorsGetDashboardDataErrors[keyof AcademicIndicatorsGetDashboardDataErrors]

export type AcademicIndicatorsGetDashboardDataResponses = {
	/**
	 * Successful Response
	 */
	200: DashboardAggregation
}

export type AcademicIndicatorsGetDashboardDataResponse =
	AcademicIndicatorsGetDashboardDataResponses[keyof AcademicIndicatorsGetDashboardDataResponses]

export type AcademicIndicatorsGetDashboardSummaryData = {
	body?: never
	path?: never
	query: {
		/**
		 * Cds
		 *
		 * 14-char CDS code or '00000000000000' for statewide
		 */
		cds: string
		/**
		 * Reportingyear
		 *
		 * Reporting year
		 */
		reportingyear?: string
		/**
		 * Studentgroup
		 *
		 * Student group code
		 */
		studentgroup?: string
	}
	url: '/api/v1/academic-indicators/dashboard/summary'
}

export type AcademicIndicatorsGetDashboardSummaryErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type AcademicIndicatorsGetDashboardSummaryError =
	AcademicIndicatorsGetDashboardSummaryErrors[keyof AcademicIndicatorsGetDashboardSummaryErrors]

export type AcademicIndicatorsGetDashboardSummaryResponses = {
	/**
	 * Successful Response
	 */
	200: DashboardSummaryResponse
}

export type AcademicIndicatorsGetDashboardSummaryResponse =
	AcademicIndicatorsGetDashboardSummaryResponses[keyof AcademicIndicatorsGetDashboardSummaryResponses]

export type AcademicIndicatorsGetEquityReportData = {
	body?: never
	path?: never
	query: {
		/**
		 * Cds
		 *
		 * 14-char CDS code
		 */
		cds: string
		/**
		 * Indicator
		 *
		 * Test ID code (1 for ELA, 2 for MATH, etc.)
		 */
		indicator: string
		/**
		 * Reportingyear
		 *
		 * Reporting year
		 */
		reportingyear?: string
	}
	url: '/api/v1/academic-indicators/dashboard/equity'
}

export type AcademicIndicatorsGetEquityReportErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type AcademicIndicatorsGetEquityReportError =
	AcademicIndicatorsGetEquityReportErrors[keyof AcademicIndicatorsGetEquityReportErrors]

export type AcademicIndicatorsGetEquityReportResponses = {
	/**
	 * Successful Response
	 */
	200: EquityReportResponse
}

export type AcademicIndicatorsGetEquityReportResponse =
	AcademicIndicatorsGetEquityReportResponses[keyof AcademicIndicatorsGetEquityReportResponses]

export type AcademicIndicatorsUpdateUserPreferencesData = {
	body: UserPreferencesUpdate
	path?: never
	query?: never
	url: '/api/v1/academic-indicators/users/me/preferences'
}

export type AcademicIndicatorsUpdateUserPreferencesErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type AcademicIndicatorsUpdateUserPreferencesError =
	AcademicIndicatorsUpdateUserPreferencesErrors[keyof AcademicIndicatorsUpdateUserPreferencesErrors]

export type AcademicIndicatorsUpdateUserPreferencesResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type AcademicIndicatorsUpdateUserPreferencesResponse =
	AcademicIndicatorsUpdateUserPreferencesResponses[keyof AcademicIndicatorsUpdateUserPreferencesResponses]

export type AcademicIndicatorsGetLastViewedCdsData = {
	body?: never
	path?: never
	query?: never
	url: '/api/v1/academic-indicators/users/me/preferences/last-viewed-cds'
}

export type AcademicIndicatorsGetLastViewedCdsResponses = {
	/**
	 * Response Academic-Indicators-Get Last Viewed Cds
	 *
	 * Successful Response
	 */
	200: {
		[key: string]: string | null
	}
}

export type AcademicIndicatorsGetLastViewedCdsResponse =
	AcademicIndicatorsGetLastViewedCdsResponses[keyof AcademicIndicatorsGetLastViewedCdsResponses]

export type AcademicIndicatorsDeleteAcademicIndicatorData = {
	body?: never
	path?: never
	query?: never
	url: '/api/v1/academic-indicators/{id}'
}

export type AcademicIndicatorsDeleteAcademicIndicatorResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type AcademicIndicatorsDeleteAcademicIndicatorResponse =
	AcademicIndicatorsDeleteAcademicIndicatorResponses[keyof AcademicIndicatorsDeleteAcademicIndicatorResponses]

export type AcademicIndicatorsReadAcademicIndicatorData = {
	body?: never
	path?: never
	query?: never
	url: '/api/v1/academic-indicators/{id}'
}

export type AcademicIndicatorsReadAcademicIndicatorResponses = {
	/**
	 * Successful Response
	 */
	200: AcademicIndicatorPublic
}

export type AcademicIndicatorsReadAcademicIndicatorResponse =
	AcademicIndicatorsReadAcademicIndicatorResponses[keyof AcademicIndicatorsReadAcademicIndicatorResponses]

export type AcademicIndicatorsUpdateAcademicIndicatorData = {
	body?: never
	path?: never
	query?: never
	url: '/api/v1/academic-indicators/{id}'
}

export type AcademicIndicatorsUpdateAcademicIndicatorResponses = {
	/**
	 * Successful Response
	 */
	200: AcademicIndicatorPublic
}

export type AcademicIndicatorsUpdateAcademicIndicatorResponse =
	AcademicIndicatorsUpdateAcademicIndicatorResponses[keyof AcademicIndicatorsUpdateAcademicIndicatorResponses]

export type PrivateCreateUserData = {
	body: PrivateUserCreate
	path?: never
	query?: never
	url: '/api/v1/private/users/'
}

export type PrivateCreateUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type PrivateCreateUserError = PrivateCreateUserErrors[keyof PrivateCreateUserErrors]

export type PrivateCreateUserResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type PrivateCreateUserResponse = PrivateCreateUserResponses[keyof PrivateCreateUserResponses]
