// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: `${string}://${string}` | (string & {})
}

/**
 * AssessmentPublic
 *
 * A test, described for one administration year.
 */
export type AssessmentPublic = {
	/**
	 * Testid
	 */
	testId: number
	/**
	 * Code
	 */
	code: string
	program: Program
	/**
	 * Testtype
	 */
	testType: string
	/**
	 * Name
	 */
	name: string
	/**
	 * Shortname
	 */
	shortName: string
	/**
	 * Subject
	 */
	subject: string
	/**
	 * Isalternate
	 */
	isAlternate: boolean
	/**
	 * Sortorder
	 */
	sortOrder: number
	levelScheme: LevelSchemePublic
	/**
	 * Subscores
	 */
	subscores: Array<SubscorePublic>
	/**
	 * Grades
	 */
	grades: Array<string>
	/**
	 * Gradesnote
	 */
	gradesNote?: string | null
}

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
	/**
	 * Grant Type
	 */
	grant_type?: string | null
	/**
	 * Username
	 */
	username: string
	/**
	 * Password
	 */
	password: string
	/**
	 * Scope
	 */
	scope?: string
	/**
	 * Client Id
	 */
	client_id?: string | null
	/**
	 * Client Secret
	 */
	client_secret?: string | null
}

/**
 * Catalog
 *
 * Everything a client needs to build the report controls.
 */
export type Catalog = {
	/**
	 * Testyear
	 */
	testYear: number
	/**
	 * Years
	 */
	years: Array<number>
	/**
	 * Assessments
	 */
	assessments: Array<AssessmentPublic>
	/**
	 * Studentgroups
	 */
	studentGroups: Array<StudentGroupPublic>
	/**
	 * Grades
	 */
	grades: Array<GradePublic>
}

/**
 * CensusData
 */
export type CensusData = {
	/**
	 * Academicyear
	 */
	academicYear: number
	/**
	 * Aggregationlevel
	 */
	aggregationLevel: string
	/**
	 * Cdscode
	 */
	cdsCode: string
	/**
	 * Charter
	 */
	charter?: string | null
	/**
	 * Reportingcategory
	 */
	reportingCategory: string
	/**
	 * Totalenr
	 */
	totalEnr?: number
	/**
	 * Grtk
	 */
	grTk?: number
	/**
	 * Grkn
	 */
	grKn?: number
	/**
	 * Gr1
	 */
	gr1?: number
	/**
	 * Gr2
	 */
	gr2?: number
	/**
	 * Gr3
	 */
	gr3?: number
	/**
	 * Gr4
	 */
	gr4?: number
	/**
	 * Gr5
	 */
	gr5?: number
	/**
	 * Gr6
	 */
	gr6?: number
	/**
	 * Gr7
	 */
	gr7?: number
	/**
	 * Gr8
	 */
	gr8?: number
	/**
	 * Gr9
	 */
	gr9?: number
	/**
	 * Gr10
	 */
	gr10?: number
	/**
	 * Gr11
	 */
	gr11?: number
	/**
	 * Gr12
	 */
	gr12?: number
	/**
	 * Id
	 */
	id?: string
}

/**
 * CharterFunding
 *
 * How a charter school is funded, per the entity ``Type ID``.
 */
export type CharterFunding = 'direct' | 'local'

/**
 * ChildEntityReport
 */
export type ChildEntityReport = {
	entity: EntityPublic
	/**
	 * Testyear
	 */
	testYear: number
	/**
	 * Testid
	 */
	testId: number
	/**
	 * Studentgroupid
	 */
	studentGroupId: number
	/**
	 * Grade
	 */
	grade: string
	childLevel: EntityLevel
	/**
	 * Count
	 */
	count: number
	/**
	 * Data
	 */
	data: Array<ChildEntityResult>
}

/**
 * ChildEntityResult
 *
 * One county, district or school inside the requested entity.
 */
export type ChildEntityResult = {
	entity: EntityPublic
	/**
	 * Studentstested
	 */
	studentsTested?: number | null
	/**
	 * Meanscalescore
	 */
	meanScaleScore?: string | null
	/**
	 * Metorabovepct
	 */
	metOrAbovePct?: string | null
	/**
	 * Suppressed
	 */
	suppressed?: boolean
}

/**
 * ChildIndicatorReport
 *
 * The entities inside a district or county, ranked on one indicator.
 */
export type ChildIndicatorReport = {
	entity: EntityPublic
	/**
	 * Reportingyear
	 */
	reportingYear: number
	/**
	 * Indicatorcode
	 */
	indicatorCode: string
	/**
	 * Studentgroupcode
	 */
	studentGroupCode: string
	/**
	 * Children
	 */
	children: Array<ChildIndicatorResult>
	/**
	 * Count
	 */
	count: number
}

/**
 * ChildIndicatorResult
 *
 * One child entity's result, for ranking within a district or county.
 */
export type ChildIndicatorResult = {
	entity: EntityPublic
	result: IndicatorResult
}

/**
 * CompareReport
 *
 * Side-by-side results for an explicit list of entities.
 */
export type CompareReport = {
	/**
	 * Testyear
	 */
	testYear: number
	/**
	 * Testid
	 */
	testId: number
	/**
	 * Studentgroupid
	 */
	studentGroupId: number
	/**
	 * Grade
	 */
	grade: string
	/**
	 * Entries
	 */
	entries: Array<EntityResults>
}

/**
 * DashboardCatalog
 *
 * Everything needed to populate the accountability filters.
 */
export type DashboardCatalog = {
	/**
	 * Reportingyear
	 */
	reportingYear: number
	/**
	 * Years
	 */
	years: Array<number>
	/**
	 * Indicators
	 */
	indicators: Array<IndicatorPublic>
	/**
	 * Studentgroups
	 */
	studentGroups: Array<StudentGroupCodePublic>
	/**
	 * Colors
	 */
	colors?: {
		[key: string]: string
	}
}

/**
 * EnrollmentGroupPublic
 *
 * One student group's share of an entity's enrolment.
 */
export type EnrollmentGroupPublic = {
	/**
	 * Studentgroupcode
	 */
	studentGroupCode: string
	/**
	 * Name
	 */
	name: string
	/**
	 * Subgrouptotal
	 */
	subgroupTotal?: number | null
	/**
	 * Rate
	 */
	rate?: string | null
}

/**
 * EnrollmentReport
 *
 * Who attends, on the state's Census Day count.
 *
 * Census Day is the first Wednesday in October, so this is a snapshot rather
 * than an average over the year.  Groups overlap -- a student can be counted
 * as Hispanic, an English learner and socioeconomically disadvantaged -- so
 * the rates do not sum to 100.
 */
export type EnrollmentReport = {
	entity: EntityPublic
	/**
	 * Reportingyear
	 */
	reportingYear: number
	/**
	 * Totalenrollment
	 */
	totalEnrollment?: number | null
	/**
	 * Groups
	 */
	groups: Array<EnrollmentGroupPublic>
	/**
	 * Availableyears
	 */
	availableYears: Array<number>
}

/**
 * EntityAncestry
 *
 * An entity together with the entities it rolls up into.
 */
export type EntityAncestry = {
	entity: EntityPublic
	/**
	 * Ancestors
	 */
	ancestors: Array<EntityPublic>
}

/**
 * EntityLevel
 *
 * Reporting level of an entity in a research file.
 */
export type EntityLevel = 'state' | 'county' | 'district' | 'school'

/**
 * EntityList
 */
export type EntityList = {
	/**
	 * Data
	 */
	data: Array<EntityPublic>
	/**
	 * Count
	 */
	count: number
}

/**
 * EntityPublic
 *
 * An entity as the API presents it.
 */
export type EntityPublic = {
	/**
	 * Cdscode
	 */
	cdsCode: string
	/**
	 * Displayname
	 */
	displayName: string
	entityLevel: EntityLevel
	/**
	 * Countycode
	 */
	countyCode: string
	/**
	 * Districtcode
	 */
	districtCode: string
	/**
	 * Schoolcode
	 */
	schoolCode: string
	/**
	 * Countyname
	 */
	countyName?: string | null
	/**
	 * Districtname
	 */
	districtName?: string | null
	/**
	 * Schoolname
	 */
	schoolName?: string | null
	/**
	 * Zipcode
	 */
	zipCode?: string | null
	/**
	 * Ischarter
	 */
	isCharter?: boolean
	charterFunding?: CharterFunding | null
	/**
	 * Parentcdscode
	 */
	parentCdsCode?: string | null
	/**
	 * Firsttestyear
	 */
	firstTestYear?: number | null
	/**
	 * Lasttestyear
	 */
	lastTestYear?: number | null
}

/**
 * EntityResults
 *
 * An entity's results for one or more tests.
 */
export type EntityResults = {
	entity: EntityPublic
	/**
	 * Results
	 */
	results: Array<ResultSummary>
}

/**
 * ForcePasswordResetRequest
 */
export type ForcePasswordResetRequest = {
	/**
	 * Emails
	 */
	emails?: Array<string>
	/**
	 * Includeallactiveusers
	 */
	includeAllActiveUsers?: boolean
}

/**
 * GradePublic
 */
export type GradePublic = {
	/**
	 * Code
	 */
	code: string
	/**
	 * Label
	 */
	label: string
	/**
	 * Sortorder
	 */
	sortOrder: number
	/**
	 * Isaggregate
	 */
	isAggregate: boolean
}

/**
 * GradeReport
 */
export type GradeReport = {
	entity: EntityPublic
	/**
	 * Testyear
	 */
	testYear: number
	/**
	 * Testid
	 */
	testId: number
	/**
	 * Studentgroupid
	 */
	studentGroupId: number
	/**
	 * Grades
	 */
	grades: Array<GradeResult>
}

/**
 * GradeResult
 *
 * One grade's result, for the by-grade report.
 */
export type GradeResult = {
	/**
	 * Grade
	 */
	grade: string
	/**
	 * Label
	 */
	label: string
	/**
	 * Sortorder
	 */
	sortOrder: number
	/**
	 * Studentstested
	 */
	studentsTested?: number | null
	/**
	 * Meanscalescore
	 */
	meanScaleScore?: string | null
	/**
	 * Metorabovepct
	 */
	metOrAbovePct?: string | null
	/**
	 * Suppressed
	 */
	suppressed?: boolean
	/**
	 * Levels
	 */
	levels: Array<LevelResult>
}

/**
 * GrowthReport
 *
 * Growth in ELA and mathematics for one entity and year.
 *
 * Growth is published for information only: the State Board adopted it in
 * July 2025 and it is not used for Local Control Funding Formula
 * eligibility.  ``isInformational`` is always true and clients must say so.
 */
export type GrowthReport = {
	entity: EntityPublic
	/**
	 * Reportingyear
	 */
	reportingYear: number
	/**
	 * Studentgroupcode
	 */
	studentGroupCode: string
	/**
	 * Results
	 */
	results: Array<GrowthResultPublic>
	/**
	 * Availableyears
	 */
	availableYears: Array<number>
	/**
	 * Isinformational
	 */
	isInformational?: boolean
}

/**
 * GrowthResultPublic
 *
 * One subject's growth figure for one entity.
 */
export type GrowthResultPublic = {
	/**
	 * Subject
	 */
	subject: string
	/**
	 * Denominator
	 */
	denominator?: number | null
	/**
	 * Growth
	 */
	growth?: string | null
	/**
	 * Estimatemethod
	 */
	estimateMethod?: string | null
	/**
	 * Estimatemethodname
	 */
	estimateMethodName?: string | null
	/**
	 * Performancecategory
	 */
	performanceCategory?: number | null
	/**
	 * Performancecategoryname
	 */
	performanceCategoryName?: string | null
	/**
	 * Numberimproved
	 */
	numberImproved?: number | null
	/**
	 * Percentimproved
	 */
	percentImproved?: string | null
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
	/**
	 * Detail
	 */
	detail?: Array<ValidationError>
}

/**
 * IndicatorGroupReport
 *
 * One indicator, broken out by student group.
 */
export type IndicatorGroupReport = {
	entity: EntityPublic
	/**
	 * Reportingyear
	 */
	reportingYear: number
	/**
	 * Indicatorcode
	 */
	indicatorCode: string
	/**
	 * Indicatorname
	 */
	indicatorName: string
	allStudents?: IndicatorResult | null
	/**
	 * Groups
	 */
	groups: Array<IndicatorResult>
}

/**
 * IndicatorPublic
 *
 * One of the seven state indicators.
 */
export type IndicatorPublic = {
	/**
	 * Code
	 */
	code: string
	/**
	 * Name
	 */
	name: string
	/**
	 * Shortname
	 */
	shortName: string
	/**
	 * Lowerisbetter
	 */
	lowerIsBetter: boolean
	/**
	 * Unit
	 */
	unit: string
	/**
	 * Sortorder
	 */
	sortOrder: number
	/**
	 * Isinformational
	 */
	isInformational?: boolean
}

/**
 * IndicatorReport
 *
 * Every indicator for one entity and year.
 */
export type IndicatorReport = {
	entity: EntityPublic
	/**
	 * Reportingyear
	 */
	reportingYear: number
	/**
	 * Studentgroupcode
	 */
	studentGroupCode: string
	/**
	 * Results
	 */
	results: Array<IndicatorResult>
	/**
	 * Availableyears
	 */
	availableYears: Array<number>
	/**
	 * Includesprojections
	 */
	includesProjections?: boolean
}

/**
 * IndicatorResult
 *
 * One indicator's result for one entity.
 */
export type IndicatorResult = {
	/**
	 * Indicatorcode
	 */
	indicatorCode: string
	/**
	 * Indicatorname
	 */
	indicatorName: string
	/**
	 * Studentgroupcode
	 */
	studentGroupCode: string
	/**
	 * Variant
	 */
	variant: string
	/**
	 * Currnumerator
	 */
	currNumerator?: number | null
	/**
	 * Currdenominator
	 */
	currDenominator?: number | null
	/**
	 * Currstatus
	 */
	currStatus?: string | null
	/**
	 * Priorstatus
	 */
	priorStatus?: string | null
	/**
	 * Change
	 */
	change?: string | null
	/**
	 * Statuslevel
	 */
	statusLevel?: number | null
	/**
	 * Statuslabel
	 */
	statusLabel?: string | null
	/**
	 * Changelevel
	 */
	changeLevel?: number | null
	/**
	 * Changelabel
	 */
	changeLabel?: string | null
	/**
	 * Color
	 */
	color?: number | null
	/**
	 * Colorname
	 */
	colorName?: string | null
	/**
	 * Box
	 */
	box?: number | null
	/**
	 * Accountabilitymet
	 */
	accountabilityMet?: boolean
	/**
	 * Smalldenominator
	 */
	smallDenominator?: boolean
	/**
	 * Dassflag
	 */
	dassFlag?: boolean
	/**
	 * Isprojected
	 */
	isProjected?: boolean
	/**
	 * Projectionbasis
	 */
	projectionBasis?: string | null
}

/**
 * IndicatorTrendPoint
 *
 * One year of an indicator's history.
 */
export type IndicatorTrendPoint = {
	/**
	 * Reportingyear
	 */
	reportingYear: number
	/**
	 * Currstatus
	 */
	currStatus?: string | null
	/**
	 * Change
	 */
	change?: string | null
	/**
	 * Statuslevel
	 */
	statusLevel?: number | null
	/**
	 * Changelevel
	 */
	changeLevel?: number | null
	/**
	 * Color
	 */
	color?: number | null
	/**
	 * Colorname
	 */
	colorName?: string | null
	/**
	 * Isprojected
	 */
	isProjected?: boolean
}

/**
 * IndicatorTrendReport
 *
 * One indicator over time for one entity.
 */
export type IndicatorTrendReport = {
	entity: EntityPublic
	/**
	 * Indicatorcode
	 */
	indicatorCode: string
	/**
	 * Indicatorname
	 */
	indicatorName: string
	/**
	 * Studentgroupcode
	 */
	studentGroupCode: string
	/**
	 * Points
	 */
	points: Array<IndicatorTrendPoint>
	/**
	 * Missingyears
	 */
	missingYears: Array<number>
}

/**
 * IngestFilePublic
 *
 * The outcome of one file within a run.
 */
export type IngestFilePublic = {
	/**
	 * Sourcekey
	 */
	sourceKey: string
	/**
	 * Program
	 */
	program?: string | null
	/**
	 * Testtype
	 */
	testType?: string | null
	/**
	 * Testyear
	 */
	testYear?: number | null
	status: IngestStatus
	/**
	 * Resultrows
	 */
	resultRows: number
	/**
	 * Subscorerows
	 */
	subscoreRows: number
	/**
	 * Durationseconds
	 */
	durationSeconds?: number | null
	/**
	 * Error
	 */
	error?: string | null
	/**
	 * Loadedat
	 */
	loadedAt?: string | null
}

/**
 * IngestRequest
 *
 * What to import.
 */
export type IngestRequest = {
	/**
	 * Sourceuri
	 */
	sourceUri?: string | null
	/**
	 * Force
	 */
	force?: boolean
	/**
	 * Only
	 */
	only?: Array<string> | null
	/**
	 * Years
	 */
	years?: Array<number> | null
}

/**
 * IngestRunDetail
 *
 * A run together with every file it touched.
 */
export type IngestRunDetail = {
	run: IngestRunPublic
	/**
	 * Files
	 */
	files: Array<IngestFilePublic>
}

/**
 * IngestRunList
 *
 * A page of import runs.
 */
export type IngestRunList = {
	/**
	 * Data
	 */
	data: Array<IngestRunPublic>
	/**
	 * Count
	 */
	count: number
}

/**
 * IngestRunPublic
 *
 * One import run.
 */
export type IngestRunPublic = {
	/**
	 * Id
	 */
	id: string
	/**
	 * Sourceuri
	 */
	sourceUri: string
	status: IngestStatus
	/**
	 * Startedat
	 */
	startedAt: string
	/**
	 * Finishedat
	 */
	finishedAt?: string | null
	/**
	 * Filesseen
	 */
	filesSeen: number
	/**
	 * Filesloaded
	 */
	filesLoaded: number
	/**
	 * Filesskipped
	 */
	filesSkipped: number
	/**
	 * Resultrows
	 */
	resultRows: number
	/**
	 * Subscorerows
	 */
	subscoreRows: number
	/**
	 * Error
	 */
	error?: string | null
}

/**
 * IngestStatus
 *
 * Lifecycle of an ingest run or of one file within it.
 */
export type IngestStatus = 'running' | 'succeeded' | 'failed' | 'skipped'

/**
 * ItemCreate
 */
export type ItemCreate = {
	/**
	 * Title
	 */
	title: string
	/**
	 * Description
	 */
	description?: string | null
}

/**
 * ItemPublic
 */
export type ItemPublic = {
	/**
	 * Title
	 */
	title: string
	/**
	 * Description
	 */
	description?: string | null
	/**
	 * Id
	 */
	id: string
	/**
	 * Ownerid
	 */
	ownerId: string
	/**
	 * Createdat
	 */
	createdAt?: string | null
}

/**
 * ItemUpdate
 */
export type ItemUpdate = {
	/**
	 * Title
	 */
	title?: string | null
	/**
	 * Description
	 */
	description?: string | null
}

/**
 * ItemsPublic
 */
export type ItemsPublic = {
	/**
	 * Data
	 */
	data: Array<ItemPublic>
	/**
	 * Count
	 */
	count: number
}

/**
 * LevelPublic
 *
 * One achievement level of a scheme.
 */
export type LevelPublic = {
	/**
	 * Levelnumber
	 */
	levelNumber: number
	/**
	 * Name
	 */
	name: string
	/**
	 * Shortname
	 */
	shortName: string
	/**
	 * Description
	 */
	description?: string | null
}

/**
 * LevelResult
 *
 * A labelled slice of a distribution.
 */
export type LevelResult = {
	/**
	 * Levelnumber
	 */
	levelNumber: number
	/**
	 * Name
	 */
	name: string
	/**
	 * Shortname
	 */
	shortName: string
	/**
	 * Count
	 */
	count?: number | null
	/**
	 * Pct
	 */
	pct?: string | null
}

/**
 * LevelSchemePublic
 */
export type LevelSchemePublic = {
	/**
	 * Code
	 */
	code: string
	/**
	 * Name
	 */
	name: string
	/**
	 * Levelcount
	 */
	levelCount: number
	/**
	 * Proficientfromlevel
	 */
	proficientFromLevel?: number | null
	/**
	 * Description
	 */
	description?: string | null
	/**
	 * Levels
	 */
	levels: Array<LevelPublic>
}

/**
 * LocalIndicatorCatalog
 *
 * Everything needed to populate the local indicator filters.
 */
export type LocalIndicatorCatalog = {
	/**
	 * Reportingyear
	 */
	reportingYear: number
	/**
	 * Years
	 */
	years: Array<number>
	/**
	 * Priorities
	 */
	priorities: Array<PriorityPublic>
	/**
	 * Performancevalues
	 */
	performanceValues: Array<string>
}

/**
 * LocalIndicatorDetail
 *
 * One priority in full, including everything the LEA wrote.
 */
export type LocalIndicatorDetail = {
	/**
	 * Prioritynumber
	 */
	priorityNumber: number
	/**
	 * Name
	 */
	name: string
	/**
	 * Shortname
	 */
	shortName: string
	/**
	 * Description
	 */
	description?: string | null
	/**
	 * Countyofficeonly
	 */
	countyOfficeOnly?: boolean
	/**
	 * Performance
	 */
	performance?: string | null
	/**
	 * Meetingdate
	 */
	meetingDate?: string | null
	/**
	 * Additionalinfo
	 */
	additionalInfo?: string | null
	/**
	 * Ratings
	 */
	ratings?: {
		[key: string]: number
	}
	/**
	 * Narratives
	 */
	narratives?: Array<{
		[key: string]: string
	}>
}

/**
 * LocalIndicatorReport
 *
 * Every priority for one LEA and year.
 */
export type LocalIndicatorReport = {
	entity: EntityPublic
	reportedBy: EntityPublic
	/**
	 * Reportingyear
	 */
	reportingYear: number
	/**
	 * Priorities
	 */
	priorities: Array<LocalIndicatorSummary>
	/**
	 * Availableyears
	 */
	availableYears: Array<number>
}

/**
 * LocalIndicatorSummary
 *
 * One priority's headline result for one LEA.
 */
export type LocalIndicatorSummary = {
	/**
	 * Prioritynumber
	 */
	priorityNumber: number
	/**
	 * Name
	 */
	name: string
	/**
	 * Shortname
	 */
	shortName: string
	/**
	 * Countyofficeonly
	 */
	countyOfficeOnly?: boolean
	/**
	 * Performance
	 */
	performance?: string | null
	/**
	 * Meetingdate
	 */
	meetingDate?: string | null
	/**
	 * Responsecount
	 */
	responseCount?: number
	/**
	 * Hasnarrative
	 */
	hasNarrative?: boolean
}

/**
 * LocalIndicatorTrendPoint
 */
export type LocalIndicatorTrendPoint = {
	/**
	 * Reportingyear
	 */
	reportingYear: number
	/**
	 * Performance
	 */
	performance?: string | null
	/**
	 * Meetingdate
	 */
	meetingDate?: string | null
}

/**
 * LocalIndicatorTrendReport
 *
 * One priority across every year the LEA has reported.
 */
export type LocalIndicatorTrendReport = {
	entity: EntityPublic
	reportedBy: EntityPublic
	/**
	 * Prioritynumber
	 */
	priorityNumber: number
	/**
	 * Name
	 */
	name: string
	/**
	 * Points
	 */
	points: Array<LocalIndicatorTrendPoint>
}

/**
 * Message
 *
 * A message for an API response.
 */
export type Message = {
	/**
	 * Message
	 */
	message: string
	/**
	 * Success
	 */
	success?: boolean
	/**
	 * Status
	 */
	status?: string | null
	/**
	 * Code
	 */
	code?: string | number | null
}

/**
 * MetOrAboveSource
 *
 * Where the "met or above" figure on a result row came from.
 */
export type MetOrAboveSource = 'published' | 'derived'

/**
 * NewPassword
 */
export type NewPassword = {
	/**
	 * Token
	 */
	token: string
	/**
	 * Newpassword
	 */
	newPassword: string
}

/**
 * OverviewReport
 *
 * The equivalent of the state's "Test Results" landing report.
 */
export type OverviewReport = {
	entity: EntityPublic
	/**
	 * Testyear
	 */
	testYear: number
	/**
	 * Studentgroupid
	 */
	studentGroupId: number
	/**
	 * Grade
	 */
	grade: string
	/**
	 * Schooltype
	 */
	schoolType: string
	/**
	 * Results
	 */
	results: Array<ResultSummary>
	/**
	 * Comparisons
	 */
	comparisons: Array<EntityResults>
}

/**
 * PriorityPublic
 *
 * One of the seven LCFF priorities reported as a local indicator.
 */
export type PriorityPublic = {
	/**
	 * Prioritynumber
	 */
	priorityNumber: number
	/**
	 * Name
	 */
	name: string
	/**
	 * Shortname
	 */
	shortName: string
	/**
	 * Description
	 */
	description?: string | null
	/**
	 * Countyofficeonly
	 */
	countyOfficeOnly?: boolean
	/**
	 * Sortorder
	 */
	sortOrder?: number
}

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
	/**
	 * Email
	 */
	email: string
	/**
	 * Password
	 */
	password: string
	/**
	 * Full Name
	 */
	full_name: string
	/**
	 * Is Verified
	 */
	is_verified?: boolean
}

/**
 * Program
 *
 * The two assessment programs reported by the state's public site.
 */
export type Program = 'CAASPP' | 'ELPAC'

/**
 * ResultSummary
 *
 * One test's overall result for the requested cell.
 *
 * ``suppressed`` means the state withheld the figures because too few
 * students were tested.  Values can also be absent without suppression: the
 * mean scale score is not reported for the "all grades" aggregate, because
 * scale scores are not comparable between grades.
 */
export type ResultSummary = {
	/**
	 * Testid
	 */
	testId: number
	/**
	 * Testcode
	 */
	testCode: string
	/**
	 * Testname
	 */
	testName: string
	/**
	 * Shortname
	 */
	shortName: string
	program: Program
	/**
	 * Subject
	 */
	subject: string
	/**
	 * Grade
	 */
	grade: string
	/**
	 * Studentsenrolled
	 */
	studentsEnrolled?: number | null
	/**
	 * Studentstested
	 */
	studentsTested?: number | null
	/**
	 * Studentstestedwithscores
	 */
	studentsTestedWithScores?: number | null
	/**
	 * Participationrate
	 */
	participationRate?: string | null
	/**
	 * Meanscalescore
	 */
	meanScaleScore?: string | null
	/**
	 * Metorabovecount
	 */
	metOrAboveCount?: number | null
	/**
	 * Metorabovepct
	 */
	metOrAbovePct?: string | null
	metOrAboveSource?: MetOrAboveSource | null
	/**
	 * Overalltotal
	 */
	overallTotal?: number | null
	/**
	 * Suppressed
	 */
	suppressed?: boolean
	/**
	 * Levelschemecode
	 */
	levelSchemeCode: string
	/**
	 * Levels
	 */
	levels: Array<LevelResult>
	/**
	 * Derivedfromchildren
	 */
	derivedFromChildren?: boolean
}

/**
 * SchoolPublic
 */
export type SchoolPublic = {
	/**
	 * Cdscode
	 */
	cdsCode: string
	/**
	 * Ncesdist
	 */
	ncesDist: string
	/**
	 * Ncesschool
	 */
	ncesSchool: string
	/**
	 * Schoolcode
	 */
	schoolCode: string
	/**
	 * Statustype
	 */
	statusType?: string | null
	/**
	 * County
	 */
	county?: string | null
	/**
	 * District
	 */
	district?: string | null
	/**
	 * School
	 */
	school?: string | null
	/**
	 * Street
	 */
	street?: string | null
	/**
	 * Streetabr
	 */
	streetAbr?: string | null
	/**
	 * City
	 */
	city?: string | null
	/**
	 * Zip
	 */
	zip?: string | null
	/**
	 * State
	 */
	state?: string | null
	/**
	 * Mailstreet
	 */
	mailStreet?: string | null
	/**
	 * Mailstreetabr
	 */
	mailStreetAbr?: string | null
	/**
	 * Mailcity
	 */
	mailCity?: string | null
	/**
	 * Mailzip
	 */
	mailZip?: string | null
	/**
	 * Mailstate
	 */
	mailState?: string | null
	/**
	 * Phone
	 */
	phone?: string | null
	/**
	 * Ext
	 */
	ext?: string | null
	/**
	 * Faxnumber
	 */
	faxNumber?: string | null
	/**
	 * Website
	 */
	website?: string | null
	/**
	 * Opendate
	 */
	openDate?: string | null
	/**
	 * Closeddate
	 */
	closedDate?: string | null
	/**
	 * Charter
	 */
	charter?: string | null
	/**
	 * Charternum
	 */
	charterNum?: string | null
	/**
	 * Fundingtype
	 */
	fundingType?: string | null
	/**
	 * Doc
	 */
	doc?: string | null
	/**
	 * Doctype
	 */
	docType?: string | null
	/**
	 * Soc
	 */
	soc?: string | null
	/**
	 * Soctype
	 */
	socType?: string | null
	/**
	 * Edopscode
	 */
	edopsCode?: string | null
	/**
	 * Edopsname
	 */
	edopsName?: string | null
	/**
	 * Eilcode
	 */
	eilCode?: string | null
	/**
	 * Eilname
	 */
	eilName?: string | null
	/**
	 * Gsoffered
	 */
	gsOffered?: string | null
	/**
	 * Gsserved
	 */
	gsServed?: string | null
	/**
	 * Virtual
	 */
	virtual?: string | null
	/**
	 * Magnet
	 */
	magnet?: string | null
	/**
	 * Yearroundyn
	 */
	yearRoundYn?: string | null
	/**
	 * Federaldfcdistrictid
	 */
	federalDfcDistrictId?: string | null
	/**
	 * Latitude
	 */
	latitude?: number | null
	/**
	 * Longitude
	 */
	longitude?: number | null
	/**
	 * Admfname
	 */
	admFname?: string | null
	/**
	 * Admlname
	 */
	admLname?: string | null
	/**
	 * Lastupdate
	 */
	lastUpDate?: string | null
	/**
	 * Multilingual
	 */
	multilingual?: string | null
	/**
	 * Id
	 */
	id: string
}

/**
 * SchoolSummary
 */
export type SchoolSummary = {
	/**
	 * Id
	 */
	id: string
	/**
	 * School
	 */
	school?: string | null
	/**
	 * City
	 */
	city?: string | null
	/**
	 * County
	 */
	county?: string | null
	/**
	 * Cdscode
	 */
	cdsCode?: string | null
	/**
	 * Schoolcode
	 */
	schoolCode?: string | null
}

/**
 * SchoolType
 *
 * The state's charter filter on aggregate reports.
 */
export type SchoolType = 'all' | 'charter' | 'non-charter'

/**
 * SchoolsPublic
 */
export type SchoolsPublic = {
	/**
	 * Data
	 */
	data: Array<SchoolPublic>
	/**
	 * Count
	 */
	count: number
}

/**
 * SchoolsSummary
 */
export type SchoolsSummary = {
	/**
	 * Data
	 */
	data: Array<SchoolSummary>
	/**
	 * Count
	 */
	count: number
}

/**
 * StudentGroupCodePublic
 *
 * A Dashboard student group.
 *
 * These are the state's short codes, which are not the numeric CAASPP and
 * ELPAC group ids used by the assessment reports.
 */
export type StudentGroupCodePublic = {
	/**
	 * Code
	 */
	code: string
	/**
	 * Name
	 */
	name: string
}

/**
 * StudentGroupPublic
 */
export type StudentGroupPublic = {
	program: Program
	/**
	 * Studentgroupid
	 */
	studentGroupId: number
	/**
	 * Code
	 */
	code: string
	/**
	 * Name
	 */
	name: string
	/**
	 * Category
	 */
	category: string
	/**
	 * Sortorder
	 */
	sortOrder: number
}

/**
 * StudentGroupReport
 */
export type StudentGroupReport = {
	entity: EntityPublic
	/**
	 * Testyear
	 */
	testYear: number
	/**
	 * Testid
	 */
	testId: number
	/**
	 * Grade
	 */
	grade: string
	allStudents?: StudentGroupResult | null
	/**
	 * Groups
	 */
	groups: Array<StudentGroupResult>
}

/**
 * StudentGroupResult
 *
 * One student group's result, for the student group comparison report.
 */
export type StudentGroupResult = {
	/**
	 * Studentgroupid
	 */
	studentGroupId: number
	/**
	 * Name
	 */
	name: string
	/**
	 * Category
	 */
	category: string
	/**
	 * Sortorder
	 */
	sortOrder: number
	/**
	 * Studentsenrolled
	 */
	studentsEnrolled?: number | null
	/**
	 * Studentstested
	 */
	studentsTested?: number | null
	/**
	 * Meanscalescore
	 */
	meanScaleScore?: string | null
	/**
	 * Metorabovepct
	 */
	metOrAbovePct?: string | null
	/**
	 * Suppressed
	 */
	suppressed?: boolean
	/**
	 * Levels
	 */
	levels: Array<LevelResult>
}

/**
 * SubscoreKind
 *
 * Kind of reported subscore.
 *
 * ``AREA`` and ``COMPOSITE_AREA`` are Smarter Balanced claim reporting
 * categories; ``DOMAIN`` is used by CAST, CSA and ELPAC; ``COMPOSITE`` is an
 * ELPAC/CSA composite that carries its own mean scale score.
 */
export type SubscoreKind = 'area' | 'composite_area' | 'domain' | 'composite'

/**
 * SubscorePublic
 *
 * An area, domain or composite a test reports in a given year.
 */
export type SubscorePublic = {
	/**
	 * Code
	 */
	code: string
	kind: SubscoreKind
	/**
	 * Name
	 */
	name: string
	/**
	 * Reportsmeanscalescore
	 */
	reportsMeanScaleScore: boolean
	bandScheme: LevelSchemePublic
	/**
	 * Sortorder
	 */
	sortOrder: number
}

/**
 * SubscoreReport
 */
export type SubscoreReport = {
	entity: EntityPublic
	/**
	 * Testyear
	 */
	testYear: number
	/**
	 * Testid
	 */
	testId: number
	/**
	 * Studentgroupid
	 */
	studentGroupId: number
	/**
	 * Grade
	 */
	grade: string
	/**
	 * Subscores
	 */
	subscores: Array<SubscoreResult>
}

/**
 * SubscoreResult
 *
 * One area, domain or composite for the requested cell.
 */
export type SubscoreResult = {
	/**
	 * Code
	 */
	code: string
	kind: SubscoreKind
	/**
	 * Name
	 */
	name: string
	/**
	 * Sortorder
	 */
	sortOrder: number
	/**
	 * Meanscalescore
	 */
	meanScaleScore?: string | null
	/**
	 * Total
	 */
	total?: number | null
	/**
	 * Bandschemecode
	 */
	bandSchemeCode: string
	/**
	 * Bands
	 */
	bands: Array<LevelResult>
}

/**
 * Token
 *
 * A JSON payload containing the access token. The names follow the JWT spec (RFC 7519).
 */
export type Token = {
	/**
	 * Access Token
	 */
	access_token: string
	/**
	 * Token Type
	 */
	token_type?: string
}

/**
 * TrendPoint
 *
 * One year of a change-over-time series.
 */
export type TrendPoint = {
	/**
	 * Testyear
	 */
	testYear: number
	/**
	 * Studentstested
	 */
	studentsTested?: number | null
	/**
	 * Meanscalescore
	 */
	meanScaleScore?: string | null
	/**
	 * Metorabovepct
	 */
	metOrAbovePct?: string | null
	/**
	 * Suppressed
	 */
	suppressed?: boolean
	/**
	 * Levels
	 */
	levels: Array<LevelResult>
}

/**
 * TrendReport
 */
export type TrendReport = {
	entity: EntityPublic
	/**
	 * Testid
	 */
	testId: number
	/**
	 * Studentgroupid
	 */
	studentGroupId: number
	/**
	 * Grade
	 */
	grade: string
	/**
	 * Points
	 */
	points: Array<TrendPoint>
	/**
	 * Scalebreaknote
	 */
	scaleBreakNote?: string | null
}

/**
 * UpdatePassword
 */
export type UpdatePassword = {
	/**
	 * Currentpassword
	 */
	currentPassword: string
	/**
	 * Newpassword
	 */
	newPassword: string
}

/**
 * UserCreate
 */
export type UserCreate = {
	/**
	 * Email
	 */
	email: string
	/**
	 * Isactive
	 */
	isActive?: boolean
	/**
	 * Issuperuser
	 */
	isSuperuser?: boolean
	/**
	 * Fullname
	 */
	fullName?: string | null
	/**
	 * Password
	 */
	password: string
}

/**
 * UserPreferencesUpdate
 */
export type UserPreferencesUpdate = {
	/**
	 * Lastviewedcds
	 */
	lastViewedCds?: string | null
}

/**
 * UserPublic
 */
export type UserPublic = {
	/**
	 * Email
	 */
	email: string
	/**
	 * Isactive
	 */
	isActive?: boolean
	/**
	 * Issuperuser
	 */
	isSuperuser?: boolean
	/**
	 * Fullname
	 */
	fullName?: string | null
	/**
	 * Id
	 */
	id: string
	/**
	 * Createdat
	 */
	createdAt?: string | null
	/**
	 * Forcepasswordreset
	 */
	forcePasswordReset?: boolean
}

/**
 * UserRegister
 */
export type UserRegister = {
	/**
	 * Email
	 */
	email: string
	/**
	 * Password
	 */
	password: string
	/**
	 * Fullname
	 */
	fullName?: string | null
}

/**
 * UserUpdate
 */
export type UserUpdate = {
	/**
	 * Email
	 */
	email?: string | null
	/**
	 * Isactive
	 */
	isActive?: boolean
	/**
	 * Issuperuser
	 */
	isSuperuser?: boolean
	/**
	 * Fullname
	 */
	fullName?: string | null
	/**
	 * Password
	 */
	password?: string | null
	/**
	 * Forcepasswordreset
	 */
	forcePasswordReset?: boolean | null
}

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
	/**
	 * Fullname
	 */
	fullName?: string | null
	/**
	 * Email
	 */
	email?: string | null
	/**
	 * Lastviewedcds
	 */
	lastViewedCds?: string | null
}

/**
 * UsersPublic
 */
export type UsersPublic = {
	/**
	 * Data
	 */
	data: Array<UserPublic>
	/**
	 * Count
	 */
	count: number
}

/**
 * ValidationError
 */
export type ValidationError = {
	/**
	 * Location
	 */
	loc: Array<string | number>
	/**
	 * Message
	 */
	msg: string
	/**
	 * Error Type
	 */
	type: string
	/**
	 * Input
	 */
	input?: unknown
	/**
	 * Context
	 */
	ctx?: {
		[key: string]: unknown
	}
}

export type LoginLoginAccessTokenData = {
	body: BodyLoginLoginAccessToken
	path?: never
	query?: never
	url: '/api/v1/login/access-token'
}

export type LoginLoginAccessTokenErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type LoginLoginAccessTokenError =
	LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors]

export type LoginLoginAccessTokenResponses = {
	/**
	 * Successful Response
	 */
	200: Token
}

export type LoginLoginAccessTokenResponse =
	LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses]

export type LoginTestTokenData = {
	body?: never
	path?: never
	query?: never
	url: '/api/v1/login/test-token'
}

export type LoginTestTokenResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses]

export type LoginRecoverPasswordData = {
	body?: never
	path: {
		/**
		 * Email
		 */
		email: string
	}
	query?: never
	url: '/api/v1/password-recovery/{email}'
}

export type LoginRecoverPasswordErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors]

export type LoginRecoverPasswordResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type LoginRecoverPasswordResponse =
	LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses]

export type LoginResetPasswordData = {
	body: NewPassword
	path?: never
	query?: never
	url: '/api/v1/reset-password/'
}

export type LoginResetPasswordErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors]

export type LoginResetPasswordResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type LoginResetPasswordResponse =
	LoginResetPasswordResponses[keyof LoginResetPasswordResponses]

export type LoginRecoverPasswordHtmlContentData = {
	body?: never
	path: {
		/**
		 * Email
		 */
		email: string
	}
	query?: never
	url: '/api/v1/password-recovery-html-content/{email}'
}

export type LoginRecoverPasswordHtmlContentErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type LoginRecoverPasswordHtmlContentError =
	LoginRecoverPasswordHtmlContentErrors[keyof LoginRecoverPasswordHtmlContentErrors]

export type LoginRecoverPasswordHtmlContentResponses = {
	/**
	 * Successful Response
	 */
	200: string
}

export type LoginRecoverPasswordHtmlContentResponse =
	LoginRecoverPasswordHtmlContentResponses[keyof LoginRecoverPasswordHtmlContentResponses]

export type LoginForcePasswordResetForUsersData = {
	body: ForcePasswordResetRequest
	path?: never
	query?: never
	url: '/api/v1/login/force-password-reset'
}

export type LoginForcePasswordResetForUsersErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type LoginForcePasswordResetForUsersError =
	LoginForcePasswordResetForUsersErrors[keyof LoginForcePasswordResetForUsersErrors]

export type LoginForcePasswordResetForUsersResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type LoginForcePasswordResetForUsersResponse =
	LoginForcePasswordResetForUsersResponses[keyof LoginForcePasswordResetForUsersResponses]

export type UsersReadUsersData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Skip
		 */
		skip?: number
		/**
		 * Limit
		 */
		limit?: number
	}
	url: '/api/v1/users/'
}

export type UsersReadUsersErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors]

export type UsersReadUsersResponses = {
	/**
	 * Successful Response
	 */
	200: UsersPublic
}

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses]

export type UsersCreateUserData = {
	body: UserCreate
	path?: never
	query?: never
	url: '/api/v1/users/'
}

export type UsersCreateUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors]

export type UsersCreateUserResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses]

export type UsersDeleteUserMeData = {
	body?: never
	path?: never
	query?: never
	url: '/api/v1/users/me'
}

export type UsersDeleteUserMeResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses]

export type UsersReadUserMeData = {
	body?: never
	path?: never
	query?: never
	url: '/api/v1/users/me'
}

export type UsersReadUserMeResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses]

export type UsersUpdateUserMeData = {
	body: UserUpdateMe
	path?: never
	query?: never
	url: '/api/v1/users/me'
}

export type UsersUpdateUserMeErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors]

export type UsersUpdateUserMeResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses]

export type UsersUpdatePasswordMeData = {
	body: UpdatePassword
	path?: never
	query?: never
	url: '/api/v1/users/me/password'
}

export type UsersUpdatePasswordMeErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersUpdatePasswordMeError =
	UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors]

export type UsersUpdatePasswordMeResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type UsersUpdatePasswordMeResponse =
	UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses]

export type UsersGetUserPreferencesData = {
	body?: never
	path?: never
	query?: never
	url: '/api/v1/users/me/preferences'
}

export type UsersGetUserPreferencesResponses = {
	/**
	 * Successful Response
	 */
	200: UserPreferencesUpdate
}

export type UsersGetUserPreferencesResponse =
	UsersGetUserPreferencesResponses[keyof UsersGetUserPreferencesResponses]

export type UsersUpdateUserPreferencesData = {
	body: UserPreferencesUpdate
	path?: never
	query?: never
	url: '/api/v1/users/me/preferences'
}

export type UsersUpdateUserPreferencesErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersUpdateUserPreferencesError =
	UsersUpdateUserPreferencesErrors[keyof UsersUpdateUserPreferencesErrors]

export type UsersUpdateUserPreferencesResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type UsersUpdateUserPreferencesResponse =
	UsersUpdateUserPreferencesResponses[keyof UsersUpdateUserPreferencesResponses]

export type UsersRegisterUserData = {
	body: UserRegister
	path?: never
	query?: never
	url: '/api/v1/users/signup'
}

export type UsersRegisterUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors]

export type UsersRegisterUserResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses]

export type UsersDeleteUserData = {
	body?: never
	path: {
		/**
		 * User Id
		 */
		user_id: string
	}
	query?: never
	url: '/api/v1/users/{user_id}'
}

export type UsersDeleteUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors]

export type UsersDeleteUserResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses]

export type UsersReadUserByIdData = {
	body?: never
	path: {
		/**
		 * User Id
		 */
		user_id: string
	}
	query?: never
	url: '/api/v1/users/{user_id}'
}

export type UsersReadUserByIdErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors]

export type UsersReadUserByIdResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses]

export type UsersUpdateUserData = {
	body: UserUpdate
	path: {
		/**
		 * User Id
		 */
		user_id: string
	}
	query?: never
	url: '/api/v1/users/{user_id}'
}

export type UsersUpdateUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors]

export type UsersUpdateUserResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses]

export type UtilsTestEmailData = {
	body?: never
	path?: never
	query: {
		/**
		 * Email To
		 */
		email_to: string
	}
	url: '/api/v1/utils/test-email/'
}

export type UtilsTestEmailErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type UtilsTestEmailError = UtilsTestEmailErrors[keyof UtilsTestEmailErrors]

export type UtilsTestEmailResponses = {
	/**
	 * Successful Response
	 */
	201: Message
}

export type UtilsTestEmailResponse = UtilsTestEmailResponses[keyof UtilsTestEmailResponses]

export type UtilsHealthCheckData = {
	body?: never
	path?: never
	query?: never
	url: '/api/v1/utils/health-check/'
}

export type UtilsHealthCheckResponses = {
	/**
	 * Response Utils-Health Check
	 *
	 * Successful Response
	 */
	200: boolean
}

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses]

export type ItemsReadItemsData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Skip
		 */
		skip?: number
		/**
		 * Limit
		 */
		limit?: number
	}
	url: '/api/v1/items/'
}

export type ItemsReadItemsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ItemsReadItemsError = ItemsReadItemsErrors[keyof ItemsReadItemsErrors]

export type ItemsReadItemsResponses = {
	/**
	 * Successful Response
	 */
	200: ItemsPublic
}

export type ItemsReadItemsResponse = ItemsReadItemsResponses[keyof ItemsReadItemsResponses]

export type ItemsCreateItemData = {
	body: ItemCreate
	path?: never
	query?: never
	url: '/api/v1/items/'
}

export type ItemsCreateItemErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ItemsCreateItemError = ItemsCreateItemErrors[keyof ItemsCreateItemErrors]

export type ItemsCreateItemResponses = {
	/**
	 * Successful Response
	 */
	200: ItemPublic
}

export type ItemsCreateItemResponse = ItemsCreateItemResponses[keyof ItemsCreateItemResponses]

export type ItemsDeleteItemData = {
	body?: never
	path: {
		/**
		 * Id
		 */
		id: string
	}
	query?: never
	url: '/api/v1/items/{id}'
}

export type ItemsDeleteItemErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ItemsDeleteItemError = ItemsDeleteItemErrors[keyof ItemsDeleteItemErrors]

export type ItemsDeleteItemResponses = {
	/**
	 * Successful Response
	 */
	200: Message
}

export type ItemsDeleteItemResponse = ItemsDeleteItemResponses[keyof ItemsDeleteItemResponses]

export type ItemsReadItemData = {
	body?: never
	path: {
		/**
		 * Id
		 */
		id: string
	}
	query?: never
	url: '/api/v1/items/{id}'
}

export type ItemsReadItemErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ItemsReadItemError = ItemsReadItemErrors[keyof ItemsReadItemErrors]

export type ItemsReadItemResponses = {
	/**
	 * Successful Response
	 */
	200: ItemPublic
}

export type ItemsReadItemResponse = ItemsReadItemResponses[keyof ItemsReadItemResponses]

export type ItemsUpdateItemData = {
	body: ItemUpdate
	path: {
		/**
		 * Id
		 */
		id: string
	}
	query?: never
	url: '/api/v1/items/{id}'
}

export type ItemsUpdateItemErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ItemsUpdateItemError = ItemsUpdateItemErrors[keyof ItemsUpdateItemErrors]

export type ItemsUpdateItemResponses = {
	/**
	 * Successful Response
	 */
	200: ItemPublic
}

export type ItemsUpdateItemResponse = ItemsUpdateItemResponses[keyof ItemsUpdateItemResponses]

export type CensusdataCountOfCensusDataData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Skip
		 */
		skip?: number
		/**
		 * Limit
		 */
		limit?: number
	}
	url: '/api/v1/censusdata/'
}

export type CensusdataCountOfCensusDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type CensusdataCountOfCensusDataError =
	CensusdataCountOfCensusDataErrors[keyof CensusdataCountOfCensusDataErrors]

export type CensusdataCountOfCensusDataResponses = {
	/**
	 * Response Censusdata-Count Of Census Data
	 *
	 * Successful Response
	 */
	200: Array<CensusData>
}

export type CensusdataCountOfCensusDataResponse =
	CensusdataCountOfCensusDataResponses[keyof CensusdataCountOfCensusDataResponses]

export type CensusdataCreateCensusDataData = {
	body: CensusData
	path?: never
	query?: never
	url: '/api/v1/censusdata/'
}

export type CensusdataCreateCensusDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type CensusdataCreateCensusDataError =
	CensusdataCreateCensusDataErrors[keyof CensusdataCreateCensusDataErrors]

export type CensusdataCreateCensusDataResponses = {
	/**
	 * Successful Response
	 */
	200: CensusData
}

export type CensusdataCreateCensusDataResponse =
	CensusdataCreateCensusDataResponses[keyof CensusdataCreateCensusDataResponses]

export type CensusdataDeleteCensusDataData = {
	body?: never
	path: {
		/**
		 * Id
		 */
		id: string
	}
	query?: never
	url: '/api/v1/censusdata/{id}'
}

export type CensusdataDeleteCensusDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type CensusdataDeleteCensusDataError =
	CensusdataDeleteCensusDataErrors[keyof CensusdataDeleteCensusDataErrors]

export type CensusdataDeleteCensusDataResponses = {
	/**
	 * Successful Response
	 */
	200: CensusData
}

export type CensusdataDeleteCensusDataResponse =
	CensusdataDeleteCensusDataResponses[keyof CensusdataDeleteCensusDataResponses]

export type CensusdataReadCensusDataData = {
	body?: never
	path: {
		/**
		 * Id
		 */
		id: string
	}
	query?: never
	url: '/api/v1/censusdata/{id}'
}

export type CensusdataReadCensusDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type CensusdataReadCensusDataError =
	CensusdataReadCensusDataErrors[keyof CensusdataReadCensusDataErrors]

export type CensusdataReadCensusDataResponses = {
	/**
	 * Successful Response
	 */
	200: CensusData
}

export type CensusdataReadCensusDataResponse =
	CensusdataReadCensusDataResponses[keyof CensusdataReadCensusDataResponses]

export type CensusdataUpdateCensusDataData = {
	body: CensusData
	path: {
		/**
		 * Id
		 */
		id: string
	}
	query?: never
	url: '/api/v1/censusdata/{id}'
}

export type CensusdataUpdateCensusDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type CensusdataUpdateCensusDataError =
	CensusdataUpdateCensusDataErrors[keyof CensusdataUpdateCensusDataErrors]

export type CensusdataUpdateCensusDataResponses = {
	/**
	 * Successful Response
	 */
	200: CensusData
}

export type CensusdataUpdateCensusDataResponse =
	CensusdataUpdateCensusDataResponses[keyof CensusdataUpdateCensusDataResponses]

export type SchoolsReadSchoolsData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Q
		 */
		q?: string | null
		/**
		 * Skip
		 */
		skip?: number
		/**
		 * Limit
		 */
		limit?: number
	}
	url: '/api/v1/schools/'
}

export type SchoolsReadSchoolsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type SchoolsReadSchoolsError = SchoolsReadSchoolsErrors[keyof SchoolsReadSchoolsErrors]

export type SchoolsReadSchoolsResponses = {
	/**
	 * Successful Response
	 */
	200: SchoolsPublic
}

export type SchoolsReadSchoolsResponse =
	SchoolsReadSchoolsResponses[keyof SchoolsReadSchoolsResponses]

export type SchoolsReadSchoolsSummaryData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Q
		 */
		q?: string | null
		/**
		 * Skip
		 */
		skip?: number
		/**
		 * Limit
		 */
		limit?: number
	}
	url: '/api/v1/schools/summary'
}

export type SchoolsReadSchoolsSummaryErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type SchoolsReadSchoolsSummaryError =
	SchoolsReadSchoolsSummaryErrors[keyof SchoolsReadSchoolsSummaryErrors]

export type SchoolsReadSchoolsSummaryResponses = {
	/**
	 * Successful Response
	 */
	200: SchoolsSummary
}

export type SchoolsReadSchoolsSummaryResponse =
	SchoolsReadSchoolsSummaryResponses[keyof SchoolsReadSchoolsSummaryResponses]

export type ReferenceReadCatalogData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Year
		 *
		 * Administration year; defaults to the most recent.
		 */
		year?: number | null
	}
	url: '/api/v1/reference/catalog'
}

export type ReferenceReadCatalogErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ReferenceReadCatalogError = ReferenceReadCatalogErrors[keyof ReferenceReadCatalogErrors]

export type ReferenceReadCatalogResponses = {
	/**
	 * Successful Response
	 */
	200: Catalog
}

export type ReferenceReadCatalogResponse =
	ReferenceReadCatalogResponses[keyof ReferenceReadCatalogResponses]

export type EntitiesSearchEntitiesData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Q
		 *
		 * Name or CDS code fragment.
		 */
		q?: string | null
		/**
		 * Level
		 */
		level?: EntityLevel | null
		/**
		 * Countycode
		 */
		countyCode?: string | null
		/**
		 * Districtcode
		 */
		districtCode?: string | null
		/**
		 * Charter
		 */
		charter?: boolean | null
		/**
		 * Limit
		 */
		limit?: number
		/**
		 * Offset
		 */
		offset?: number
	}
	url: '/api/v1/entities/search'
}

export type EntitiesSearchEntitiesErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type EntitiesSearchEntitiesError =
	EntitiesSearchEntitiesErrors[keyof EntitiesSearchEntitiesErrors]

export type EntitiesSearchEntitiesResponses = {
	/**
	 * Successful Response
	 */
	200: EntityList
}

export type EntitiesSearchEntitiesResponse =
	EntitiesSearchEntitiesResponses[keyof EntitiesSearchEntitiesResponses]

export type EntitiesReadEntityData = {
	body?: never
	path: {
		/**
		 * Cds Code
		 */
		cds_code: string
	}
	query?: never
	url: '/api/v1/entities/{cds_code}'
}

export type EntitiesReadEntityErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type EntitiesReadEntityError = EntitiesReadEntityErrors[keyof EntitiesReadEntityErrors]

export type EntitiesReadEntityResponses = {
	/**
	 * Successful Response
	 */
	200: EntityAncestry
}

export type EntitiesReadEntityResponse =
	EntitiesReadEntityResponses[keyof EntitiesReadEntityResponses]

export type EntitiesReadChildrenData = {
	body?: never
	path: {
		/**
		 * Cds Code
		 */
		cds_code: string
	}
	query?: {
		/**
		 * Q
		 */
		q?: string | null
		/**
		 * Charter
		 */
		charter?: boolean | null
		/**
		 * Limit
		 */
		limit?: number
		/**
		 * Offset
		 */
		offset?: number
	}
	url: '/api/v1/entities/{cds_code}/children'
}

export type EntitiesReadChildrenErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type EntitiesReadChildrenError = EntitiesReadChildrenErrors[keyof EntitiesReadChildrenErrors]

export type EntitiesReadChildrenResponses = {
	/**
	 * Successful Response
	 */
	200: EntityList
}

export type EntitiesReadChildrenResponse =
	EntitiesReadChildrenResponses[keyof EntitiesReadChildrenResponses]

export type ReportsReadOverviewData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Cds
		 *
		 * 14-character CDS code.
		 */
		cds?: string
		/**
		 * Year
		 */
		year?: number | null
		/**
		 * Studentgroup
		 */
		studentGroup?: number
		/**
		 * Grade
		 */
		grade?: string
		/**
		 * Tests
		 *
		 * Comma-separated test ids; defaults to all.
		 */
		tests?: string | null
		schoolType?: SchoolType
		/**
		 * Compare
		 *
		 * Include the district, county and state alongside.
		 */
		compare?: boolean
	}
	url: '/api/v1/reports/overview'
}

export type ReportsReadOverviewErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ReportsReadOverviewError = ReportsReadOverviewErrors[keyof ReportsReadOverviewErrors]

export type ReportsReadOverviewResponses = {
	/**
	 * Successful Response
	 */
	200: OverviewReport
}

export type ReportsReadOverviewResponse =
	ReportsReadOverviewResponses[keyof ReportsReadOverviewResponses]

export type ReportsReadSubscoresData = {
	body?: never
	path?: never
	query: {
		/**
		 * Testid
		 */
		testId: number
		/**
		 * Cds
		 */
		cds?: string
		/**
		 * Year
		 */
		year?: number | null
		/**
		 * Studentgroup
		 */
		studentGroup?: number
		/**
		 * Grade
		 */
		grade?: string
	}
	url: '/api/v1/reports/subscores'
}

export type ReportsReadSubscoresErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ReportsReadSubscoresError = ReportsReadSubscoresErrors[keyof ReportsReadSubscoresErrors]

export type ReportsReadSubscoresResponses = {
	/**
	 * Successful Response
	 */
	200: SubscoreReport
}

export type ReportsReadSubscoresResponse =
	ReportsReadSubscoresResponses[keyof ReportsReadSubscoresResponses]

export type ReportsReadTrendData = {
	body?: never
	path?: never
	query: {
		/**
		 * Testid
		 */
		testId: number
		/**
		 * Cds
		 */
		cds?: string
		/**
		 * Studentgroup
		 */
		studentGroup?: number
		/**
		 * Grade
		 */
		grade?: string
		/**
		 * Fromyear
		 */
		fromYear?: number | null
		/**
		 * Toyear
		 */
		toYear?: number | null
	}
	url: '/api/v1/reports/trend'
}

export type ReportsReadTrendErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ReportsReadTrendError = ReportsReadTrendErrors[keyof ReportsReadTrendErrors]

export type ReportsReadTrendResponses = {
	/**
	 * Successful Response
	 */
	200: TrendReport
}

export type ReportsReadTrendResponse = ReportsReadTrendResponses[keyof ReportsReadTrendResponses]

export type ReportsReadStudentGroupsData = {
	body?: never
	path?: never
	query: {
		/**
		 * Testid
		 */
		testId: number
		/**
		 * Cds
		 */
		cds?: string
		/**
		 * Year
		 */
		year?: number | null
		/**
		 * Grade
		 */
		grade?: string
		/**
		 * Category
		 */
		category?: Array<string> | null
	}
	url: '/api/v1/reports/student-groups'
}

export type ReportsReadStudentGroupsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ReportsReadStudentGroupsError =
	ReportsReadStudentGroupsErrors[keyof ReportsReadStudentGroupsErrors]

export type ReportsReadStudentGroupsResponses = {
	/**
	 * Successful Response
	 */
	200: StudentGroupReport
}

export type ReportsReadStudentGroupsResponse =
	ReportsReadStudentGroupsResponses[keyof ReportsReadStudentGroupsResponses]

export type ReportsReadGradesData = {
	body?: never
	path?: never
	query: {
		/**
		 * Testid
		 */
		testId: number
		/**
		 * Cds
		 */
		cds?: string
		/**
		 * Year
		 */
		year?: number | null
		/**
		 * Studentgroup
		 */
		studentGroup?: number
	}
	url: '/api/v1/reports/grades'
}

export type ReportsReadGradesErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ReportsReadGradesError = ReportsReadGradesErrors[keyof ReportsReadGradesErrors]

export type ReportsReadGradesResponses = {
	/**
	 * Successful Response
	 */
	200: GradeReport
}

export type ReportsReadGradesResponse = ReportsReadGradesResponses[keyof ReportsReadGradesResponses]

export type ReportsReadChildResultsData = {
	body?: never
	path?: never
	query: {
		/**
		 * Testid
		 */
		testId: number
		/**
		 * Cds
		 */
		cds?: string
		/**
		 * Year
		 */
		year?: number | null
		/**
		 * Studentgroup
		 */
		studentGroup?: number
		/**
		 * Grade
		 */
		grade?: string
		schoolType?: SchoolType
		/**
		 * Orderby
		 */
		orderBy?: string
		/**
		 * Descending
		 */
		descending?: boolean
		/**
		 * Limit
		 */
		limit?: number
		/**
		 * Offset
		 */
		offset?: number
	}
	url: '/api/v1/reports/children'
}

export type ReportsReadChildResultsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ReportsReadChildResultsError =
	ReportsReadChildResultsErrors[keyof ReportsReadChildResultsErrors]

export type ReportsReadChildResultsResponses = {
	/**
	 * Successful Response
	 */
	200: ChildEntityReport
}

export type ReportsReadChildResultsResponse =
	ReportsReadChildResultsResponses[keyof ReportsReadChildResultsResponses]

export type ReportsReadComparisonData = {
	body?: never
	path?: never
	query: {
		/**
		 * Cdscodes
		 *
		 * Comma-separated CDS codes, at most 10.
		 */
		cdsCodes: string
		/**
		 * Testid
		 */
		testId?: number | null
		/**
		 * Year
		 */
		year?: number | null
		/**
		 * Studentgroup
		 */
		studentGroup?: number
		/**
		 * Grade
		 */
		grade?: string
	}
	url: '/api/v1/reports/compare'
}

export type ReportsReadComparisonErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type ReportsReadComparisonError =
	ReportsReadComparisonErrors[keyof ReportsReadComparisonErrors]

export type ReportsReadComparisonResponses = {
	/**
	 * Successful Response
	 */
	200: CompareReport
}

export type ReportsReadComparisonResponse =
	ReportsReadComparisonResponses[keyof ReportsReadComparisonResponses]

export type DashboardReadCatalogData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Year
		 */
		year?: number | null
	}
	url: '/api/v1/dashboard/catalog'
}

export type DashboardReadCatalogErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type DashboardReadCatalogError = DashboardReadCatalogErrors[keyof DashboardReadCatalogErrors]

export type DashboardReadCatalogResponses = {
	/**
	 * Successful Response
	 */
	200: DashboardCatalog
}

export type DashboardReadCatalogResponse =
	DashboardReadCatalogResponses[keyof DashboardReadCatalogResponses]

export type DashboardReadIndicatorsData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Cds
		 *
		 * 14-character CDS code.
		 */
		cds?: string
		/**
		 * Year
		 */
		year?: number | null
		/**
		 * Studentgroup
		 */
		studentGroup?: string
		/**
		 * Includeprojected
		 */
		includeProjected?: boolean
	}
	url: '/api/v1/dashboard/indicators'
}

export type DashboardReadIndicatorsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type DashboardReadIndicatorsError =
	DashboardReadIndicatorsErrors[keyof DashboardReadIndicatorsErrors]

export type DashboardReadIndicatorsResponses = {
	/**
	 * Successful Response
	 */
	200: IndicatorReport
}

export type DashboardReadIndicatorsResponse =
	DashboardReadIndicatorsResponses[keyof DashboardReadIndicatorsResponses]

export type DashboardReadIndicatorData = {
	body?: never
	path?: never
	query: {
		/**
		 * Indicator
		 *
		 * Indicator code, e.g. CHRO.
		 */
		indicator: string
		/**
		 * Cds
		 */
		cds?: string
		/**
		 * Year
		 */
		year?: number | null
	}
	url: '/api/v1/dashboard/indicator'
}

export type DashboardReadIndicatorErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type DashboardReadIndicatorError =
	DashboardReadIndicatorErrors[keyof DashboardReadIndicatorErrors]

export type DashboardReadIndicatorResponses = {
	/**
	 * Successful Response
	 */
	200: IndicatorGroupReport
}

export type DashboardReadIndicatorResponse =
	DashboardReadIndicatorResponses[keyof DashboardReadIndicatorResponses]

export type DashboardReadTrendData = {
	body?: never
	path?: never
	query: {
		/**
		 * Indicator
		 *
		 * Indicator code, e.g. CHRO.
		 */
		indicator: string
		/**
		 * Cds
		 */
		cds?: string
		/**
		 * Studentgroup
		 */
		studentGroup?: string
		/**
		 * Fromyear
		 */
		fromYear?: number | null
		/**
		 * Toyear
		 */
		toYear?: number | null
	}
	url: '/api/v1/dashboard/trend'
}

export type DashboardReadTrendErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type DashboardReadTrendError = DashboardReadTrendErrors[keyof DashboardReadTrendErrors]

export type DashboardReadTrendResponses = {
	/**
	 * Successful Response
	 */
	200: IndicatorTrendReport
}

export type DashboardReadTrendResponse =
	DashboardReadTrendResponses[keyof DashboardReadTrendResponses]

export type DashboardReadChildrenData = {
	body?: never
	path?: never
	query: {
		/**
		 * Indicator
		 *
		 * Indicator code, e.g. CHRO.
		 */
		indicator: string
		/**
		 * Cds
		 */
		cds?: string
		/**
		 * Year
		 */
		year?: number | null
		/**
		 * Studentgroup
		 */
		studentGroup?: string
		/**
		 * Orderby
		 */
		orderBy?: string
		/**
		 * Descending
		 */
		descending?: boolean
		/**
		 * Limit
		 */
		limit?: number
		/**
		 * Offset
		 */
		offset?: number
	}
	url: '/api/v1/dashboard/children'
}

export type DashboardReadChildrenErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type DashboardReadChildrenError =
	DashboardReadChildrenErrors[keyof DashboardReadChildrenErrors]

export type DashboardReadChildrenResponses = {
	/**
	 * Successful Response
	 */
	200: ChildIndicatorReport
}

export type DashboardReadChildrenResponse =
	DashboardReadChildrenResponses[keyof DashboardReadChildrenResponses]

export type DashboardReadGrowthData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Cds
		 */
		cds?: string
		/**
		 * Year
		 */
		year?: number | null
		/**
		 * Studentgroup
		 */
		studentGroup?: string
	}
	url: '/api/v1/dashboard/growth'
}

export type DashboardReadGrowthErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type DashboardReadGrowthError = DashboardReadGrowthErrors[keyof DashboardReadGrowthErrors]

export type DashboardReadGrowthResponses = {
	/**
	 * Successful Response
	 */
	200: GrowthReport
}

export type DashboardReadGrowthResponse =
	DashboardReadGrowthResponses[keyof DashboardReadGrowthResponses]

export type DashboardReadEnrollmentData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Cds
		 */
		cds?: string
		/**
		 * Year
		 */
		year?: number | null
	}
	url: '/api/v1/dashboard/enrollment'
}

export type DashboardReadEnrollmentErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type DashboardReadEnrollmentError =
	DashboardReadEnrollmentErrors[keyof DashboardReadEnrollmentErrors]

export type DashboardReadEnrollmentResponses = {
	/**
	 * Successful Response
	 */
	200: EnrollmentReport
}

export type DashboardReadEnrollmentResponse =
	DashboardReadEnrollmentResponses[keyof DashboardReadEnrollmentResponses]

export type LocalIndicatorsReadCatalogData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Year
		 */
		year?: number | null
	}
	url: '/api/v1/local-indicators/catalog'
}

export type LocalIndicatorsReadCatalogErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type LocalIndicatorsReadCatalogError =
	LocalIndicatorsReadCatalogErrors[keyof LocalIndicatorsReadCatalogErrors]

export type LocalIndicatorsReadCatalogResponses = {
	/**
	 * Successful Response
	 */
	200: LocalIndicatorCatalog
}

export type LocalIndicatorsReadCatalogResponse =
	LocalIndicatorsReadCatalogResponses[keyof LocalIndicatorsReadCatalogResponses]

export type LocalIndicatorsReadLocalIndicatorsData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Cds
		 *
		 * 14-character CDS code.
		 */
		cds?: string
		/**
		 * Year
		 */
		year?: number | null
	}
	url: '/api/v1/local-indicators/'
}

export type LocalIndicatorsReadLocalIndicatorsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type LocalIndicatorsReadLocalIndicatorsError =
	LocalIndicatorsReadLocalIndicatorsErrors[keyof LocalIndicatorsReadLocalIndicatorsErrors]

export type LocalIndicatorsReadLocalIndicatorsResponses = {
	/**
	 * Successful Response
	 */
	200: LocalIndicatorReport
}

export type LocalIndicatorsReadLocalIndicatorsResponse =
	LocalIndicatorsReadLocalIndicatorsResponses[keyof LocalIndicatorsReadLocalIndicatorsResponses]

export type LocalIndicatorsReadPriorityData = {
	body?: never
	path?: never
	query: {
		/**
		 * Priority
		 *
		 * LCFF priority number, e.g. 3.
		 */
		priority: number
		/**
		 * Cds
		 */
		cds?: string
		/**
		 * Year
		 */
		year?: number | null
	}
	url: '/api/v1/local-indicators/priority'
}

export type LocalIndicatorsReadPriorityErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type LocalIndicatorsReadPriorityError =
	LocalIndicatorsReadPriorityErrors[keyof LocalIndicatorsReadPriorityErrors]

export type LocalIndicatorsReadPriorityResponses = {
	/**
	 * Successful Response
	 */
	200: LocalIndicatorDetail
}

export type LocalIndicatorsReadPriorityResponse =
	LocalIndicatorsReadPriorityResponses[keyof LocalIndicatorsReadPriorityResponses]

export type LocalIndicatorsReadTrendData = {
	body?: never
	path?: never
	query: {
		/**
		 * Priority
		 *
		 * LCFF priority number, e.g. 3.
		 */
		priority: number
		/**
		 * Cds
		 */
		cds?: string
	}
	url: '/api/v1/local-indicators/trend'
}

export type LocalIndicatorsReadTrendErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type LocalIndicatorsReadTrendError =
	LocalIndicatorsReadTrendErrors[keyof LocalIndicatorsReadTrendErrors]

export type LocalIndicatorsReadTrendResponses = {
	/**
	 * Successful Response
	 */
	200: LocalIndicatorTrendReport
}

export type LocalIndicatorsReadTrendResponse =
	LocalIndicatorsReadTrendResponses[keyof LocalIndicatorsReadTrendResponses]

export type IngestListRunsData = {
	body?: never
	path?: never
	query?: {
		/**
		 * Limit
		 */
		limit?: number
	}
	url: '/api/v1/ingest/runs'
}

export type IngestListRunsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type IngestListRunsError = IngestListRunsErrors[keyof IngestListRunsErrors]

export type IngestListRunsResponses = {
	/**
	 * Successful Response
	 */
	200: IngestRunList
}

export type IngestListRunsResponse = IngestListRunsResponses[keyof IngestListRunsResponses]

export type IngestStartIngestData = {
	body: IngestRequest
	path?: never
	query?: never
	url: '/api/v1/ingest/runs'
}

export type IngestStartIngestErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type IngestStartIngestError = IngestStartIngestErrors[keyof IngestStartIngestErrors]

export type IngestStartIngestResponses = {
	/**
	 * Successful Response
	 */
	202: IngestRunPublic
}

export type IngestStartIngestResponse = IngestStartIngestResponses[keyof IngestStartIngestResponses]

export type IngestReadRunData = {
	body?: never
	path: {
		/**
		 * Run Id
		 */
		run_id: string
	}
	query?: never
	url: '/api/v1/ingest/runs/{run_id}'
}

export type IngestReadRunErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type IngestReadRunError = IngestReadRunErrors[keyof IngestReadRunErrors]

export type IngestReadRunResponses = {
	/**
	 * Successful Response
	 */
	200: IngestRunDetail
}

export type IngestReadRunResponse = IngestReadRunResponses[keyof IngestReadRunResponses]

export type PrivateCreateUserData = {
	body: PrivateUserCreate
	path?: never
	query?: never
	url: '/api/v1/private/users/'
}

export type PrivateCreateUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError
}

export type PrivateCreateUserError = PrivateCreateUserErrors[keyof PrivateCreateUserErrors]

export type PrivateCreateUserResponses = {
	/**
	 * Successful Response
	 */
	200: UserPublic
}

export type PrivateCreateUserResponse = PrivateCreateUserResponses[keyof PrivateCreateUserResponses]
