"""Update CensusData primary key to schl_id

Revision ID: 1d53f36fa2de
Revises: abbe6b667292
Create Date: 2025-08-10 09:29:15.214807

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1d53f36fa2de'
down_revision = 'abbe6b667292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the existing primary key constraint
    op.drop_constraint('censusdata_pkey', 'censusdata', type_='primary')
    # Add primary key constraint on schl_id
    op.create_primary_key('censusdata_pkey', 'censusdata', ['schl_id'])
    # Drop the old id column
    op.drop_column('censusdata', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back the id column
    op.add_column('censusdata', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    # Drop the current primary key constraint
    op.drop_constraint('censusdata_pkey', 'censusdata', type_='primary')
    # Add primary key constraint back on id
    op.create_primary_key('censusdata_pkey', 'censusdata', ['id'])
    # ### end Alembic commands ###
