"""Add census day enrollment rates

Revision ID: 23f3798f79df
Revises: 1e0311874f65
Create Date: 2026-08-31 12:33:21.620439

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = '23f3798f79df'
down_revision = '1e0311874f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_rates',
                    sa.Column('cds_code', sqlmodel.sql.sqltypes.AutoString(length=14), nullable=False),
                    sa.Column('reporting_year', sa.Integer(), nullable=False),
                    sa.Column('student_group_code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
                    sa.Column('total_enrollment', sa.Integer(), nullable=True),
                    sa.Column('subgroup_total', sa.Integer(), nullable=True),
                    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=True),
                    sa.ForeignKeyConstraint(['cds_code'], ['entities.cds_code'], ),
                    sa.PrimaryKeyConstraint('cds_code', 'reporting_year', 'student_group_code')
                    )
    op.create_index('ix_enrollment_lookup', 'enrollment_rates', ['reporting_year', 'student_group_code', 'cds_code'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_enrollment_lookup', table_name='enrollment_rates')
    op.drop_table('enrollment_rates')
    # ### end Alembic commands ###
