"""Add Dashboard student groups

Revision ID: 2aec1e0612ec
Revises: d8715d3c4ed9
Create Date: 2026-08-31 09:51:11.816092

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = '2aec1e0612ec'
down_revision = 'd8715d3c4ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_student_groups',
                    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
                    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
                    sa.Column('sort_order', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('code')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_student_groups')
    # ### end Alembic commands ###
