"""Add LCFF local indicators

Revision ID: 2ce75c5c25b3
Revises: 2aec1e0612ec
Create Date: 2026-08-31 11:21:00.647723

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ce75c5c25b3'
down_revision = '2aec1e0612ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_indicator_priorities',
                    sa.Column('priority_number', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
                    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('county_office_only', sa.Boolean(), nullable=False),
                    sa.Column('sort_order', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('priority_number')
                    )
    op.create_table('local_indicator_results',
                    sa.Column('cds_code', sqlmodel.sql.sqltypes.AutoString(length=14), nullable=False),
                    sa.Column('reporting_year', sa.Integer(), nullable=False),
                    sa.Column('priority_number', sa.Integer(), nullable=False),
                    sa.Column('lea_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
                    sa.Column('performance', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
                    sa.Column('meeting_date', sa.Date(), nullable=True),
                    sa.Column('additional_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('responses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.ForeignKeyConstraint(['cds_code'], ['entities.cds_code'], ),
                    sa.ForeignKeyConstraint(['priority_number'], ['local_indicator_priorities.priority_number'], ),
                    sa.PrimaryKeyConstraint('cds_code', 'reporting_year', 'priority_number')
                    )
    op.create_index('ix_local_indicator_lookup', 'local_indicator_results',
                    ['reporting_year', 'priority_number', 'performance'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_local_indicator_lookup', table_name='local_indicator_results')
    op.drop_table('local_indicator_results')
    op.drop_table('local_indicator_priorities')
    # ### end Alembic commands ###
