"""Add CensusData model

Revision ID: 3b8a6856d220
Revises: 1a31ce608336
Create Date: 2025-08-10 09:19:55.971451

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3b8a6856d220'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('censusdata',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('school_name', 
                  sa.String(length=255), 
                  nullable=False),
        sa.Column('student_count', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('censusdata')
    # ### end Alembic commands ###
