"""Mark informational dashboard indicators

Revision ID: 45f2bf28cbe7
Revises: 23f3798f79df
Create Date: 2026-08-31 12:39:44.443521

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '45f2bf28cbe7'
down_revision = '23f3798f79df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_indicators', sa.Column(
        'is_informational',
        sa.Boolean(),
        nullable=False,
        # The table is already populated, so existing indicators need a
        # value; every one of them is an accountability indicator.
        server_default=sa.false(),
    ))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard_indicators', 'is_informational')
    # ### end Alembic commands ###
