"""Add new school table

Revision ID: 47f9668602ed
Revises: 8a38665e13e6
Create Date: 2025-08-15 11:30:48.029069

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '47f9668602ed'
down_revision = '8a38665e13e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('cds_code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('nces_dist', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('nces_school', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('county', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('district', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('school', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('street', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('street_abr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('zip', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('mail_street', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mail_street_abr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mail_city', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('mail_zip', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('mail_state', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ext', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('fax_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('open_date', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('closed_date', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('charter', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('charter_num', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('funding_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('doc', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('doc_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('soc', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('soc_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('edops_code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('edops_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('eil_code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('eil_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('gs_offered', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('gs_served', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('virtual', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('magnet', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('year_round_yn', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('federal_dfc_district_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('adm_fname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('adm_lname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('last_up_date', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('multilingual', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cds_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school')
    # ### end Alembic commands ###
