"""Add Census data models

Revision ID: 8a38665e13e6
Revises: eb18e3ec8487
Create Date: 2025-08-10 20:06:19.178801

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8a38665e13e6'
down_revision = 'eb18e3ec8487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('censusdata', sa.Column('census_data_id', sa.Uuid(), nullable=False))
    op.drop_column('censusdata', 'schl_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('censusdata', sa.Column('schl_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('censusdata', 'census_data_id')
    # ### end Alembic commands ###
