"""Normalize assessment column names and index dashboard lookups

Revision ID: 8c1f4a2b7d90
Revises: fa601598b7df
Create Date: 2026-08-28 00:00:00.000000

The assessment result tables were created with the raw CDE export headers as
column names ("Percentage Standard Met and Above"), which did not match the
snake_case ORM attributes.  Rename every one of them to the attribute name so
model attributes and columns line up, and add the composite indexes the
dashboard endpoints filter on.
"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "8c1f4a2b7d90"
down_revision = "fa601598b7df"
branch_labels = None
depends_on = None

# table -> {legacy column name: normalized column name}
RENAMES: dict[str, dict[str, str]] = {
    'caa_results': {
        'Mean Scale Score': 'mean_scale_score',
        'Count Level 1': 'count_level_1',
        'Count Level 2': 'count_level_2',
        'Count Level 3': 'count_level_3',
        'Percentage Level 1': 'percentage_level_1',
        'Percentage Level 2': 'percentage_level_2',
        'Percentage Level 3': 'percentage_level_3',
    },
    'caas_results': {
        'Mean Scale Score': 'mean_scale_score',
        'Count Level 1': 'count_level_1',
        'Count Level 2': 'count_level_2',
        'Count Level 3': 'count_level_3',
        'Percentage Level 1': 'percentage_level_1',
        'Percentage Level 2': 'percentage_level_2',
        'Percentage Level 3': 'percentage_level_3',
    },
    'cast_results': {
        'Mean Scale Score': 'mean_scale_score',
        'Count Standard Exceeded': 'count_standard_exceeded',
        'Count Standard Met': 'count_standard_met',
        'Count Standard Met and Above': 'count_standard_met_and_above',
        'Count Standard Nearly Met': 'count_standard_nearly_met',
        'Count Standard Not Met': 'count_standard_not_met',
        'Percentage Standard Exceeded': 'percentage_standard_exceeded',
        'Percentage Standard Met': 'percentage_standard_met',
        'Percentage Standard Met and Above': 'percentage_standard_met_and_above',
        'Percentage Standard Nearly Met': 'percentage_standard_nearly_met',
        'Percentage Standard Not Met': 'percentage_standard_not_met',
        'Earth and Space Sciences Domain Count Above Standard': 'earth_and_space_sciences_domain_count_above_standard',
        'Earth and Space Sciences Domain Count Below Standard': 'earth_and_space_sciences_domain_count_below_standard',
        'Earth and Space Sciences Domain Count Near Standard': 'earth_and_space_sciences_domain_count_near_standard',
        'Earth and Space Sciences Domain Percent Above Standard': 'earth_and_space_sciences_domain_percent_above_standard',
        'Earth and Space Sciences Domain Percent Below Standard': 'earth_and_space_sciences_domain_percent_below_standard',
        'Earth and Space Sciences Domain Percent Near Standard': 'earth_and_space_sciences_domain_percent_near_standard',
        'Earth and Space Sciences Domain Total': 'earth_and_space_sciences_domain_total',
        'Life Sciences Domain Count Above Standard': 'life_sciences_domain_count_above_standard',
        'Life Sciences Domain Count Below Standard': 'life_sciences_domain_count_below_standard',
        'Life Sciences Domain Count Near Standard': 'life_sciences_domain_count_near_standard',
        'Life Sciences Domain Percent Above Standard': 'life_sciences_domain_percent_above_standard',
        'Life Sciences Domain Percent Below Standard': 'life_sciences_domain_percent_below_standard',
        'Life Sciences Domain Percent Near Standard': 'life_sciences_domain_percent_near_standard',
        'Life Sciences Domain Total': 'life_sciences_domain_total',
        'Physical Sciences Domain Count Above Standard': 'physical_sciences_domain_count_above_standard',
        'Physical Sciences Domain Count Below Standard': 'physical_sciences_domain_count_below_standard',
        'Physical Sciences Domain Count Near Standard': 'physical_sciences_domain_count_near_standard',
        'Physical Sciences Domain Percent Above Standard': 'physical_sciences_domain_percent_above_standard',
        'Physical Sciences Domain Percent Below Standard': 'physical_sciences_domain_percent_below_standard',
        'Physical Sciences Domain Percent Near Standard': 'physical_sciences_domain_percent_near_standard',
        'Physical Sciences Domain Total': 'physical_sciences_domain_total',
    },
    'csa_results': {
        'Overall Mean Scale Score': 'overall_mean_scale_score',
        'Count Level 1': 'count_level_1',
        'Count Level 2': 'count_level_2',
        'Count Level 3': 'count_level_3',
        'Percent Level 1': 'percent_level_1',
        'Percent Level 2': 'percent_level_2',
        'Percent Level 3': 'percent_level_3',
        'Composite 1 Count Level 1': 'composite_1_count_level_1',
        'Composite 1 Count Level 2': 'composite_1_count_level_2',
        'Composite 1 Count Level 3': 'composite_1_count_level_3',
        'Composite 1 Mean Scale Score': 'composite_1_mean_scale_score',
        'Composite 1 Percent Level 1': 'composite_1_percent_level_1',
        'Composite 1 Percent Level 2': 'composite_1_percent_level_2',
        'Composite 1 Percent Level 3': 'composite_1_percent_level_3',
        'Composite 1 Total': 'composite_1_total',
        'Composite 2 Count Level 1': 'composite_2_count_level_1',
        'Composite 2 Count Level 2': 'composite_2_count_level_2',
        'Composite 2 Count Level 3': 'composite_2_count_level_3',
        'Composite 2 Mean Scale Score': 'composite_2_mean_scale_score',
        'Composite 2 Percent Level 1': 'composite_2_percent_level_1',
        'Composite 2 Percent Level 2': 'composite_2_percent_level_2',
        'Composite 2 Percent Level 3': 'composite_2_percent_level_3',
        'Composite 2 Total': 'composite_2_total',
        'Listening Domain Count Level 1': 'listening_domain_count_level_1',
        'Listening Domain Count Level 2': 'listening_domain_count_level_2',
        'Listening Domain Count Level 3': 'listening_domain_count_level_3',
        'Listening Domain Percent Level 1': 'listening_domain_percent_level_1',
        'Listening Domain Percent Level 2': 'listening_domain_percent_level_2',
        'Listening Domain Percent Level 3': 'listening_domain_percent_level_3',
        'Listening Domain Total': 'listening_domain_total',
        'Reading Domain Count Level 1': 'reading_domain_count_level_1',
        'Reading Domain Count Level 2': 'reading_domain_count_level_2',
        'Reading Domain Count Level 3': 'reading_domain_count_level_3',
        'Reading Domain Percent Level 1': 'reading_domain_percent_level_1',
        'Reading Domain Percent Level 2': 'reading_domain_percent_level_2',
        'Reading Domain Percent Level 3': 'reading_domain_percent_level_3',
        'Reading Domain Total': 'reading_domain_total',
        'Speaking Domain Count Level 1': 'speaking_domain_count_level_1',
        'Speaking Domain Count Level 2': 'speaking_domain_count_level_2',
        'Speaking Domain Count Level 3': 'speaking_domain_count_level_3',
        'Speaking Domain Percent Level 1': 'speaking_domain_percent_level_1',
        'Speaking Domain Percent Level 2': 'speaking_domain_percent_level_2',
        'Speaking Domain Percent Level 3': 'speaking_domain_percent_level_3',
        'Speaking Domain Total': 'speaking_domain_total',
        'Writing Domain Count Level 1': 'writing_domain_count_level_1',
        'Writing Domain Count Level 2': 'writing_domain_count_level_2',
        'Writing Domain Count Level 3': 'writing_domain_count_level_3',
        'Writing Domain Percent Level 1': 'writing_domain_percent_level_1',
        'Writing Domain Percent Level 2': 'writing_domain_percent_level_2',
        'Writing Domain Percent Level 3': 'writing_domain_percent_level_3',
        'Writing Domain Total': 'writing_domain_total',
    },
    'sb_results': {
        'Mean Scale Score': 'mean_scale_score',
        'Count Standard Exceeded': 'count_standard_exceeded',
        'Count Standard Met': 'count_standard_met',
        'Count Standard Met and Above': 'count_standard_met_and_above',
        'Count Standard Nearly Met': 'count_standard_nearly_met',
        'Count Standard Not Met': 'count_standard_not_met',
        'Percentage Standard Exceeded': 'percentage_standard_exceeded',
        'Percentage Standard Met': 'percentage_standard_met',
        'Percentage Standard Met and Above': 'percentage_standard_met_and_above',
        'Percentage Standard Nearly Met': 'percentage_standard_nearly_met',
        'Percentage Standard Not Met': 'percentage_standard_not_met',
        'Area 1 Count Above Standard': 'area_1_count_above_standard',
        'Area 1 Count Below Standard': 'area_1_count_below_standard',
        'Area 1 Count Near Standard': 'area_1_count_near_standard',
        'Area 1 Percentage Above Standard': 'area_1_percentage_above_standard',
        'Area 1 Percentage Below Standard': 'area_1_percentage_below_standard',
        'Area 1 Percentage Near Standard': 'area_1_percentage_near_standard',
        'Area 1 Total': 'area_1_total',
        'Area 2 Count Above Standard': 'area_2_count_above_standard',
        'Area 2 Count Below Standard': 'area_2_count_below_standard',
        'Area 2 Count Near Standard': 'area_2_count_near_standard',
        'Area 2 Percentage Above Standard': 'area_2_percentage_above_standard',
        'Area 2 Percentage Below Standard': 'area_2_percentage_below_standard',
        'Area 2 Percentage Near Standard': 'area_2_percentage_near_standard',
        'Area 2 Total': 'area_2_total',
        'Area 3 Count Above Standard': 'area_3_count_above_standard',
        'Area 3 Count Below Standard': 'area_3_count_below_standard',
        'Area 3 Count Near Standard': 'area_3_count_near_standard',
        'Area 3 Percentage Above Standard': 'area_3_percentage_above_standard',
        'Area 3 Percentage Below Standard': 'area_3_percentage_below_standard',
        'Area 3 Percentage Near Standard': 'area_3_percentage_near_standard',
        'Area 3 Total': 'area_3_total',
        'Area 4 Count Above Standard': 'area_4_count_above_standard',
        'Area 4 Count Below Standard': 'area_4_count_below_standard',
        'Area 4 Count Near Standard': 'area_4_count_near_standard',
        'Area 4 Percentage Above Standard': 'area_4_percentage_above_standard',
        'Area 4 Percentage Below Standard': 'area_4_percentage_below_standard',
        'Area 4 Percentage Near Standard': 'area_4_percentage_near_standard',
        'Area 4 Total': 'area_4_total',
        'Composite Area 1 Count Above Standard': 'composite_area_1_count_above_standard',
        'Composite Area 1 Count Below Standard': 'composite_area_1_count_below_standard',
        'Composite Area 1 Count Near Standard': 'composite_area_1_count_near_standard',
        'Composite Area 1 Percentage Above Standard': 'composite_area_1_percentage_above_standard',
        'Composite Area 1 Percentage Below Standard': 'composite_area_1_percentage_below_standard',
        'Composite Area 1 Percentage Near Standard': 'composite_area_1_percentage_near_standard',
        'Composite Area 1 Total': 'composite_area_1_total',
        'Composite Area 2 Count Above Standard': 'composite_area_2_count_above_standard',
        'Composite Area 2 Count Below Standard': 'composite_area_2_count_below_standard',
        'Composite Area 2 Count Near Standard': 'composite_area_2_count_near_standard',
        'Composite Area 2 Percentage Above Standard': 'composite_area_2_percentage_above_standard',
        'Composite Area 2 Percentage Below Standard': 'composite_area_2_percentage_below_standard',
        'Composite Area 2 Percentage Near Standard': 'composite_area_2_percentage_near_standard',
        'Composite Area 2 Total': 'composite_area_2_total',
    },
    'ia_elpac_results': {
        'OverallMeanSclScr': 'overall_mean_scale_score',
        'NoviceELPerfLvlPcnt': 'novice_el_perf_lvl_pcnt',
        'NoviceELPerfLvlCount': 'novice_el_perf_lvl_count',
        'IntermediateELPerfLvlPcnt': 'intermediate_el_perf_lvl_pcnt',
        'IntermediateELPerfLvlCount': 'intermediate_el_perf_lvl_count',
        'IFEPPerfLvlPcnt': 'ifep_perf_lvl_pcnt',
        'IFEPPerfLvlCount': 'ifep_perf_lvl_count',
        'OralLangMinimallyDevelopedPerfLvlPcnt': 'oral_lang_minimally_developed_perf_lvl_pcnt',
        'OralLangMinimallyDevelopedPerfLvlCount': 'oral_lang_minimally_developed_perf_lvl_count',
        'OralLangModeratelyDevelopedPerfLvlPcnt': 'oral_lang_moderately_developed_perf_lvl_pcnt',
        'OralLangModeratelyDevelopedPerfLvlCount': 'oral_lang_moderately_developed_perf_lvl_count',
        'OralLangWellDevelopedPerfLvlPcnt': 'oral_lang_well_developed_perf_lvl_pcnt',
        'OralLangWellDevelopedPerfLvlCount': 'oral_lang_well_developed_perf_lvl_count',
        'OralLangTotal': 'oral_lang_total',
        'WritLangMinimallyDevelopedPerfLvlPcnt': 'writ_lang_minimally_developed_perf_lvl_pcnt',
        'WritLangMinimallyDevelopedPerfLvlCount': 'writ_lang_minimally_developed_perf_lvl_count',
        'WritLangModeratelyDevelopedPerfLvlPcnt': 'writ_lang_moderately_developed_perf_lvl_pcnt',
        'WritLangModeratelyDevelopedPerfLvlCount': 'writ_lang_moderately_developed_perf_lvl_count',
        'WritLangWellDevelopedPerfLvlPcnt': 'writ_lang_well_developed_perf_lvl_pcnt',
        'WritLangWellDevelopedPerfLvlCount': 'writ_lang_well_developed_perf_lvl_count',
        'WritLangTotal': 'writ_lang_total',
    },
    'altia_elpac_results': {
        'OverallMeanScaleScore': 'overall_mean_scale_score',
        'OverallPerfLvl1Pcnt': 'overall_perf_lvl_pcnt_1',
        'OverallPerfLvl1Count': 'overall_perf_lvl_count_1',
        'OverallPerfLvl2Pcnt': 'overall_perf_lvl_pcnt_2',
        'OverallPerfLvl2Count': 'overall_perf_lvl_count_2',
        'OverallPerfLvl3Pcnt': 'overall_perf_lvl_pcnt_3',
        'OverallPerfLvl3Count': 'overall_perf_lvl_count_3',
        'OverallPerfLvl4Pcnt': 'overall_perf_lvl_pcnt_4',
        'OverallPerfLvl4Count': 'overall_perf_lvl_count_4',
        'OralLangMeanScaleScore': 'oral_lang_mean_scale_score',
        'OralLangPerfLvl1Pcnt': 'oral_lang_perf_lvl_pcnt_1',
        'OralLangPerfLvl1Count': 'oral_lang_perf_lvl_count_1',
        'OralLangPerfLvl2Pcnt': 'oral_lang_perf_lvl_pcnt_2',
        'OralLangPerfLvl2Count': 'oral_lang_perf_lvl_count_2',
        'OralLangPerfLvl3Pcnt': 'oral_lang_perf_lvl_pcnt_3',
        'OralLangPerfLvl3Count': 'oral_lang_perf_lvl_count_3',
        'OralLangPerfLvl4Pcnt': 'oral_lang_perf_lvl_pcnt_4',
        'OralLangPerfLvl4Count': 'oral_lang_perf_lvl_count_4',
        'OralLangTotal': 'oral_lang_total',
        'WritLangMeanScaleScore': 'writ_lang_mean_scale_score',
        'WritLangPerfLvl1Pcnt': 'writ_lang_perf_lvl_pcnt_1',
        'WritLangPerfLvl1Count': 'writ_lang_perf_lvl_count_1',
        'WritLangPerfLvl2Pcnt': 'writ_lang_perf_lvl_pcnt_2',
        'WritLangPerfLvl2Count': 'writ_lang_perf_lvl_count_2',
        'WritLangPerfLvl3Pcnt': 'writ_lang_perf_lvl_pcnt_3',
        'WritLangPerfLvl3Count': 'writ_lang_perf_lvl_count_3',
        'WritLangPerfLvl4Pcnt': 'writ_lang_perf_lvl_pcnt_4',
        'WritLangPerfLvl4Count': 'writ_lang_perf_lvl_count_4',
        'WritLangTotal': 'writ_lang_total',
    },
    'sa_elpac_results': {
        'OverallMeanScaleScore': 'overall_mean_scale_score',
        'OverallPerfLvl1Pcnt': 'overall_perf_lvl_pcnt_1',
        'OverallPerfLvl1Count': 'overall_perf_lvl_count_1',
        'OverallPerfLvl2Pcnt': 'overall_perf_lvl_pcnt_2',
        'OverallPerfLvl2Count': 'overall_perf_lvl_count_2',
        'OverallPerfLvl3Pcnt': 'overall_perf_lvl_pcnt_3',
        'OverallPerfLvl3Count': 'overall_perf_lvl_count_3',
        'OverallPerfLvl4Pcnt': 'overall_perf_lvl_pcnt_4',
        'OverallPerfLvl4Count': 'overall_perf_lvl_count_4',
        'OralLangMeanScaleScore': 'oral_lang_mean_scale_score',
        'OralLangPerfLvl1Count': 'oral_lang_perf_lvl_count_1',
        'OralLangPerfLvl1Pcnt': 'oral_lang_perf_lvl_pcnt_1',
        'OralLangPerfLvl2Count': 'oral_lang_perf_lvl_count_2',
        'OralLangPerfLvl2Pcnt': 'oral_lang_perf_lvl_pcnt_2',
        'OralLangPerfLvl3Count': 'oral_lang_perf_lvl_count_3',
        'OralLangPerfLvl3Pcnt': 'oral_lang_perf_lvl_pcnt_3',
        'OralLangPerfLvl4Count': 'oral_lang_perf_lvl_count_4',
        'OralLangPerfLvl4Pcnt': 'oral_lang_perf_lvl_pcnt_4',
        'OralLangTotal': 'oral_lang_total',
        'WritLangMeanScaleScore': 'writ_lang_mean_scale_score',
        'WritLangPerfLvl1Count': 'writ_lang_perf_lvl_count_1',
        'WritLangPerfLvl1Pcnt': 'writ_lang_perf_lvl_pcnt_1',
        'WritLangPerfLvl2Count': 'writ_lang_perf_lvl_count_2',
        'WritLangPerfLvl2Pcnt': 'writ_lang_perf_lvl_pcnt_2',
        'WritLangPerfLvl3Count': 'writ_lang_perf_lvl_count_3',
        'WritLangPerfLvl3Pcnt': 'writ_lang_perf_lvl_pcnt_3',
        'WritLangPerfLvl4Count': 'writ_lang_perf_lvl_count_4',
        'WritLangPerfLvl4Pcnt': 'writ_lang_perf_lvl_pcnt_4',
        'WritLangTotal': 'writ_lang_total',
    },
    'altsa_elpac_results': {
        'OverallMeanScaleScore': 'overall_mean_scale_score',
        'OverallPerfLvl1Pcnt': 'overall_perf_lvl_pcnt_1',
        'OverallPerfLvl1Count': 'count_level_1',
        'OverallPerfLvl2Pcnt': 'overall_perf_lvl_pcnt_2',
        'OverallPerfLvl2Count': 'count_level_2',
        'OverallPerfLvl3Pcnt': 'overall_perf_lvl_pcnt_3',
        'OverallPerfLvl3Count': 'count_level_3',
    },
}

DASHBOARD_INDEXES: tuple[tuple[str, str], ...] = (
    ("sb_results", "ix_sb_results_cds_year_test"),
    ("cast_results", "ix_cast_results_cds_year_test"),
    ("ia_elpac_results", "ix_ia_elpac_results_cds_year_test"),
)


def upgrade() -> None:
    for table, columns in RENAMES.items():
        for legacy_name, normalized_name in columns.items():
            op.alter_column(table, legacy_name, new_column_name=normalized_name)

    for table, index_name in DASHBOARD_INDEXES:
        op.create_index(
            index_name, table, ["cds_code", "test_year", "test_id"], unique=False
        )


def downgrade() -> None:
    for table, index_name in DASHBOARD_INDEXES:
        op.drop_index(index_name, table_name=table)

    for table, columns in RENAMES.items():
        for legacy_name, normalized_name in columns.items():
            op.alter_column(table, normalized_name, new_column_name=legacy_name)
