"""Update CensusData model with new fields

Revision ID: abbe6b667292
Revises: 74673f8651ca
Create Date: 2025-08-10 09:27:46.345244

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'abbe6b667292'
down_revision = '74673f8651ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('censusdata', sa.Column('schl_id', sa.Uuid(), nullable=False))
    op.add_column('censusdata', sa.Column('academic_year', sa.Integer(), nullable=False))
    op.add_column('censusdata', sa.Column('aggregation_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('censusdata', sa.Column('county_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('censusdata', sa.Column('district_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('censusdata', sa.Column('school_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('censusdata', sa.Column('county_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('censusdata', sa.Column('district_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('censusdata', sa.Column('charter', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('censusdata', sa.Column('reporting_category', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('censusdata', sa.Column('total_enr', sa.Integer(), nullable=False))
    op.add_column('censusdata', sa.Column('gr_tk', sa.Integer(), nullable=False))
    op.add_column('censusdata', sa.Column('gr_kn', sa.Integer(), nullable=False))
    op.add_column('censusdata', sa.Column('gr_1', sa.Integer(), nullable=False))
    op.add_column('censusdata', sa.Column('gr_2', sa.Integer(), nullable=False))
    op.add_column('censusdata', sa.Column('gr_3', sa.Integer(), nullable=False))
    op.add_column('censusdata', sa.Column('gr_4', sa.Integer(), nullable=False))
    op.add_column('censusdata', sa.Column('gr_5', sa.Integer(), nullable=False))
    op.add_column('censusdata', sa.Column('gr_6', sa.Integer(), nullable=False))
    op.add_column('censusdata', sa.Column('gr_7', sa.Integer(), nullable=False))
    op.add_column('censusdata', sa.Column('gr_8', sa.Integer(), nullable=False))
    op.add_column('censusdata', sa.Column('gr_9', sa.Integer(), nullable=False))
    op.add_column('censusdata', sa.Column('gr_10', sa.Integer(), nullable=False))
    op.add_column('censusdata', sa.Column('gr_11', sa.Integer(), nullable=False))
    op.add_column('censusdata', sa.Column('gr_12', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_censusdata_academic_year'), 'censusdata', ['academic_year'], unique=False)
    op.create_index(op.f('ix_censusdata_aggregation_level'), 'censusdata', ['aggregation_level'], unique=False)
    op.create_index(op.f('ix_censusdata_county_code'), 'censusdata', ['county_code'], unique=False)
    op.create_index(op.f('ix_censusdata_district_code'), 'censusdata', ['district_code'], unique=False)
    op.create_index(op.f('ix_censusdata_school_code'), 'censusdata', ['school_code'], unique=False)
    op.drop_column('censusdata', 'student_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('censusdata', sa.Column('student_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_censusdata_school_code'), table_name='censusdata')
    op.drop_index(op.f('ix_censusdata_district_code'), table_name='censusdata')
    op.drop_index(op.f('ix_censusdata_county_code'), table_name='censusdata')
    op.drop_index(op.f('ix_censusdata_aggregation_level'), table_name='censusdata')
    op.drop_index(op.f('ix_censusdata_academic_year'), table_name='censusdata')
    op.drop_column('censusdata', 'gr_12')
    op.drop_column('censusdata', 'gr_11')
    op.drop_column('censusdata', 'gr_10')
    op.drop_column('censusdata', 'gr_9')
    op.drop_column('censusdata', 'gr_8')
    op.drop_column('censusdata', 'gr_7')
    op.drop_column('censusdata', 'gr_6')
    op.drop_column('censusdata', 'gr_5')
    op.drop_column('censusdata', 'gr_4')
    op.drop_column('censusdata', 'gr_3')
    op.drop_column('censusdata', 'gr_2')
    op.drop_column('censusdata', 'gr_1')
    op.drop_column('censusdata', 'gr_kn')
    op.drop_column('censusdata', 'gr_tk')
    op.drop_column('censusdata', 'total_enr')
    op.drop_column('censusdata', 'reporting_category')
    op.drop_column('censusdata', 'charter')
    op.drop_column('censusdata', 'district_name')
    op.drop_column('censusdata', 'county_name')
    op.drop_column('censusdata', 'school_code')
    op.drop_column('censusdata', 'district_code')
    op.drop_column('censusdata', 'county_code')
    op.drop_column('censusdata', 'aggregation_level')
    op.drop_column('censusdata', 'academic_year')
    op.drop_column('censusdata', 'schl_id')
    # ### end Alembic commands ###
