"""Add Dashboard accountability layer

Revision ID: d8715d3c4ed9
Revises: 7b82316000d2
Create Date: 2026-08-31 09:21:36.895691

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8715d3c4ed9'
down_revision = '7b82316000d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_indicators',
                    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
                    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
                    sa.Column('lower_is_better', sa.Boolean(), nullable=False),
                    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('sort_order', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('code')
                    )
    op.create_table('dashboard_color_cells',
                    sa.Column('indicator_code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
                    sa.Column('variant', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
                    sa.Column('small_denominator', sa.Boolean(), nullable=False),
                    sa.Column('status_level', sa.Integer(), nullable=False),
                    sa.Column('change_level', sa.Integer(), nullable=False),
                    sa.Column('color', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['indicator_code'], ['dashboard_indicators.code'], ),
                    sa.PrimaryKeyConstraint('indicator_code', 'variant', 'small_denominator', 'status_level',
                                            'change_level')
                    )
    op.create_table('dashboard_cutpoints',
                    sa.Column('indicator_code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
                    sa.Column('variant', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
                    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
                    sa.Column('level', sa.Integer(), nullable=False),
                    sa.Column('lower_bound', sa.Numeric(precision=8, scale=2), nullable=True),
                    sa.Column('upper_bound', sa.Numeric(precision=8, scale=2), nullable=True),
                    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
                    sa.ForeignKeyConstraint(['indicator_code'], ['dashboard_indicators.code'], ),
                    sa.PrimaryKeyConstraint('indicator_code', 'variant', 'kind', 'level')
                    )
    op.create_table('dashboard_indicator_results',
                    sa.Column('cds_code', sqlmodel.sql.sqltypes.AutoString(length=14), nullable=False),
                    sa.Column('reporting_year', sa.Integer(), nullable=False),
                    sa.Column('indicator_code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
                    sa.Column('student_group_code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
                    sa.Column('variant', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
                    sa.Column('curr_numerator', sa.Integer(), nullable=True),
                    sa.Column('curr_denominator', sa.Integer(), nullable=True),
                    sa.Column('prior_numerator', sa.Integer(), nullable=True),
                    sa.Column('prior_denominator', sa.Integer(), nullable=True),
                    sa.Column('curr_status', sa.Numeric(precision=8, scale=2), nullable=True),
                    sa.Column('prior_status', sa.Numeric(precision=8, scale=2), nullable=True),
                    sa.Column('change', sa.Numeric(precision=8, scale=2), nullable=True),
                    sa.Column('status_level', sa.Integer(), nullable=True),
                    sa.Column('change_level', sa.Integer(), nullable=True),
                    sa.Column('color', sa.Integer(), nullable=True),
                    sa.Column('box', sa.Integer(), nullable=True),
                    sa.Column('curr_nsize_met', sa.Boolean(), nullable=False),
                    sa.Column('prior_nsize_met', sa.Boolean(), nullable=False),
                    sa.Column('accountability_met', sa.Boolean(), nullable=False),
                    sa.Column('small_denominator', sa.Boolean(), nullable=False),
                    sa.Column('charter_flag', sa.Boolean(), nullable=False),
                    sa.Column('coe_flag', sa.Boolean(), nullable=False),
                    sa.Column('dass_flag', sa.Boolean(), nullable=False),
                    sa.Column('is_projected', sa.Boolean(), nullable=False),
                    sa.Column('projection_basis', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
                    sa.Column('source_extras', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.ForeignKeyConstraint(['cds_code'], ['entities.cds_code'], ),
                    sa.ForeignKeyConstraint(['indicator_code'], ['dashboard_indicators.code'], ),
                    sa.PrimaryKeyConstraint('cds_code', 'reporting_year', 'indicator_code', 'student_group_code',
                                            'variant')
                    )
    op.create_index('ix_dashboard_lookup', 'dashboard_indicator_results',
                    ['reporting_year', 'indicator_code', 'student_group_code', 'cds_code'], unique=False)
    op.alter_column('ingest_files', 'test_type',
                    existing_type=sa.VARCHAR(length=5),
                    type_=sqlmodel.sql.sqltypes.AutoString(length=10),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingest_files', 'test_type',
                    existing_type=sqlmodel.sql.sqltypes.AutoString(length=10),
                    type_=sa.VARCHAR(length=5),
                    existing_nullable=True)
    op.drop_index('ix_dashboard_lookup', table_name='dashboard_indicator_results')
    op.drop_table('dashboard_indicator_results')
    op.drop_table('dashboard_cutpoints')
    op.drop_table('dashboard_color_cells')
    op.drop_table('dashboard_indicators')
    # ### end Alembic commands ###
