"""Check schema after model refactoring

Revision ID: eb18e3ec8487
Revises: f5a83e87d6ee
Create Date: 2025-08-10 19:52:20.647288

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'eb18e3ec8487'
down_revision = 'f5a83e87d6ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
