/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/_status'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as ReportIndexRouteImport } from './routes/report/index'
import { Route as Dashboard2IndexRouteImport } from './routes/dashboard2/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as UserSettingsRouteImport } from './routes/user/settings'
import { Route as UserItemsRouteImport } from './routes/user/items'
import { Route as UserAdminRouteImport } from './routes/user/admin'
import { Route as UserLayoutRouteImport } from './routes/user/_layout'
import { Route as PrivatePrivateRouteImport } from './routes/private/_private'
import { Route as StatusWelcomeRouteImport } from './routes/_status/welcome'
import { Route as StatusWebhookConfiguredRouteImport } from './routes/_status/webhook-configured'
import { Route as StatusVerifyEmailRouteImport } from './routes/_status/verify-email'
import { Route as StatusUpgradeSuccessRouteImport } from './routes/_status/upgrade-success'
import { Route as StatusUnsupportedMediaRouteImport } from './routes/_status/unsupported-media'
import { Route as StatusUnderConstructionRouteImport } from './routes/_status/under-construction'
import { Route as StatusTimeoutRouteImport } from './routes/_status/timeout'
import { Route as StatusSuccessStatesRouteImport } from './routes/_status/success-states'
import { Route as StatusSuccessRouteImport } from './routes/_status/success'
import { Route as StatusSubscriptionCancelledRouteImport } from './routes/_status/subscription-cancelled'
import { Route as StatusStatusRouteImport } from './routes/_status/status'
import { Route as StatusSessionExpiredRouteImport } from './routes/_status/session-expired'
import { Route as StatusRateLimitedRouteImport } from './routes/_status/rate-limited'
import { Route as StatusQueuedRouteImport } from './routes/_status/queued'
import { Route as StatusProcessingRouteImport } from './routes/_status/processing'
import { Route as StatusPaymentRequiredRouteImport } from './routes/_status/payment-required'
import { Route as StatusPasswordChangedRouteImport } from './routes/_status/password-changed'
import { Route as StatusOfflineRouteImport } from './routes/_status/offline'
import { Route as StatusNoResultsRouteImport } from './routes/_status/no-results'
import { Route as StatusMaintenanceRouteImport } from './routes/_status/maintenance'
import { Route as StatusLoginRequiredRouteImport } from './routes/_status/login-required'
import { Route as StatusLockedRouteImport } from './routes/_status/locked'
import { Route as StatusLoadingRouteImport } from './routes/_status/loading'
import { Route as StatusInvitationRouteImport } from './routes/_status/invitation'
import { Route as StatusInfoStatesRouteImport } from './routes/_status/info-states'
import { Route as StatusImportCompleteRouteImport } from './routes/_status/import-complete'
import { Route as StatusGoneRouteImport } from './routes/_status/gone'
import { Route as StatusGatewayTimeoutRouteImport } from './routes/_status/gateway-timeout'
import { Route as StatusExportReadyRouteImport } from './routes/_status/export-ready'
import { Route as StatusErrorDemoRouteImport } from './routes/_status/error-demo'
import { Route as StatusErrorRouteImport } from './routes/_status/error'
import { Route as StatusEmptyStateRouteImport } from './routes/_status/empty-state'
import { Route as StatusEmailSentRouteImport } from './routes/_status/email-sent'
import { Route as StatusDowngradeRouteImport } from './routes/_status/downgrade'
import { Route as StatusDeviceVerifiedRouteImport } from './routes/_status/device-verified'
import { Route as StatusDeletedRouteImport } from './routes/_status/deleted'
import { Route as StatusConflictRouteImport } from './routes/_status/conflict'
import { Route as StatusComingSoonRouteImport } from './routes/_status/coming-soon'
import { Route as StatusCancelledRouteImport } from './routes/_status/cancelled'
import { Route as StatusBandwidthExceededRouteImport } from './routes/_status/bandwidth-exceeded'
import { Route as StatusBadRequestRouteImport } from './routes/_status/bad-request'
import { Route as StatusBadGatewayRouteImport } from './routes/_status/bad-gateway'
import { Route as StatusBackupCompleteRouteImport } from './routes/_status/backup-complete'
import { Route as StatusApiKeyCreatedRouteImport } from './routes/_status/api-key-created'
import { Route as Status503RouteImport } from './routes/_status/503'
import { Route as Status500RouteImport } from './routes/_status/500'
import { Route as Status404RouteImport } from './routes/_status/404'
import { Route as Status403RouteImport } from './routes/_status/403'
import { Route as Status401RouteImport } from './routes/_status/401'
import { Route as Status2faRequiredRouteImport } from './routes/_status/2fa-required'
import { Route as Status2faEnabledRouteImport } from './routes/_status/2fa-enabled'
import { Route as DeprecatedHomeRouteImport } from './routes/_deprecated/home'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRecoverPasswordRouteImport } from './routes/_auth/recover-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'

const StatusRoute = StatusRouteImport.update({
  id: '/_status',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIndexRoute = ReportIndexRouteImport.update({
  id: '/report/',
  path: '/report/',
  getParentRoute: () => rootRouteImport,
} as any)
const Dashboard2IndexRoute = Dashboard2IndexRouteImport.update({
  id: '/dashboard2/',
  path: '/dashboard2/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/user/settings',
  path: '/user/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UserItemsRoute = UserItemsRouteImport.update({
  id: '/user/items',
  path: '/user/items',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAdminRoute = UserAdminRouteImport.update({
  id: '/user/admin',
  path: '/user/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLayoutRoute = UserLayoutRouteImport.update({
  id: '/user/_layout',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatePrivateRoute = PrivatePrivateRouteImport.update({
  id: '/private/_private',
  path: '/private',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusWelcomeRoute = StatusWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => StatusRoute,
} as any)
const StatusWebhookConfiguredRoute = StatusWebhookConfiguredRouteImport.update({
  id: '/webhook-configured',
  path: '/webhook-configured',
  getParentRoute: () => StatusRoute,
} as any)
const StatusVerifyEmailRoute = StatusVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => StatusRoute,
} as any)
const StatusUpgradeSuccessRoute = StatusUpgradeSuccessRouteImport.update({
  id: '/upgrade-success',
  path: '/upgrade-success',
  getParentRoute: () => StatusRoute,
} as any)
const StatusUnsupportedMediaRoute = StatusUnsupportedMediaRouteImport.update({
  id: '/unsupported-media',
  path: '/unsupported-media',
  getParentRoute: () => StatusRoute,
} as any)
const StatusUnderConstructionRoute = StatusUnderConstructionRouteImport.update({
  id: '/under-construction',
  path: '/under-construction',
  getParentRoute: () => StatusRoute,
} as any)
const StatusTimeoutRoute = StatusTimeoutRouteImport.update({
  id: '/timeout',
  path: '/timeout',
  getParentRoute: () => StatusRoute,
} as any)
const StatusSuccessStatesRoute = StatusSuccessStatesRouteImport.update({
  id: '/success-states',
  path: '/success-states',
  getParentRoute: () => StatusRoute,
} as any)
const StatusSuccessRoute = StatusSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => StatusRoute,
} as any)
const StatusSubscriptionCancelledRoute =
  StatusSubscriptionCancelledRouteImport.update({
    id: '/subscription-cancelled',
    path: '/subscription-cancelled',
    getParentRoute: () => StatusRoute,
  } as any)
const StatusStatusRoute = StatusStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => StatusRoute,
} as any)
const StatusSessionExpiredRoute = StatusSessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => StatusRoute,
} as any)
const StatusRateLimitedRoute = StatusRateLimitedRouteImport.update({
  id: '/rate-limited',
  path: '/rate-limited',
  getParentRoute: () => StatusRoute,
} as any)
const StatusQueuedRoute = StatusQueuedRouteImport.update({
  id: '/queued',
  path: '/queued',
  getParentRoute: () => StatusRoute,
} as any)
const StatusProcessingRoute = StatusProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => StatusRoute,
} as any)
const StatusPaymentRequiredRoute = StatusPaymentRequiredRouteImport.update({
  id: '/payment-required',
  path: '/payment-required',
  getParentRoute: () => StatusRoute,
} as any)
const StatusPasswordChangedRoute = StatusPasswordChangedRouteImport.update({
  id: '/password-changed',
  path: '/password-changed',
  getParentRoute: () => StatusRoute,
} as any)
const StatusOfflineRoute = StatusOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => StatusRoute,
} as any)
const StatusNoResultsRoute = StatusNoResultsRouteImport.update({
  id: '/no-results',
  path: '/no-results',
  getParentRoute: () => StatusRoute,
} as any)
const StatusMaintenanceRoute = StatusMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => StatusRoute,
} as any)
const StatusLoginRequiredRoute = StatusLoginRequiredRouteImport.update({
  id: '/login-required',
  path: '/login-required',
  getParentRoute: () => StatusRoute,
} as any)
const StatusLockedRoute = StatusLockedRouteImport.update({
  id: '/locked',
  path: '/locked',
  getParentRoute: () => StatusRoute,
} as any)
const StatusLoadingRoute = StatusLoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => StatusRoute,
} as any)
const StatusInvitationRoute = StatusInvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => StatusRoute,
} as any)
const StatusInfoStatesRoute = StatusInfoStatesRouteImport.update({
  id: '/info-states',
  path: '/info-states',
  getParentRoute: () => StatusRoute,
} as any)
const StatusImportCompleteRoute = StatusImportCompleteRouteImport.update({
  id: '/import-complete',
  path: '/import-complete',
  getParentRoute: () => StatusRoute,
} as any)
const StatusGoneRoute = StatusGoneRouteImport.update({
  id: '/gone',
  path: '/gone',
  getParentRoute: () => StatusRoute,
} as any)
const StatusGatewayTimeoutRoute = StatusGatewayTimeoutRouteImport.update({
  id: '/gateway-timeout',
  path: '/gateway-timeout',
  getParentRoute: () => StatusRoute,
} as any)
const StatusExportReadyRoute = StatusExportReadyRouteImport.update({
  id: '/export-ready',
  path: '/export-ready',
  getParentRoute: () => StatusRoute,
} as any)
const StatusErrorDemoRoute = StatusErrorDemoRouteImport.update({
  id: '/error-demo',
  path: '/error-demo',
  getParentRoute: () => StatusRoute,
} as any)
const StatusErrorRoute = StatusErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => StatusRoute,
} as any)
const StatusEmptyStateRoute = StatusEmptyStateRouteImport.update({
  id: '/empty-state',
  path: '/empty-state',
  getParentRoute: () => StatusRoute,
} as any)
const StatusEmailSentRoute = StatusEmailSentRouteImport.update({
  id: '/email-sent',
  path: '/email-sent',
  getParentRoute: () => StatusRoute,
} as any)
const StatusDowngradeRoute = StatusDowngradeRouteImport.update({
  id: '/downgrade',
  path: '/downgrade',
  getParentRoute: () => StatusRoute,
} as any)
const StatusDeviceVerifiedRoute = StatusDeviceVerifiedRouteImport.update({
  id: '/device-verified',
  path: '/device-verified',
  getParentRoute: () => StatusRoute,
} as any)
const StatusDeletedRoute = StatusDeletedRouteImport.update({
  id: '/deleted',
  path: '/deleted',
  getParentRoute: () => StatusRoute,
} as any)
const StatusConflictRoute = StatusConflictRouteImport.update({
  id: '/conflict',
  path: '/conflict',
  getParentRoute: () => StatusRoute,
} as any)
const StatusComingSoonRoute = StatusComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => StatusRoute,
} as any)
const StatusCancelledRoute = StatusCancelledRouteImport.update({
  id: '/cancelled',
  path: '/cancelled',
  getParentRoute: () => StatusRoute,
} as any)
const StatusBandwidthExceededRoute = StatusBandwidthExceededRouteImport.update({
  id: '/bandwidth-exceeded',
  path: '/bandwidth-exceeded',
  getParentRoute: () => StatusRoute,
} as any)
const StatusBadRequestRoute = StatusBadRequestRouteImport.update({
  id: '/bad-request',
  path: '/bad-request',
  getParentRoute: () => StatusRoute,
} as any)
const StatusBadGatewayRoute = StatusBadGatewayRouteImport.update({
  id: '/bad-gateway',
  path: '/bad-gateway',
  getParentRoute: () => StatusRoute,
} as any)
const StatusBackupCompleteRoute = StatusBackupCompleteRouteImport.update({
  id: '/backup-complete',
  path: '/backup-complete',
  getParentRoute: () => StatusRoute,
} as any)
const StatusApiKeyCreatedRoute = StatusApiKeyCreatedRouteImport.update({
  id: '/api-key-created',
  path: '/api-key-created',
  getParentRoute: () => StatusRoute,
} as any)
const Status503Route = Status503RouteImport.update({
  id: '/503',
  path: '/503',
  getParentRoute: () => StatusRoute,
} as any)
const Status500Route = Status500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => StatusRoute,
} as any)
const Status404Route = Status404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => StatusRoute,
} as any)
const Status403Route = Status403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => StatusRoute,
} as any)
const Status401Route = Status401RouteImport.update({
  id: '/401',
  path: '/401',
  getParentRoute: () => StatusRoute,
} as any)
const Status2faRequiredRoute = Status2faRequiredRouteImport.update({
  id: '/2fa-required',
  path: '/2fa-required',
  getParentRoute: () => StatusRoute,
} as any)
const Status2faEnabledRoute = Status2faEnabledRouteImport.update({
  id: '/2fa-enabled',
  path: '/2fa-enabled',
  getParentRoute: () => StatusRoute,
} as any)
const DeprecatedHomeRoute = DeprecatedHomeRouteImport.update({
  id: '/_deprecated/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/_auth/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/_auth/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoverPasswordRoute = AuthRecoverPasswordRouteImport.update({
  id: '/_auth/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/recover-password': typeof AuthRecoverPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-up': typeof AuthSignUpRoute
  '/home': typeof DeprecatedHomeRoute
  '/2fa-enabled': typeof Status2faEnabledRoute
  '/2fa-required': typeof Status2faRequiredRoute
  '/401': typeof Status401Route
  '/403': typeof Status403Route
  '/404': typeof Status404Route
  '/500': typeof Status500Route
  '/503': typeof Status503Route
  '/api-key-created': typeof StatusApiKeyCreatedRoute
  '/backup-complete': typeof StatusBackupCompleteRoute
  '/bad-gateway': typeof StatusBadGatewayRoute
  '/bad-request': typeof StatusBadRequestRoute
  '/bandwidth-exceeded': typeof StatusBandwidthExceededRoute
  '/cancelled': typeof StatusCancelledRoute
  '/coming-soon': typeof StatusComingSoonRoute
  '/conflict': typeof StatusConflictRoute
  '/deleted': typeof StatusDeletedRoute
  '/device-verified': typeof StatusDeviceVerifiedRoute
  '/downgrade': typeof StatusDowngradeRoute
  '/email-sent': typeof StatusEmailSentRoute
  '/empty-state': typeof StatusEmptyStateRoute
  '/error': typeof StatusErrorRoute
  '/error-demo': typeof StatusErrorDemoRoute
  '/export-ready': typeof StatusExportReadyRoute
  '/gateway-timeout': typeof StatusGatewayTimeoutRoute
  '/gone': typeof StatusGoneRoute
  '/import-complete': typeof StatusImportCompleteRoute
  '/info-states': typeof StatusInfoStatesRoute
  '/invitation': typeof StatusInvitationRoute
  '/loading': typeof StatusLoadingRoute
  '/locked': typeof StatusLockedRoute
  '/login-required': typeof StatusLoginRequiredRoute
  '/maintenance': typeof StatusMaintenanceRoute
  '/no-results': typeof StatusNoResultsRoute
  '/offline': typeof StatusOfflineRoute
  '/password-changed': typeof StatusPasswordChangedRoute
  '/payment-required': typeof StatusPaymentRequiredRoute
  '/processing': typeof StatusProcessingRoute
  '/queued': typeof StatusQueuedRoute
  '/rate-limited': typeof StatusRateLimitedRoute
  '/session-expired': typeof StatusSessionExpiredRoute
  '/status': typeof StatusStatusRoute
  '/subscription-cancelled': typeof StatusSubscriptionCancelledRoute
  '/success': typeof StatusSuccessRoute
  '/success-states': typeof StatusSuccessStatesRoute
  '/timeout': typeof StatusTimeoutRoute
  '/under-construction': typeof StatusUnderConstructionRoute
  '/unsupported-media': typeof StatusUnsupportedMediaRoute
  '/upgrade-success': typeof StatusUpgradeSuccessRoute
  '/verify-email': typeof StatusVerifyEmailRoute
  '/webhook-configured': typeof StatusWebhookConfiguredRoute
  '/welcome': typeof StatusWelcomeRoute
  '/private': typeof PrivatePrivateRoute
  '/user': typeof UserLayoutRoute
  '/user/admin': typeof UserAdminRoute
  '/user/items': typeof UserItemsRoute
  '/user/settings': typeof UserSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard2/': typeof Dashboard2IndexRoute
  '/report/': typeof ReportIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/recover-password': typeof AuthRecoverPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-up': typeof AuthSignUpRoute
  '/home': typeof DeprecatedHomeRoute
  '/2fa-enabled': typeof Status2faEnabledRoute
  '/2fa-required': typeof Status2faRequiredRoute
  '/401': typeof Status401Route
  '/403': typeof Status403Route
  '/404': typeof Status404Route
  '/500': typeof Status500Route
  '/503': typeof Status503Route
  '/api-key-created': typeof StatusApiKeyCreatedRoute
  '/backup-complete': typeof StatusBackupCompleteRoute
  '/bad-gateway': typeof StatusBadGatewayRoute
  '/bad-request': typeof StatusBadRequestRoute
  '/bandwidth-exceeded': typeof StatusBandwidthExceededRoute
  '/cancelled': typeof StatusCancelledRoute
  '/coming-soon': typeof StatusComingSoonRoute
  '/conflict': typeof StatusConflictRoute
  '/deleted': typeof StatusDeletedRoute
  '/device-verified': typeof StatusDeviceVerifiedRoute
  '/downgrade': typeof StatusDowngradeRoute
  '/email-sent': typeof StatusEmailSentRoute
  '/empty-state': typeof StatusEmptyStateRoute
  '/error': typeof StatusErrorRoute
  '/error-demo': typeof StatusErrorDemoRoute
  '/export-ready': typeof StatusExportReadyRoute
  '/gateway-timeout': typeof StatusGatewayTimeoutRoute
  '/gone': typeof StatusGoneRoute
  '/import-complete': typeof StatusImportCompleteRoute
  '/info-states': typeof StatusInfoStatesRoute
  '/invitation': typeof StatusInvitationRoute
  '/loading': typeof StatusLoadingRoute
  '/locked': typeof StatusLockedRoute
  '/login-required': typeof StatusLoginRequiredRoute
  '/maintenance': typeof StatusMaintenanceRoute
  '/no-results': typeof StatusNoResultsRoute
  '/offline': typeof StatusOfflineRoute
  '/password-changed': typeof StatusPasswordChangedRoute
  '/payment-required': typeof StatusPaymentRequiredRoute
  '/processing': typeof StatusProcessingRoute
  '/queued': typeof StatusQueuedRoute
  '/rate-limited': typeof StatusRateLimitedRoute
  '/session-expired': typeof StatusSessionExpiredRoute
  '/status': typeof StatusStatusRoute
  '/subscription-cancelled': typeof StatusSubscriptionCancelledRoute
  '/success': typeof StatusSuccessRoute
  '/success-states': typeof StatusSuccessStatesRoute
  '/timeout': typeof StatusTimeoutRoute
  '/under-construction': typeof StatusUnderConstructionRoute
  '/unsupported-media': typeof StatusUnsupportedMediaRoute
  '/upgrade-success': typeof StatusUpgradeSuccessRoute
  '/verify-email': typeof StatusVerifyEmailRoute
  '/webhook-configured': typeof StatusWebhookConfiguredRoute
  '/welcome': typeof StatusWelcomeRoute
  '/private': typeof PrivatePrivateRoute
  '/user': typeof UserIndexRoute
  '/user/admin': typeof UserAdminRoute
  '/user/items': typeof UserItemsRoute
  '/user/settings': typeof UserSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard2': typeof Dashboard2IndexRoute
  '/report': typeof ReportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_status': typeof StatusRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/recover-password': typeof AuthRecoverPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_deprecated/home': typeof DeprecatedHomeRoute
  '/_status/2fa-enabled': typeof Status2faEnabledRoute
  '/_status/2fa-required': typeof Status2faRequiredRoute
  '/_status/401': typeof Status401Route
  '/_status/403': typeof Status403Route
  '/_status/404': typeof Status404Route
  '/_status/500': typeof Status500Route
  '/_status/503': typeof Status503Route
  '/_status/api-key-created': typeof StatusApiKeyCreatedRoute
  '/_status/backup-complete': typeof StatusBackupCompleteRoute
  '/_status/bad-gateway': typeof StatusBadGatewayRoute
  '/_status/bad-request': typeof StatusBadRequestRoute
  '/_status/bandwidth-exceeded': typeof StatusBandwidthExceededRoute
  '/_status/cancelled': typeof StatusCancelledRoute
  '/_status/coming-soon': typeof StatusComingSoonRoute
  '/_status/conflict': typeof StatusConflictRoute
  '/_status/deleted': typeof StatusDeletedRoute
  '/_status/device-verified': typeof StatusDeviceVerifiedRoute
  '/_status/downgrade': typeof StatusDowngradeRoute
  '/_status/email-sent': typeof StatusEmailSentRoute
  '/_status/empty-state': typeof StatusEmptyStateRoute
  '/_status/error': typeof StatusErrorRoute
  '/_status/error-demo': typeof StatusErrorDemoRoute
  '/_status/export-ready': typeof StatusExportReadyRoute
  '/_status/gateway-timeout': typeof StatusGatewayTimeoutRoute
  '/_status/gone': typeof StatusGoneRoute
  '/_status/import-complete': typeof StatusImportCompleteRoute
  '/_status/info-states': typeof StatusInfoStatesRoute
  '/_status/invitation': typeof StatusInvitationRoute
  '/_status/loading': typeof StatusLoadingRoute
  '/_status/locked': typeof StatusLockedRoute
  '/_status/login-required': typeof StatusLoginRequiredRoute
  '/_status/maintenance': typeof StatusMaintenanceRoute
  '/_status/no-results': typeof StatusNoResultsRoute
  '/_status/offline': typeof StatusOfflineRoute
  '/_status/password-changed': typeof StatusPasswordChangedRoute
  '/_status/payment-required': typeof StatusPaymentRequiredRoute
  '/_status/processing': typeof StatusProcessingRoute
  '/_status/queued': typeof StatusQueuedRoute
  '/_status/rate-limited': typeof StatusRateLimitedRoute
  '/_status/session-expired': typeof StatusSessionExpiredRoute
  '/_status/status': typeof StatusStatusRoute
  '/_status/subscription-cancelled': typeof StatusSubscriptionCancelledRoute
  '/_status/success': typeof StatusSuccessRoute
  '/_status/success-states': typeof StatusSuccessStatesRoute
  '/_status/timeout': typeof StatusTimeoutRoute
  '/_status/under-construction': typeof StatusUnderConstructionRoute
  '/_status/unsupported-media': typeof StatusUnsupportedMediaRoute
  '/_status/upgrade-success': typeof StatusUpgradeSuccessRoute
  '/_status/verify-email': typeof StatusVerifyEmailRoute
  '/_status/webhook-configured': typeof StatusWebhookConfiguredRoute
  '/_status/welcome': typeof StatusWelcomeRoute
  '/private/_private': typeof PrivatePrivateRoute
  '/user/_layout': typeof UserLayoutRoute
  '/user/admin': typeof UserAdminRoute
  '/user/items': typeof UserItemsRoute
  '/user/settings': typeof UserSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard2/': typeof Dashboard2IndexRoute
  '/report/': typeof ReportIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/sign-up'
    | '/home'
    | '/2fa-enabled'
    | '/2fa-required'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/api-key-created'
    | '/backup-complete'
    | '/bad-gateway'
    | '/bad-request'
    | '/bandwidth-exceeded'
    | '/cancelled'
    | '/coming-soon'
    | '/conflict'
    | '/deleted'
    | '/device-verified'
    | '/downgrade'
    | '/email-sent'
    | '/empty-state'
    | '/error'
    | '/error-demo'
    | '/export-ready'
    | '/gateway-timeout'
    | '/gone'
    | '/import-complete'
    | '/info-states'
    | '/invitation'
    | '/loading'
    | '/locked'
    | '/login-required'
    | '/maintenance'
    | '/no-results'
    | '/offline'
    | '/password-changed'
    | '/payment-required'
    | '/processing'
    | '/queued'
    | '/rate-limited'
    | '/session-expired'
    | '/status'
    | '/subscription-cancelled'
    | '/success'
    | '/success-states'
    | '/timeout'
    | '/under-construction'
    | '/unsupported-media'
    | '/upgrade-success'
    | '/verify-email'
    | '/webhook-configured'
    | '/welcome'
    | '/private'
    | '/user'
    | '/user/admin'
    | '/user/items'
    | '/user/settings'
    | '/dashboard/'
    | '/dashboard2/'
    | '/report/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/sign-up'
    | '/home'
    | '/2fa-enabled'
    | '/2fa-required'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/api-key-created'
    | '/backup-complete'
    | '/bad-gateway'
    | '/bad-request'
    | '/bandwidth-exceeded'
    | '/cancelled'
    | '/coming-soon'
    | '/conflict'
    | '/deleted'
    | '/device-verified'
    | '/downgrade'
    | '/email-sent'
    | '/empty-state'
    | '/error'
    | '/error-demo'
    | '/export-ready'
    | '/gateway-timeout'
    | '/gone'
    | '/import-complete'
    | '/info-states'
    | '/invitation'
    | '/loading'
    | '/locked'
    | '/login-required'
    | '/maintenance'
    | '/no-results'
    | '/offline'
    | '/password-changed'
    | '/payment-required'
    | '/processing'
    | '/queued'
    | '/rate-limited'
    | '/session-expired'
    | '/status'
    | '/subscription-cancelled'
    | '/success'
    | '/success-states'
    | '/timeout'
    | '/under-construction'
    | '/unsupported-media'
    | '/upgrade-success'
    | '/verify-email'
    | '/webhook-configured'
    | '/welcome'
    | '/private'
    | '/user'
    | '/user/admin'
    | '/user/items'
    | '/user/settings'
    | '/dashboard'
    | '/dashboard2'
    | '/report'
  id:
    | '__root__'
    | '/'
    | '/_status'
    | '/_auth/login'
    | '/_auth/recover-password'
    | '/_auth/reset-password'
    | '/_auth/sign-up'
    | '/_deprecated/home'
    | '/_status/2fa-enabled'
    | '/_status/2fa-required'
    | '/_status/401'
    | '/_status/403'
    | '/_status/404'
    | '/_status/500'
    | '/_status/503'
    | '/_status/api-key-created'
    | '/_status/backup-complete'
    | '/_status/bad-gateway'
    | '/_status/bad-request'
    | '/_status/bandwidth-exceeded'
    | '/_status/cancelled'
    | '/_status/coming-soon'
    | '/_status/conflict'
    | '/_status/deleted'
    | '/_status/device-verified'
    | '/_status/downgrade'
    | '/_status/email-sent'
    | '/_status/empty-state'
    | '/_status/error'
    | '/_status/error-demo'
    | '/_status/export-ready'
    | '/_status/gateway-timeout'
    | '/_status/gone'
    | '/_status/import-complete'
    | '/_status/info-states'
    | '/_status/invitation'
    | '/_status/loading'
    | '/_status/locked'
    | '/_status/login-required'
    | '/_status/maintenance'
    | '/_status/no-results'
    | '/_status/offline'
    | '/_status/password-changed'
    | '/_status/payment-required'
    | '/_status/processing'
    | '/_status/queued'
    | '/_status/rate-limited'
    | '/_status/session-expired'
    | '/_status/status'
    | '/_status/subscription-cancelled'
    | '/_status/success'
    | '/_status/success-states'
    | '/_status/timeout'
    | '/_status/under-construction'
    | '/_status/unsupported-media'
    | '/_status/upgrade-success'
    | '/_status/verify-email'
    | '/_status/webhook-configured'
    | '/_status/welcome'
    | '/private/_private'
    | '/user/_layout'
    | '/user/admin'
    | '/user/items'
    | '/user/settings'
    | '/dashboard/'
    | '/dashboard2/'
    | '/report/'
    | '/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatusRoute: typeof StatusRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecoverPasswordRoute: typeof AuthRecoverPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  DeprecatedHomeRoute: typeof DeprecatedHomeRoute
  PrivatePrivateRoute: typeof PrivatePrivateRoute
  UserLayoutRoute: typeof UserLayoutRoute
  UserAdminRoute: typeof UserAdminRoute
  UserItemsRoute: typeof UserItemsRoute
  UserSettingsRoute: typeof UserSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  Dashboard2IndexRoute: typeof Dashboard2IndexRoute
  ReportIndexRoute: typeof ReportIndexRoute
  UserIndexRoute: typeof UserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_status': {
      id: '/_status'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/': {
      id: '/report/'
      path: '/report'
      fullPath: '/report/'
      preLoaderRoute: typeof ReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard2/': {
      id: '/dashboard2/'
      path: '/dashboard2'
      fullPath: '/dashboard2/'
      preLoaderRoute: typeof Dashboard2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/settings': {
      id: '/user/settings'
      path: '/user/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/items': {
      id: '/user/items'
      path: '/user/items'
      fullPath: '/user/items'
      preLoaderRoute: typeof UserItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/admin': {
      id: '/user/admin'
      path: '/user/admin'
      fullPath: '/user/admin'
      preLoaderRoute: typeof UserAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/_layout': {
      id: '/user/_layout'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private/_private': {
      id: '/private/_private'
      path: '/private'
      fullPath: '/private'
      preLoaderRoute: typeof PrivatePrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_status/welcome': {
      id: '/_status/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof StatusWelcomeRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/webhook-configured': {
      id: '/_status/webhook-configured'
      path: '/webhook-configured'
      fullPath: '/webhook-configured'
      preLoaderRoute: typeof StatusWebhookConfiguredRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/verify-email': {
      id: '/_status/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof StatusVerifyEmailRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/upgrade-success': {
      id: '/_status/upgrade-success'
      path: '/upgrade-success'
      fullPath: '/upgrade-success'
      preLoaderRoute: typeof StatusUpgradeSuccessRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/unsupported-media': {
      id: '/_status/unsupported-media'
      path: '/unsupported-media'
      fullPath: '/unsupported-media'
      preLoaderRoute: typeof StatusUnsupportedMediaRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/under-construction': {
      id: '/_status/under-construction'
      path: '/under-construction'
      fullPath: '/under-construction'
      preLoaderRoute: typeof StatusUnderConstructionRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/timeout': {
      id: '/_status/timeout'
      path: '/timeout'
      fullPath: '/timeout'
      preLoaderRoute: typeof StatusTimeoutRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/success-states': {
      id: '/_status/success-states'
      path: '/success-states'
      fullPath: '/success-states'
      preLoaderRoute: typeof StatusSuccessStatesRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/success': {
      id: '/_status/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof StatusSuccessRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/subscription-cancelled': {
      id: '/_status/subscription-cancelled'
      path: '/subscription-cancelled'
      fullPath: '/subscription-cancelled'
      preLoaderRoute: typeof StatusSubscriptionCancelledRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/status': {
      id: '/_status/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusStatusRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/session-expired': {
      id: '/_status/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof StatusSessionExpiredRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/rate-limited': {
      id: '/_status/rate-limited'
      path: '/rate-limited'
      fullPath: '/rate-limited'
      preLoaderRoute: typeof StatusRateLimitedRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/queued': {
      id: '/_status/queued'
      path: '/queued'
      fullPath: '/queued'
      preLoaderRoute: typeof StatusQueuedRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/processing': {
      id: '/_status/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof StatusProcessingRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/payment-required': {
      id: '/_status/payment-required'
      path: '/payment-required'
      fullPath: '/payment-required'
      preLoaderRoute: typeof StatusPaymentRequiredRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/password-changed': {
      id: '/_status/password-changed'
      path: '/password-changed'
      fullPath: '/password-changed'
      preLoaderRoute: typeof StatusPasswordChangedRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/offline': {
      id: '/_status/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof StatusOfflineRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/no-results': {
      id: '/_status/no-results'
      path: '/no-results'
      fullPath: '/no-results'
      preLoaderRoute: typeof StatusNoResultsRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/maintenance': {
      id: '/_status/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof StatusMaintenanceRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/login-required': {
      id: '/_status/login-required'
      path: '/login-required'
      fullPath: '/login-required'
      preLoaderRoute: typeof StatusLoginRequiredRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/locked': {
      id: '/_status/locked'
      path: '/locked'
      fullPath: '/locked'
      preLoaderRoute: typeof StatusLockedRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/loading': {
      id: '/_status/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof StatusLoadingRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/invitation': {
      id: '/_status/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof StatusInvitationRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/info-states': {
      id: '/_status/info-states'
      path: '/info-states'
      fullPath: '/info-states'
      preLoaderRoute: typeof StatusInfoStatesRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/import-complete': {
      id: '/_status/import-complete'
      path: '/import-complete'
      fullPath: '/import-complete'
      preLoaderRoute: typeof StatusImportCompleteRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/gone': {
      id: '/_status/gone'
      path: '/gone'
      fullPath: '/gone'
      preLoaderRoute: typeof StatusGoneRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/gateway-timeout': {
      id: '/_status/gateway-timeout'
      path: '/gateway-timeout'
      fullPath: '/gateway-timeout'
      preLoaderRoute: typeof StatusGatewayTimeoutRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/export-ready': {
      id: '/_status/export-ready'
      path: '/export-ready'
      fullPath: '/export-ready'
      preLoaderRoute: typeof StatusExportReadyRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/error-demo': {
      id: '/_status/error-demo'
      path: '/error-demo'
      fullPath: '/error-demo'
      preLoaderRoute: typeof StatusErrorDemoRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/error': {
      id: '/_status/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof StatusErrorRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/empty-state': {
      id: '/_status/empty-state'
      path: '/empty-state'
      fullPath: '/empty-state'
      preLoaderRoute: typeof StatusEmptyStateRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/email-sent': {
      id: '/_status/email-sent'
      path: '/email-sent'
      fullPath: '/email-sent'
      preLoaderRoute: typeof StatusEmailSentRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/downgrade': {
      id: '/_status/downgrade'
      path: '/downgrade'
      fullPath: '/downgrade'
      preLoaderRoute: typeof StatusDowngradeRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/device-verified': {
      id: '/_status/device-verified'
      path: '/device-verified'
      fullPath: '/device-verified'
      preLoaderRoute: typeof StatusDeviceVerifiedRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/deleted': {
      id: '/_status/deleted'
      path: '/deleted'
      fullPath: '/deleted'
      preLoaderRoute: typeof StatusDeletedRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/conflict': {
      id: '/_status/conflict'
      path: '/conflict'
      fullPath: '/conflict'
      preLoaderRoute: typeof StatusConflictRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/coming-soon': {
      id: '/_status/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof StatusComingSoonRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/cancelled': {
      id: '/_status/cancelled'
      path: '/cancelled'
      fullPath: '/cancelled'
      preLoaderRoute: typeof StatusCancelledRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/bandwidth-exceeded': {
      id: '/_status/bandwidth-exceeded'
      path: '/bandwidth-exceeded'
      fullPath: '/bandwidth-exceeded'
      preLoaderRoute: typeof StatusBandwidthExceededRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/bad-request': {
      id: '/_status/bad-request'
      path: '/bad-request'
      fullPath: '/bad-request'
      preLoaderRoute: typeof StatusBadRequestRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/bad-gateway': {
      id: '/_status/bad-gateway'
      path: '/bad-gateway'
      fullPath: '/bad-gateway'
      preLoaderRoute: typeof StatusBadGatewayRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/backup-complete': {
      id: '/_status/backup-complete'
      path: '/backup-complete'
      fullPath: '/backup-complete'
      preLoaderRoute: typeof StatusBackupCompleteRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/api-key-created': {
      id: '/_status/api-key-created'
      path: '/api-key-created'
      fullPath: '/api-key-created'
      preLoaderRoute: typeof StatusApiKeyCreatedRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/503': {
      id: '/_status/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof Status503RouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/500': {
      id: '/_status/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof Status500RouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/404': {
      id: '/_status/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof Status404RouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/403': {
      id: '/_status/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof Status403RouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/401': {
      id: '/_status/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof Status401RouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/2fa-required': {
      id: '/_status/2fa-required'
      path: '/2fa-required'
      fullPath: '/2fa-required'
      preLoaderRoute: typeof Status2faRequiredRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_status/2fa-enabled': {
      id: '/_status/2fa-enabled'
      path: '/2fa-enabled'
      fullPath: '/2fa-enabled'
      preLoaderRoute: typeof Status2faEnabledRouteImport
      parentRoute: typeof StatusRoute
    }
    '/_deprecated/home': {
      id: '/_deprecated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof DeprecatedHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/recover-password': {
      id: '/_auth/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof AuthRecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StatusRouteChildren {
  Status2faEnabledRoute: typeof Status2faEnabledRoute
  Status2faRequiredRoute: typeof Status2faRequiredRoute
  Status401Route: typeof Status401Route
  Status403Route: typeof Status403Route
  Status404Route: typeof Status404Route
  Status500Route: typeof Status500Route
  Status503Route: typeof Status503Route
  StatusApiKeyCreatedRoute: typeof StatusApiKeyCreatedRoute
  StatusBackupCompleteRoute: typeof StatusBackupCompleteRoute
  StatusBadGatewayRoute: typeof StatusBadGatewayRoute
  StatusBadRequestRoute: typeof StatusBadRequestRoute
  StatusBandwidthExceededRoute: typeof StatusBandwidthExceededRoute
  StatusCancelledRoute: typeof StatusCancelledRoute
  StatusComingSoonRoute: typeof StatusComingSoonRoute
  StatusConflictRoute: typeof StatusConflictRoute
  StatusDeletedRoute: typeof StatusDeletedRoute
  StatusDeviceVerifiedRoute: typeof StatusDeviceVerifiedRoute
  StatusDowngradeRoute: typeof StatusDowngradeRoute
  StatusEmailSentRoute: typeof StatusEmailSentRoute
  StatusEmptyStateRoute: typeof StatusEmptyStateRoute
  StatusErrorRoute: typeof StatusErrorRoute
  StatusErrorDemoRoute: typeof StatusErrorDemoRoute
  StatusExportReadyRoute: typeof StatusExportReadyRoute
  StatusGatewayTimeoutRoute: typeof StatusGatewayTimeoutRoute
  StatusGoneRoute: typeof StatusGoneRoute
  StatusImportCompleteRoute: typeof StatusImportCompleteRoute
  StatusInfoStatesRoute: typeof StatusInfoStatesRoute
  StatusInvitationRoute: typeof StatusInvitationRoute
  StatusLoadingRoute: typeof StatusLoadingRoute
  StatusLockedRoute: typeof StatusLockedRoute
  StatusLoginRequiredRoute: typeof StatusLoginRequiredRoute
  StatusMaintenanceRoute: typeof StatusMaintenanceRoute
  StatusNoResultsRoute: typeof StatusNoResultsRoute
  StatusOfflineRoute: typeof StatusOfflineRoute
  StatusPasswordChangedRoute: typeof StatusPasswordChangedRoute
  StatusPaymentRequiredRoute: typeof StatusPaymentRequiredRoute
  StatusProcessingRoute: typeof StatusProcessingRoute
  StatusQueuedRoute: typeof StatusQueuedRoute
  StatusRateLimitedRoute: typeof StatusRateLimitedRoute
  StatusSessionExpiredRoute: typeof StatusSessionExpiredRoute
  StatusStatusRoute: typeof StatusStatusRoute
  StatusSubscriptionCancelledRoute: typeof StatusSubscriptionCancelledRoute
  StatusSuccessRoute: typeof StatusSuccessRoute
  StatusSuccessStatesRoute: typeof StatusSuccessStatesRoute
  StatusTimeoutRoute: typeof StatusTimeoutRoute
  StatusUnderConstructionRoute: typeof StatusUnderConstructionRoute
  StatusUnsupportedMediaRoute: typeof StatusUnsupportedMediaRoute
  StatusUpgradeSuccessRoute: typeof StatusUpgradeSuccessRoute
  StatusVerifyEmailRoute: typeof StatusVerifyEmailRoute
  StatusWebhookConfiguredRoute: typeof StatusWebhookConfiguredRoute
  StatusWelcomeRoute: typeof StatusWelcomeRoute
}

const StatusRouteChildren: StatusRouteChildren = {
  Status2faEnabledRoute: Status2faEnabledRoute,
  Status2faRequiredRoute: Status2faRequiredRoute,
  Status401Route: Status401Route,
  Status403Route: Status403Route,
  Status404Route: Status404Route,
  Status500Route: Status500Route,
  Status503Route: Status503Route,
  StatusApiKeyCreatedRoute: StatusApiKeyCreatedRoute,
  StatusBackupCompleteRoute: StatusBackupCompleteRoute,
  StatusBadGatewayRoute: StatusBadGatewayRoute,
  StatusBadRequestRoute: StatusBadRequestRoute,
  StatusBandwidthExceededRoute: StatusBandwidthExceededRoute,
  StatusCancelledRoute: StatusCancelledRoute,
  StatusComingSoonRoute: StatusComingSoonRoute,
  StatusConflictRoute: StatusConflictRoute,
  StatusDeletedRoute: StatusDeletedRoute,
  StatusDeviceVerifiedRoute: StatusDeviceVerifiedRoute,
  StatusDowngradeRoute: StatusDowngradeRoute,
  StatusEmailSentRoute: StatusEmailSentRoute,
  StatusEmptyStateRoute: StatusEmptyStateRoute,
  StatusErrorRoute: StatusErrorRoute,
  StatusErrorDemoRoute: StatusErrorDemoRoute,
  StatusExportReadyRoute: StatusExportReadyRoute,
  StatusGatewayTimeoutRoute: StatusGatewayTimeoutRoute,
  StatusGoneRoute: StatusGoneRoute,
  StatusImportCompleteRoute: StatusImportCompleteRoute,
  StatusInfoStatesRoute: StatusInfoStatesRoute,
  StatusInvitationRoute: StatusInvitationRoute,
  StatusLoadingRoute: StatusLoadingRoute,
  StatusLockedRoute: StatusLockedRoute,
  StatusLoginRequiredRoute: StatusLoginRequiredRoute,
  StatusMaintenanceRoute: StatusMaintenanceRoute,
  StatusNoResultsRoute: StatusNoResultsRoute,
  StatusOfflineRoute: StatusOfflineRoute,
  StatusPasswordChangedRoute: StatusPasswordChangedRoute,
  StatusPaymentRequiredRoute: StatusPaymentRequiredRoute,
  StatusProcessingRoute: StatusProcessingRoute,
  StatusQueuedRoute: StatusQueuedRoute,
  StatusRateLimitedRoute: StatusRateLimitedRoute,
  StatusSessionExpiredRoute: StatusSessionExpiredRoute,
  StatusStatusRoute: StatusStatusRoute,
  StatusSubscriptionCancelledRoute: StatusSubscriptionCancelledRoute,
  StatusSuccessRoute: StatusSuccessRoute,
  StatusSuccessStatesRoute: StatusSuccessStatesRoute,
  StatusTimeoutRoute: StatusTimeoutRoute,
  StatusUnderConstructionRoute: StatusUnderConstructionRoute,
  StatusUnsupportedMediaRoute: StatusUnsupportedMediaRoute,
  StatusUpgradeSuccessRoute: StatusUpgradeSuccessRoute,
  StatusVerifyEmailRoute: StatusVerifyEmailRoute,
  StatusWebhookConfiguredRoute: StatusWebhookConfiguredRoute,
  StatusWelcomeRoute: StatusWelcomeRoute,
}

const StatusRouteWithChildren =
  StatusRoute._addFileChildren(StatusRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatusRoute: StatusRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRecoverPasswordRoute: AuthRecoverPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  DeprecatedHomeRoute: DeprecatedHomeRoute,
  PrivatePrivateRoute: PrivatePrivateRoute,
  UserLayoutRoute: UserLayoutRoute,
  UserAdminRoute: UserAdminRoute,
  UserItemsRoute: UserItemsRoute,
  UserSettingsRoute: UserSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  Dashboard2IndexRoute: Dashboard2IndexRoute,
  ReportIndexRoute: ReportIndexRoute,
  UserIndexRoute: UserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
