import uuid

from sqlmodel import Field, SQLModel


class SchoolBase(SQLModel):
    """
    SQLModel base class for a school entry.

    Contains all the fields from the provided data, with a separate
    field for each part of the physical and mailing address.
    """

    # Unique identifier
    cds_code: str = Field(max_length=255, primary_key=True, index=True)
    nces_dist: str = Field(max_length=255)
    nces_school: str = Field(max_length=255)
    school_code: str = Field(max_length=255)

    # General school info
    status_type: str | None = Field(default=None, max_length=255)
    county: str | None = Field(default=None, max_length=255)
    district: str | None = Field(default=None, max_length=255)
    school: str | None = Field(default=None, max_length=255)

    # Physical address fields
    street: str | None = Field(default=None)
    street_abr: str | None = Field(default=None)
    city: str | None = Field(default=None, max_length=255)
    zip: str | None = Field(default=None, max_length=255)
    state: str | None = Field(default=None, max_length=255)

    # Mailing address fields
    mail_street: str | None = Field(default=None)
    mail_street_abr: str | None = Field(default=None)
    mail_city: str | None = Field(default=None, max_length=255)
    mail_zip: str | None = Field(default=None, max_length=255)
    mail_state: str | None = Field(default=None, max_length=255)

    # Contact info
    phone: str | None = Field(default=None, max_length=255)
    ext: str | None = Field(default=None, max_length=255)
    fax_number: str | None = Field(default=None, max_length=255)
    website: str | None = Field(default=None, max_length=255)

    # Dates
    open_date: str | None = Field(default=None, max_length=255)
    closed_date: str | None = Field(default=None, max_length=255)

    # Charter and funding
    charter: str | None = Field(default=None, max_length=255)
    charter_num: str | None = Field(default=None, max_length=255)
    funding_type: str | None = Field(default=None, max_length=255)

    # Various codes and types
    doc: str | None = Field(default=None, max_length=255)
    doc_type: str | None = Field(default=None, max_length=255)
    soc: str | None = Field(default=None, max_length=255)
    soc_type: str | None = Field(default=None, max_length=255)
    edops_code: str | None = Field(default=None, max_length=255)
    edops_name: str | None = Field(default=None, max_length=255)
    eil_code: str | None = Field(default=None, max_length=255)
    eil_name: str | None = Field(default=None, max_length=255)

    # Grade and program info
    gs_offered: str | None = Field(default=None, max_length=255)
    gs_served: str | None = Field(default=None, max_length=255)
    virtual: str | None = Field(default=None, max_length=255)
    magnet: str | None = Field(default=None, max_length=255)
    year_round_yn: str | None = Field(default=None, max_length=255)

    # Location and admin
    federal_dfc_district_id: str | None = Field(default=None, max_length=255)
    latitude: float | None = Field(default=None)
    longitude: float | None = Field(default=None)
    adm_fname: str | None = Field(default=None, max_length=255)
    adm_lname: str | None = Field(default=None, max_length=255)

    # Metadata
    last_up_date: str | None = Field(default=None, max_length=255)
    multilingual: str | None = Field(default=None, max_length=255)


class School(SchoolBase, table=True):
    """
    SQLModel database table class for a school entry.

    Inherits all fields from `SchoolBase` and adds the primary key.
    """

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    # id: int | None = Field(default=None, primary_key=True)


class SchoolCreate(SchoolBase):
    """
    A Pydantic model for creating new school entries. It uses the base model but
    doesn't require the ID, which will be generated by the database.
    """

    pass


class SchoolPublic(SchoolBase):
    """
    Properties to return via API, id is always required
    """

    id: uuid.UUID


class SchoolsPublic(SQLModel):
    data: list[SchoolPublic]
    count: int


class SchoolSummary(SQLModel):
    """
    Properties for a refined school view.
    """

    id: uuid.UUID
    school: str | None = None
    city: str | None = None
    county: str | None = None
    cds_code: str | None = None
    school_code: str | None = None


class SchoolsSummary(SQLModel):
    data: list[SchoolSummary]
    count: int
